language: c
compiler:
  - gcc
  - clang
branches:
  only:
    - master
    - develop

before_install:
  - sudo pip install -U cpp-coveralls

script: make && cd test && make test-full

after_success:
  - coveralls --verbose --gcov-options '\-lp' -r .. -E '.*test|.*divsufsort'
