#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#define WORD_SIZE 64
#define MASK_MSB 0x8000000000000000
#define min(a,b) ((a) < (b) ? (a) : (b))
#define max(a,b) ((a) > (b) ? (a) : (b))

char translate[256] = {[0 ... 255] = 4,
                       ['a'] = 0, ['c'] = 1, ['g'] = 2, ['t'] = 3,
                       ['A'] = 0, ['C'] = 1, ['G'] = 2, ['T'] = 3 };

typedef struct {
   uint32_t score;
   uint32_t row;
   uint32_t col;
} path_t;

typedef struct {
   double bp_thr;
   int    bp_period;
   int    bp_repeats;
   double read_error;
   double rand_error;
} alignopt_t;

void
update
(
 uint64_t   Eq,
 uint64_t * Pv,
 uint64_t * Mv,
 uint8_t  * Phin,
 uint8_t  * Mhin
 )
{
   uint64_t Xv, Xh, Ph, Mh;
   // Get current match sequence.
   Eq |= *Mhin;

   // Compute output of Xh blocks (Mh, Ph).
   Xh = (((Eq & *Pv) + *Pv) ^ *Pv) | Eq;
   Ph = *Mv | ~(Xh | *Pv);
   Mh = *Pv & Xh;

   // Save hout.
   uint8_t Phout = (Ph & MASK_MSB) > 0;
   uint8_t Mhout = (Mh & MASK_MSB) > 0;

   // Feed Ph, Mh to Xv blocks.
   Xv = Eq | *Mv;
   Ph = (Ph << 1) | *Phin;
   Mh = (Mh << 1) | *Mhin;
   *Pv = Mh | ~(Xv | Ph);
   *Mv = Ph & Xv;
   *Phin = Phout;
   *Mhin = Mhout;
}

void
fill_eq
(
 uint64_t ** Peq,
 uint8_t   * text,
 int         len
)
{
   uint32_t w = (len+WORD_SIZE-1)/WORD_SIZE;
   for (int i = 0; i < w; i++)
      for (int b = 0; b < WORD_SIZE && i*WORD_SIZE+b < len; b++)
         Peq[i][translate[text[i*WORD_SIZE+b]]] |= ((uint64_t)1) << b;
}

void
free_eq
(
 uint64_t ** Eq,
 int         words
)
{
   for (int i = 0; i < words; i++) free(Eq[i]);
   free(Eq);
}

path_t
find_min
(
 uint32_t idx,
 uint32_t score,
 uint32_t awords,
 uint64_t * Pr,
 uint64_t * Mr,
 uint64_t * Pb,
 uint64_t * Mb
 )
{
   uint32_t cur = score;
   uint32_t min = score;
   uint32_t row = 0, col = 0;
   int w = min(idx/WORD_SIZE, awords);
   int b = (w == awords ? 0 : idx%WORD_SIZE);
   // Right wing.
   for (int j = w-1, word = 0; j > 0; j--, word++) {
      uint32_t abs_min = cur - __builtin_popcountl(Pr[j]);
      if (abs_min < min) {
         for (int i = WORD_SIZE-1, bit = 1; i >= 0; i--, bit++) {
            cur += ((Mr[j] >> i) & 1) - ((Pr[j] >> i) & 1);
            if (cur < min) {
               min = cur;
               row = WORD_SIZE*word + bit;
               col = 0;
            }
         } 
      } else {
         cur = abs_min + __builtin_popcountl(Mr[j]);
      }
   }
   // Partial word.
   if (cur - __builtin_popcountl(Pr[0] >> (b ? WORD_SIZE - b : 0)) < min) {
      for (int i = WORD_SIZE-1, bit = 1; i >= (b ? WORD_SIZE - b : 0); i--, bit++) {
         cur += ((Mr[0] >> i) & 1) - ((Pr[0] >> i) & 1);
         if (cur < min) {
            min = cur;
            row = WORD_SIZE*(w-1) + bit;
            col = 0;
         }
      } 
   }
   
   // Bottom wing.
   cur = score;
   for (int j = w-1, word = 0; j > 0; j--, word++) {
      uint32_t abs_min = cur - __builtin_popcountl(Pb[j]);
      if (abs_min < min) {
         for (int i = WORD_SIZE-1, bit = 1; i >= 0; i--, bit++) {
            cur += ((Mb[j] >> i) & 1) - ((Pb[j] >> i) & 1);
            if (cur < min) {
               min = cur;
               col = WORD_SIZE*word + bit;
               row = 0;
            }
         } 
      } else {
         cur = abs_min + __builtin_popcountl(Mb[j]);
      }
   }
   // Partial word.
   if (cur - __builtin_popcountl(Pb[0] >> (b ? WORD_SIZE - b : 0)) < min) {
      for (int i = WORD_SIZE-1, bit = 1; i >= (b ? WORD_SIZE - b : 0); i--, bit++) {
         cur += ((Mb[0] >> i) & 1) - ((Pb[0] >> i) & 1);
         if (cur < min) {
            min = cur;
            col = WORD_SIZE*(w-1) + bit;
            row = 0;
         }
      } 
   }


   return (path_t){.score = min, .row = idx - row, .col = idx - col};
}

path_t
dbf_align
(
 int         qlen,
 uint8_t   * qry,
 int         rlen,
 uint8_t   * ref,
 int         dir_ref,
 int         align_w,
 alignopt_t  opt
 )
{
   if (align_w < (qlen > rlen ? qlen - rlen : rlen - qlen)) return (path_t){-1,0,0};
   // Reduce width if align_w is bigger than the available query words.
   uint32_t a_len = max(qlen,rlen);
   if (align_w > a_len) align_w = a_len;
   uint32_t awords = (align_w + WORD_SIZE - 1)/WORD_SIZE;
   align_w = awords * WORD_SIZE;

   // Number of Eq words.
   uint32_t eqwords = awords + (a_len + WORD_SIZE - 1)/WORD_SIZE;
   // Precompute query eq values.
   uint64_t ** Peq = malloc((eqwords+1)*sizeof(uint64_t*)); // Alloc 1 more to avoid segfault when shifting bits.
   for (int i = 0; i <= eqwords; i++) Peq[i] = calloc(4, sizeof(uint64_t));
   fill_eq(Peq + awords, qry, qlen);
   // Precompute ref eq values.
   uint64_t ** Req = malloc((eqwords+1)*sizeof(uint64_t*));
   for (int i = 0; i <= eqwords; i++) Req[i] = calloc(4, sizeof(uint64_t));
   fill_eq(Req + awords, ref, rlen);

   // Initialize
   // Right bitfield.
   uint64_t * Pr = calloc(awords, sizeof(uint64_t));
   uint64_t * Mr = malloc(awords * sizeof(uint64_t));
   memset(Mr, 0xFF, awords * sizeof(uint64_t));
   // Bottom bitfield.
   uint64_t * Pb = calloc(awords, sizeof(uint64_t));
   uint64_t * Mb = malloc(awords * sizeof(uint64_t));
   memset(Mb, 0xFF, awords * sizeof(uint64_t));

   // Alloc words for shifted Eq values.
   uint64_t * Eqr = malloc(awords * sizeof(uint64_t));
   uint64_t * Eqb = malloc(awords * sizeof(uint64_t));
   uint8_t    Eqc;

   // Breakpoint.
   path_t   * bp_path = malloc((a_len/opt.bp_period+1)*sizeof(path_t));
   uint32_t   bp_pos  = 0;
   uint32_t   bp_ref  = 0;
   uint32_t   bp_cnt  = 0;
   double logAe = log(opt.rand_error) - log(opt.read_error);
   double logBe = log(1-opt.rand_error) - log(1-opt.read_error);

   // Horizontal/vertical input deltas.
   uint8_t Phinr, Mhinr, Phinb, Mhinb;
   uint32_t score = 0;

   for (int i = 0; i < a_len; i++) {
      Phinr = Phinb = 1;
      Mhinr = Mhinb = 0;

      // Update Eq.
      int b = i%WORD_SIZE;
      int w = i/WORD_SIZE;
      if (b) {
         for (int j = 0; j < awords; j++)
            Eqr[j] = (Peq[w+j][translate[ref[i]]] >> b) | (Peq[w+j+1][translate[ref[i]]] << (WORD_SIZE - b));
         for (int j = 0; j < awords; j++)
            Eqb[j] = (Req[w+j][translate[qry[i]]] >> b) | (Req[w+j+1][translate[qry[i]]] << (WORD_SIZE - b));
      }
      else {
         for (int j = 0; j < awords; j++) Eqr[j] = Peq[w+j][translate[ref[i]]];
         for (int j = 0; j < awords; j++) Eqb[j] = Req[w+j][translate[qry[i]]];
      }

      // Update bitfields.
      for (int j = 0; j < awords; j++) update(Eqr[j], Pr+j, Mr+j, &Phinr, &Mhinr);
      for (int j = 0; j < awords; j++) update(Eqb[j], Pb+j, Mb+j, &Phinb, &Mhinb);

      // Compute the central cell.
      uint64_t Pvc, Mvc, Phc, Mhc;
      if (ref[i] == qry[i]) {
         Mhc = Phinb;
         Phc = Mhinb;
         Mvc = Phinr;
         Pvc = Mhinr;
      } else {
         Mhc = Phinb & Mhinr;
         Phc = !Phinb & (Mhinb | !Mhinr);
         Mvc = Phinr & Mhinb;
         Pvc = !Phinr & (Mhinr | !Mhinb);
      }

      score += Phinr - Mhinr + Pvc - Mvc;

      // Now shift the bitfields and insert center cell.
      int j;
      for (j=0; j < awords-1; j++) Pr[j] = (Pr[j] >> 1) | (Pr[j+1] << (WORD_SIZE-1));
      Pr[j] = (Pr[j] >> 1) | (Pvc << (WORD_SIZE-1));
      for (j=0; j < awords-1; j++) Mr[j] = (Mr[j] >> 1) | (Mr[j+1] << (WORD_SIZE-1));
      Mr[j] = (Mr[j] >> 1) | (Mvc << (WORD_SIZE-1));
      for (j=0; j < awords-1; j++) Pb[j] = (Pb[j] >> 1) | (Pb[j+1] << (WORD_SIZE-1));
      Pb[j] = (Pb[j] >> 1) | (Phc << (WORD_SIZE-1));
      for (j=0; j < awords-1; j++) Mb[j] = (Mb[j] >> 1) | (Mb[j+1] << (WORD_SIZE-1));
      Mb[j] = (Mb[j] >> 1) | (Mhc << (WORD_SIZE-1));

      if (i%opt.bp_period == 0) {
         // Find wing minimum.
         bp_path[bp_pos] = find_min(i, score, awords, Pr, Mr, Pb, Mb);
         // Compute likelihood of current reference.
         int Ee = bp_path[bp_pos].score - bp_path[bp_ref].score;
         int Me = i - bp_ref*opt.bp_period - Ee;
         float Je = Ee*logAe + Me*logBe;
         if (Je > opt.bp_thr) {
            bp_cnt++;
            if (bp_cnt >= opt.bp_repeats) break;
            //            fprintf(stdout, "\tML algorithm (ml=%d, i=%d) {pos = %d, be = %d (Je = %.2f)}\n", min_len, i, path_len, lastbe, Je);
         } else {
            double maxJe;
            maxJe = -INFINITY;
            for (int b = 0; b < bp_pos; b ++) {
               Ee = bp_path[bp_pos].score - bp_path[b].score;
               Me = i - b*opt.bp_period - Ee;
               Je = Ee*logAe + Me*logBe;
               if (Je > maxJe) { maxJe = Je; bp_ref = b; }
            }
            if (maxJe > opt.bp_thr) {
               bp_cnt = 1;
            }
            //            fprintf(stdout, "\tML algorithm (ml=%d, i=%d) {pos = %d, be = %d (Je = %.2f)}\n", min_len, i, path_len, lastbe, maxJe);
         }
         // Increase bp list position.
         bp_pos++;
      }
   }
   
   path_t best_bp;
   if (bp_cnt >= opt.bp_repeats) best_bp = bp_path[bp_ref];
   else best_bp = find_min(a_len-1, score, awords, Pr, Mr, Pb, Mb);
   // Free memory.
   free(Eqr);
   free(Eqb);
   free_eq(Peq, awords);
   free_eq(Req, awords);
   free(Mr); free(Pr); free(Mb); free(Pb);
   free(bp_path);

   return best_bp;
   // Compute right bottom corner score.
   /*
   if (qlen < rlen) {
      int bits  = rlen-qlen;
      int words = bits/WORD_SIZE;
      bits %= WORD_SIZE;
      for (int j = 0; j < words; j++) score += __builtin_popcountl(Mr[j]) - __builtin_popcountl(Pr[j]);
      if (bits) score += __builtin_popcountl(Mr[words] << bits) - __builtin_popcountl(Pr[words] << bits);
   } else if (qlen > rlen) {
      int bits  = qlen-rlen;
      int words = bits/WORD_SIZE;
      bits %= WORD_SIZE;
      for (int j = 0; j < words; j++) score += __builtin_popcountl(Mb[j]) - __builtin_popcountl(Pb[j]);
      if (bits) score += __builtin_popcountl(Mb[words] << bits) - __builtin_popcountl(Pb[words] << bits);
   }
   return score;
   */
}


uint64_t **
precompute_eq
(
 int        len,
 uint8_t  * text,
 uint32_t * words
)
{
   uint32_t w = (len + WORD_SIZE-1)/WORD_SIZE;
   uint64_t ** Peq = malloc((w+1)*sizeof(uint64_t*));
   for (int i = 0; i <= w; i++) Peq[i] = calloc(4, sizeof(uint64_t));
   for (int i = 0; i < w; i++)
      for (int b = 0; b < WORD_SIZE && i*WORD_SIZE+b < len; b++)
         Peq[i][translate[text[i*WORD_SIZE+b]]] |= ((uint64_t)1) << b;
   if (words != NULL) *words = w;
   return Peq;
}


uint32_t
mbf_align
(
 int         qlen,
 uint8_t   * qry,
 int         rlen,
 uint8_t   * ref,
 int         dir_ref,
 int         align_w
 )
{
   // Precompute query eq values.
   uint32_t qwords;
   uint64_t ** Peq = precompute_eq(qlen, qry, &qwords);

   // Reduce width if align_w is bigger than the available query words.
   uint32_t awords = min(qwords, (align_w + WORD_SIZE - 1)/WORD_SIZE);
   if (awords * WORD_SIZE <= rlen) align_w = awords * WORD_SIZE;
   else align_w = rlen;

   // Initialize
   // Right bitfield.
   uint64_t * Mr = calloc(awords, sizeof(uint64_t));
   uint64_t * Pr = malloc(awords * sizeof(uint64_t));
   memset(Pr, 0xFF, awords * sizeof(uint64_t));
   // Bottom bitfield.
   uint64_t * Pb = calloc(awords, sizeof(uint64_t));
   uint64_t * Mb = calloc(awords, sizeof(uint64_t));

   // Square block.
   for (int i = 0; i < align_w; i++) {
      uint32_t c = translate[ref[i]];

      // Update bitfields vertically.
      uint8_t  Phin = 1, Mhin = 0;
      for (int j = 0; j < awords; j++)
         update(Peq[j][c], Pr+j, Mr+j, &Phin, &Mhin);

      // Update Mb, Pb. (Bottom bitfield).
      uint64_t mask = ((uint64_t)1) << (i%WORD_SIZE);
      if      (Phin) Pb[i/WORD_SIZE] |= mask;
      else if (Mhin) Mb[i/WORD_SIZE] |= mask;
   }

   // Compute score at this point.
   uint32_t score = align_w;
   int last_bit = (awords * WORD_SIZE > qlen ? WORD_SIZE - (((qlen-1) % WORD_SIZE) + 1) : 0);
   int j = 0;
   for (; j < awords-1; j++) score += __builtin_popcountl(Pr[j]) - __builtin_popcountl(Mr[j]);
   score += __builtin_popcountl(Pr[j] << last_bit) - __builtin_popcountl(Mr[j] << last_bit);

   // Check whether the matrix is full.
   if (min(rlen,qlen) <= align_w) {
      free_eq(Peq, awords);
      free(Mr); free(Pr); free(Mb); free(Pb);
      return score;
   }

   // ***
   // Compute diagonals
   // ***
   int        diag_max = min(qlen, rlen);
   
   // Precompute Eq for reference.
   uint32_t rwords;
   uint64_t ** Req = precompute_eq(rlen, ref, &rwords);

   // Alloc words for shifted Eq values.
   uint64_t * Eqr = malloc(awords * sizeof(uint64_t));
   uint64_t * Eqb = malloc(awords * sizeof(uint64_t));
   uint8_t    Eqc;

   // Alloc horizontal/vertical input deltas.
   uint8_t Phinr, Mhinr, Phinb, Mhinb;
   uint8_t Pvinr = 0, Mvinr = 1, Pvinb = 0, Mvinb = 1;

   for (int d = 0, i = align_w; i < diag_max; i++, d++) {
      Phinr = Phinb = 1;
      Mhinr = Mhinb = 0;

      int bits = d%WORD_SIZE;
      if (bits) {
         for (int j = 0, s = d/WORD_SIZE; j < awords; j++) {
            Eqr[j] = (Peq[s+j][translate[ref[i]]] >> bits) | (Peq[s+j+1][translate[ref[i]]] << (WORD_SIZE - bits));
            Eqb[j] = (Req[s+j][translate[qry[i]]] >> bits) | (Req[s+j+1][translate[qry[i]]] << (WORD_SIZE - bits));
         }
      }
      else {
         for (int j = 0, s = d/WORD_SIZE; j < awords; j++) {
            Eqr[j] = Peq[s+j][translate[ref[i]]];
            Eqb[j] = Req[s+j][translate[qry[i]]];
         }
      }

      // Update bitfields.
      for (int j = 0; j < awords; j++) {
         update(Eqr[j], Pr+j, Mr+j, &Phinr, &Mhinr);
         update(Eqb[j], Pb+j, Mb+j, &Phinb, &Mhinb);
      }

      // Compute the central cell.
      uint64_t Pvc, Mvc, Phc, Mhc;
      if (ref[i] == qry[i]) {
         Mhc = Phinb;
         Phc = Mhinb;
         Mvc = Phinr;
         Pvc = Mhinr;
      } else {
         Mhc = Phinb & Mhinr;
         Phc = !Phinb & (Mhinb | !Mhinr);
         Mvc = Phinr & Mhinb;
         Pvc = !Phinr & (Mhinr | !Mhinb);;
      }

      score += Phinr - Mhinr + Pvc - Mvc;

      // Now shift the bitfields and insert center cell.
      int j = 0;
      for (; j < awords-1; j++) {
         Pr[j] = (Pr[j] >> 1) | (Pr[j+1] << (WORD_SIZE-1));
         Mr[j] = (Mr[j] >> 1) | (Mr[j+1] << (WORD_SIZE-1));
         Pb[j] = (Pb[j] >> 1) | (Pb[j+1] << (WORD_SIZE-1));
         Mb[j] = (Mb[j] >> 1) | (Mb[j+1] << (WORD_SIZE-1));
      }
      Pr[j] = (Pr[j] >> 1) | (Pvc << (WORD_SIZE-1));
      Mr[j] = (Mr[j] >> 1) | (Mvc << (WORD_SIZE-1));
      Pb[j] = (Pb[j] >> 1) | (Phc << (WORD_SIZE-1));
      Mb[j] = (Mb[j] >> 1) | (Mhc << (WORD_SIZE-1));
   }
   // Free shifted Eq values.   
   free(Eqr);
   free(Eqb);

   // Check whether the matrix is full.
   if (rlen == qlen) {
      free_eq(Peq, awords);
      free_eq(Req, awords);
      free(Mr); free(Pr); free(Mb); free(Pb);
      return score;
   }

   // If the matrix is not square, compute the last block.
   uint64_t  * Pv = (qlen > rlen ? Pb : Pr);
   uint64_t  * Mv = (qlen > rlen ? Mb : Mr);
   uint8_t   * nt = (qlen > rlen ? qry : ref);
   uint64_t ** Eq;
   if (qlen > rlen) {
      Eq = precompute_eq(awords*WORD_SIZE, ref + rlen - awords*WORD_SIZE, NULL);
   } else {
      Eq = precompute_eq(awords*WORD_SIZE, qry + qlen - awords*WORD_SIZE, NULL);
   }

   // Iterate over the remaining rows/columns.
   for (int i = min(qlen, rlen); i < max(qlen, rlen); i++) {
      uint32_t c = translate[nt[i]];

      // Update bitfields.
      uint8_t  Phin = 1, Mhin = 0;
      for (int j = 0; j < awords; j++)
         update(Eq[j][c], Pv+j, Mv+j, &Phin, &Mhin);
      score += Phin - Mhin;
      
   }

   free_eq(Peq, awords);
   free_eq(Req, awords);
   free_eq(Eq, awords);
   free(Mr); free(Pr); free(Mb); free(Pb);
   return score;
}

void
dumb_align
(
 char * q,
 char * r,
 int qlen,
 int rlen,
 int d_print
)
{
   int * m = malloc((qlen+1)*(rlen+1)*sizeof(int));
   int cols = rlen + 1;
   int rows = qlen + 1;
   m[0] = 0;
   for(int i = 1; i < cols; i++) m[i] = i;
   for(int i = 1; i < rows; i++) m[cols*i] = i;

   // Compute matrix
   for (int i = 1; i < cols; i++) {
      for (int j = 1; j < rows; j++) {
         int match = m[(i-1)+(j-1)*cols] + (r[i-1] != q[j-1]);
         int gap   = (m[(i-1)+j*cols] < m[i+(j-1)*cols] ? m[(i-1)+j*cols] : m[i+(j-1)*cols]) + 1;
         m[i+j*cols] = (match < gap ? match : gap);
      }
   }

   // Compute intermediate values.
   int words = (rlen + WORD_SIZE - 1)/WORD_SIZE;
   uint64_t * Pb = calloc(words, sizeof(uint64_t));
   uint64_t * Mb = calloc(words, sizeof(uint64_t));
   for (int j = 0; j < (rows + WORD_SIZE -1)/WORD_SIZE; j++) {
      for (int i = 0; i < cols-1; i++) {
         int dval = m[j*WORD_SIZE*cols+i+1] - m[j*WORD_SIZE*cols+i];
         if (dval > 0) Pb[i/WORD_SIZE] |= ((uint64_t)1) << (i%WORD_SIZE);
         if (dval < 0) Mb[i/WORD_SIZE] |= ((uint64_t)1) << (i%WORD_SIZE);
      }
      //fprintf(stdout, "Pb[%d] =", j);
      for (int i = 0; i < words; i++) { //fprintf(stdout, " %016lX", Pb[i]);
         Pb[i] = 0; }
      //fprintf(stdout, "\nMb[%d] =", j);
      for (int i = 0; i < words; i++) { //fprintf(stdout, " %016lX", Mb[i]);
         Mb[i] = 0; }
      //fprintf(stdout, "\n");
   }

   uint64_t Mr = 0, Pr = 0;
   for (int i = 0; i < rows - 1; i++) {
      if (i > 0 && i%64 == 0) {
         //fprintf(stdout, "Pr Mr: %016lX %016lX\n", Pr, Mr);
         Pr = Mr = 0;
      }
      int dval = m[(i+1)*cols + cols - 1] - m[i*cols + cols - 1];
      if (dval < 0) Mr |= ((uint64_t)1) << (i%WORD_SIZE);
      if (dval > 0) Pr |= ((uint64_t)1) << (i%WORD_SIZE);
   }
   // Print diagonals
   /*
   for (int i = 0; i < min(qlen,rlen) - d_print; i++) {
      fprintf(stdout, "%d\t%d\n", m[i*cols+i+d_print], m[(i+d_print)*cols+i]);
   }
   */
   /*
   for (int i = 1; i < min(qlen,rlen); i++) {
      fprintf(stdout, "%d\t(%d,%d,%d)\t%c-%c\n", i-1, m[i*cols+i-1], m[i*cols+i], m[(i-1)*cols+i],q[i-1],r[i-1]);
   }
   */
   fprintf(stdout, "align score: %d\n", m[(qlen+1)*(rlen+1)-1]);
   
}


int main(int argc, char *argv[])
{
   char * query = "GGGTGGGTCGGTTTTGGGGTGGAGAGAGAGAATATGGGGAAACTTTCCGCACAAATACTACATAATGTATGGTTTGACGCTAGTAGGAAAAATAAAGAGATAGCGAAGTGGTGTACTATGACCTGGAAGATAGTATATTGCTATCAATTTACAGATTAATCTAAGAGTAACTTTTCTGGAAGTATGTAGTTGTGTAAATTCGAAGGAATCTCTGCTATAGTTAATGTATCTTTATGTAGAGTATTCGTAAGTGATCCAAGTAAAATGAGATAAATGTAATAATATTGTCATACTGTTCTATTAAGTTTTGCATATATTAAAACTTTATTCCTCAAATGTCGGGCTATCTAAATAGGAGGATGATGTTGGGCAAGGGGATATTTGATTTGTTATATGGATGTAAAAAAAAGAAGAGGAAGCATGTCAATTTCATAAGCGCGCACGCGACATTTCTATTCTTGGCTAATCCGTACTATAGTTCAAGTAGAAGGAGAATAAAAGTAGTGTAAGCGGAAAGTCTTTTTTAAAAAACTGTACCTAAAGGCTAAAAAAGTGAAACATTTGGTTGGTCTCACCAGAACTTGCTAAGTTTGTTGGCGATGGCTGAAGTTACCGTTATTTTGAAAGATCCCAGAATATCTGTGCTAGGGAAAGGTCCTAAGTAAGTTTAAAGAATCCAGTGTTCAACCAAATCAGTCTCCCCTAAGGGCGTCTAAGCTAATGAGAGATGATCCCTTTAGGAAGCTGAAAGGTTTTGTAATAGAGGAGTTCAAAGAAGGCAAGTCTCACGATGGCAGAGTTTATATAAATATCAAAAATATGTCACTGATGTTTAATGTGTAAGTTATCATAATTGTATGGTTCAACACACCTTGGTAATTATTACTATGTAGAAATTAAGTGCAGCTTTATGAATGTTAACGAAATATGTGCAGGAAAAGTCATAAAACGATTGAGCTGTAGTAGATAATATAAAACAGACTATCTAAACTAAAAGTTTCCTGGATCTTACTTCGCTAAAAGCCTCGAAGACCCTTTTGTCCCTTTTATTTAGTATATCTTTTATTTTAGAGCAGTTCTTCTGGCCCTGTCAAACTACCGTGTATTGTTTTCGAAGTTAATCGGAGTTGATAAGAGGAACTAGAGAAGCAGATGCCGTTCCACAGGTTTGATGGCACATTACATAAGAGTGTTTTTCTGCTGCAGTAGCAGGACATTGATAAGGTAGTGGTGCTGGGCTGAGCGATTCATCTCGTGGTCGCACTACTATCAGCAGACATAAAGTGGCCTTCTCGTCCACTATGCTTCATGTTAGTGAAATAAAGTTAAATGATGAGTAAATACAAGTTGGAGGTCAGTCTATATGAGCTAAGGATATCAGTAAAGTTTTTATGATTTTATTTCATGTCATAGCTTAACAGCACCGATTAACTGATGTATTTTAAAATCAGTAGTTGTGTTCAGTGTAAATCTACTGCCAAATAAACTAAATTAATAGTTCCGTATTCGTCAAACATTAGTTCGGAGATCAGTTAAAAAGTTTTTCCATGATTTATAATGCGTTGTCAAGTGGGCCCCTAAATACTGGCAGGCCAATTATTTTCGATTGGAGTCTATCACGCTTCTTGACTTGTGAACCTCCCTCAAGACAGTCAAGCATCTGCCTTGCCCATTGTAAAGTACTCTCGAAGGTGACAATCCCTGCTTCATATTTCACTGAGAAAGAATCAATGACATGAGGGTGACAGTTTCATCACTGAAAATCCATCAATTTCGCGAATTTTATACTGAAGATCCTACATTTAATTGATATCATTCTGCAGTTTTCCCCAGTGCTACATCATCCATGTTCTCACTTCCATTTGGATTATGTAATACAAATAACTGGATGTCTCCTCATATTAAAAAAACTCAAAAAGAATAACAAAGACCTTGACCTACTTGCTCCCCATCGTCTAGCTCCCTATTCAAAACCGTTGAGACCTCCAAGTCGTTCTATCTAAGCTCCACTTTCTGCTCTATCTGGCCTTCTACTAATTGATAACTTTTGTCAAGAGCAGCCTGCTGACTCCCATCTGTTACTTAAATCCACGTCAGTTCTCAGTCTTCAAGTCTCCGCCTAACACATTGTAATTGTACTTAAATTACTCAGCTCCCATCTGGAATAACTTCCTTGCACTTGGGATTCCAGGGAGCCCTCTTTCATGGGTTTTCCTCCTCTACTGGCTGTCCCGTTCCTTGAGTTACCTCTGGCTGGTTCTCACCCATTCTCGTCAGAACTCATAAAGTTAGAGTGCCTCAGGGCCTCTTTTATTCTCTTCTGTCCACATTCACGTCTCTTGTGACTTTAGGGCTCAGGGTTACAGCTTTAAAATACCTGTCATATGCTGATGACTGCCAAACGCTAATGATGCTAACTGTTATCTTCACTCAAACCAGTCCCCTGAACTGCAGACTATAATAACCAGAATTTGCTATTGCACACCTCTATTCAGAAATTTAAGTTCATCTCATAATTTAAACACACATACAGAACTGTACTCGTAAATTCTAGGCACTTCTCACTTAAACTAGTTCTAAAGCCCACAACCTTCTCATCTCATTTAATGGCAGATCCATCTTATAGGGGTCAGCGCCCGCAAACCTCAGAAAATCATCTTTGACTCTCTTCCAACCGACTTCACAAAATACAAATCTTGTTTGCAAATTCCATTATTCTAAAAATTTAAATATATCCAGATATACTACGTACTATTATTCTTTCAGCCTGCTGCCACCAGTGGGCTGGCCTGAACCGAACCATCACCTTGCTTGGGTTTTATCTAAAGATTCCTGTTTACGCCTGATTCCACTCTCTATAACTGCTAATACCAGTCAGAATGATCCTCTTAAGCTGCATTCTGGACATTCTATGCTACTTCTGGACGATCTGACTATTCCTATTAGTCCCCACCCCTGCTTAGTTTCGCTATCAACCCACTGCTGGCTTCCTTGGTTCCTTGAACAGGTTAACATGTTTGTGAACACATATTACAATTCTATCTGTCCTGATTCTAATATAATAAGCTATCATAAGATAGTGGTGATTAAAAAGACTAAAAAACAAACAACCTCATCTTGTTTTTTACCCTTGCATAATGCTGAGATGCAGAATTGCAAACGAAGTGTGCAATACAATCACATTTTATAGGGTTTTTCTTCCACCATGATGCAGCGGACTATGCGAGCACTACTGAAACATCTTACTGAGCAAATCCTTATCCACAACCAATTCACATTTGTATGCTTCTCACACTAAAGGAACAATAAAAATTTATATTTAGAAAAAAAGTGTTGGTGCATAAAGTCATGATAATATTTCAATCAACAGTAGTGAGCTTTGGTTATTGAATGAAAATGTAAACTGTTGGAACTGAAAACAAATATAATCTTTTCCCAGACCATGATAACACCAGTAGAGATCAAAAGAAATTAGTGTTTCTGAATTCACGAGATATATCATACAGCTATTTGAAAAAGTAGAATCTAGGGCTGGCTCTGGTGGCTCACTCCTATAACCCAGCACTATTTGAACAGGCGAGCGGGCAGGATCACGAGTTCAGGAGATCGAGACATCCTGGCTAACAATGGTGAAACCTCTCTACTAAAAAACAAAAAATGTAGCCGGACTTGGTGGGGCATGTCACTGAAACTGCCGCTCTACGGGAGCGAAGGCAGCAGAATGCTTGAAACGTCCGGAGGGCGAGCTTGCAGTGAGCCGAGATGCCCACAACTTGTACCCATGCCTGGGCGACCAGTGAGACTCTGTCTCAGAAAAAAAAAAAGAAAAAAGTATTCGAAAATGTAAAAGTACCAATAGGTGCTCATACTTTACACCAGGCAGAGGACATCAAAATAAGAGGTAACTGTAGAGCTTAGGAAACCACTGTATGTGTAATTCCAATGAACAATGTCTCCAGAAGTCAACAGAGTCAGAAGTAATGTAATGAAATGTTGCAATATCTGAAATTGGCCCTGAAATTGTTAATTACATTTTTCTCTTTATCAGTTTTTTTGAAACAATGTCTTTGTCTCTGTTAAATACTTGGTAACTAGAATCAACAATACTTTATTTGGAGGGAAATGGTATAACAGGAGTTGATGCATTAGGCGCTTAAACAGCGCATTAAATACCTTGGTTTACAATTTCAAATAAATTTCAACCATTTAAACACTGTAAATATTGATGAATAGAAAAATATACCAAGATTCTGGTCAACTAAGTAGTGTGTGCTAAGTACTCTCCTATAAAAATAACCCTATATTAGTCAGCAGTATAAAAAAAACCCCGTAATACTCCCCACACACCCGTCTCACCATTATGATTCCTTACACATGCGTTTTCAGTGGTTTACATGGGTAAATGCTTTCCACATAAGTGGCCAGACAGTAAGTTTTACTCCTTTATGTATTCTCATGTGCCTTCTCAAACTGCTGGCATCTAGAAAAGCACTTTCCCACATGTGTTAATCACATTGGCTGGCCTAATCGGAAATACCTCTGATCGCAGCTCTTCCCCGAGTTCTCCGCTCATAAGAGACTCTTGACGCGCTGGCTATCATTAGACATAGGTGTTCTTTCAGAGCAACAGTTGTGCTGTGGATTTTCACGTTTCCGTTTCACTGTAAAGCTGTGCACAAATATCTTGAGTGCTGGAAAAGATTTTCCACAACTGAATGTCAACCTCGACGTCTGATTATCATACTTATTTGTGCAACCTTGTTCTACTACAGGTGTGGGCAGTTTATTTGCATCAGAATAATTCAACAGATTGCATTACTCTAAGAATGTCACTGGGTATATTCACTGCGTTTTAATTCTGTCCCCACTGTTTCGTGGGTAGTTGAAAGCCTCTTCTCTTTTCGTTGACGAGACTTTTTCGGTCTAACTGCGCCTTGTTTATGCGATTTGCCTGAATCAAATCTGTAGATACTGCTGATTCTCTCGATTATTAATAATTCTGGCCAGAGTAAGAAGCAGCAAAGTCCTGGTTGAATGTCAATCAATGTTTCCAGTAATACTAGATATCCTCTGTAGAAAAAGATTACGCAATAAAATCAAAATCTCCAATCTTTATTTTCATTTAGTGACCACCTCTTCCACTTTTGAGCATAAGTCCAGCCTGATGAATTTCTTTAACATGTCCAACTGCAAGGAAACAAGGCTACATGACAAAATCGATGCAAAGAAAAACTTCGAAAACAGGAGCTGCATATATATCTGTAAATGTATTCTAAGACCTAATGAAGCAGAATGCTGAAAAAGCACATATACTAGAGAAAATAAGATTTAAAGATATTCATCAGTATGGTTAGCGTAAAAAATCTCCAATTTTACAGAACTTGGTCAGAGATTAAAGATAATGGCTATCACAGCTGACAGTGAACCACTGCAGAAAAATTAAATGTTATAATTGTTCTGGCTTTTTTTTAAAACCCTAGAACACAAAAAATAGACTGATGGTAACTCACAGACTCCTCCATTCATCGCTGAGGCTCTCAGATAGCAACCAACTTTCTGGATTGGCAAGAGGGAAAGTCTATATGACCACTTGTTTGCCAGTATCTATTTTCTCCTGCTACCCTTAGGGACTCTTACATTATCGTTTGCCCAACTTTCTGCCTGTGCATGTCGGAATGCACCCGGAATCTTTTAAATGTAGATCAAAATTCAGTAGGTCTGTGATGGGGCCAGTCTGAGATCTGCATTATTTCTGTCTTAGATGGGTATTCTTCTGTTGCGCCTAAGCAGGAGTGCACTGGTATATATGATAGACTCACCGCAAGAACTTCAATCCTGGCTCGGCTGCTCAGCTTCCGCAAGTAACGTTGGGACACAAGGCCATTTGCTACATGACCTGGCTATTTTTTTTATAGATGCAGGTCTGCTATGCTGCCCGGCTGGTCTCGACTCGCTGGCTCAAGTGATCCTTCCCACCTTGGGCTCCAAGTGCTAAGGATTACAAGCTGATTGCACCCAGCACAGCCTGCATTTCTAATAACAGCTTCCTGGTGATGCCAATGTTGCTACGAGGAATCCACCGTAGAGGAACACCAGTTTAGAATGTAAACTCTCTCTAGCAACCCTACCACCTTTTTGTGAACTACCAAATAAGCTGGAGTGTTCGTGAGTGAGAGCTTACAAAGAAAGACTTAAGCTCACTTCGTCCCTCACATATCTAGTCAAATGTTTACTAAGTCATCTACGATGTGAGGTACTAAAATATTAATAAGTAAATAGTCCTGCCGTTCAAGAAGTTCACAATGTGGTGAACGTGTTTGATAATCTAGCACGGCTCTGGCATTACTCTGCTGACTTAATTAGGGGTAATTCAGCATCTTGGGGTTCAAGCTTTCTTAAGAATGTAAATAGAGTTGAGTTGGTTAACACTAAAAACAGTGACTGTTATAAGTATGCTGAGGATGTAAACGCGTATATCAGTAATTAACCGCCGTCTCACACACACCATCAACACACACCCCTTACCCTCAAATAATCTTCCTACTTGATTTTTCCCTAAATATGGTTTATCTTTGGGAAAGATGATCTCTTTCCCTCTCTGTTGTAAAGTATAAGCCAGAAAAAGGTTTAATCATAACGACAATGTAAATAAAGTGCTGTGATATCTATTTTATAAAGGACTAAAATTGAATTAAAATAAAAATAGCTTAGTTGCATGAACCCTCTAAAGATCTCTATATAGTATGCTAAGTATCTACAAATCTCTACCCACATGTTCTCATCATCTTCTAATTAAACTGCTTTGCCTCAAGTGCACCTGGATGTTTCCCCTTATTAAATAATGTTTAGCATCACAACACTTCTAAAAATATGTCTTTTGGTCCTGGGCCACTAAAAAGATCTTTGGTCTCTAAATTGTGTTTAAGTGCTCGCAATAAAATAAACCGCCAAACAGATAACAAAGGTCAGGTAGCCTTTAAGACGCAATATAAGTTAGCAGGAAGTCATACCACATTAATTGTTCAAGCAGGTCAGGTGCCTATCCCTTAAGACGCCTAAGGTCGGCGCATCACCTGAGGTCAGGAGTTCAAGAACCCAGCTGCCAACATGTAAAACGCCGTGATCTACAAAATAACAAAAATTAGCTGGGCATTGATGGCGTTGCCTGTAATTCCAACGCTACTCGGTGAGGCTGAGCAGGAGAATCCCTTGAACGCTGGGAGGTGGAGTTTGCAGTGAGCCCAGACTCAACAGCCATTGCATCCCACCTGGGGACAGAGTGAGACTCCATCTCAAAAAAAAAAAAAAAAAAAAAAATAATTTGTTCATTCATGAAATGGTAATTCATACAAACTATTTCCAATAAGATGGCTATAATTCAGTCACATGTAAGCAGCACTAATGCAATACTTCATAACAGATATTGTCTTTTGTTTACAAAGTATTAGATAACATCCTCTGAACAGTCACTGAAGGTCATTAATTACATATTGCCAAAGGTACATGTCCTAAATGCTTATAAGATTACCTCAGGACATGCCTATGAAAATCTATTATTAATCCTCATTTTAAACAACACAATGAAAAATCTAGTAGTCCAAAGAAATAAATAACCTGTCCAAAGCACAGAATGTTAGAAACCAGATTTGAGCCAAGGTAATCATGGCCCCTTGATGCAAACTTAATATATCCTACCTGTTTCTTTAATCACGTAAGTTGTAACAATTTCTATTGGTATAACATCCTCTTTACATGTTCTAGCTGAACTCGAGAATTAGCTCACCATCAAGTCTCACAGGAGAAGAATATGTACTGCTAAAAGCAGACTGAACAAAACACCTGGCCATTCTTCAAAGCATTGGTTTCTTTGAATAATCTCAAAGAAAATGTGCCTACCGGTGATTCAAATGAAGATTGTTTTGTTTTTGCATAGTAATTGAGATGAAAGGGAAACCATTATAATTGCAGGCCAGCCAAAAATTCACCACCTGCTCTTCGCTTAATCAACTATACAAGAACTCACATTTGAAGATTTCATTATAGCCAAAATTTAAAATAATTCCAAATAGCATGAAAGTTTACTTTTCTGTCACCTCCCTGCCGCTCACACTGGATACTTCTTACACAAGAAGGTCCTCGTCAAAAAGATTAATGAGCACCCTGATCTAGATTTTTAAATAGATATATTTCCAAGATAATTACAATATAAAGTGAGGAAAGATTATTGCTAATTATACATGAACATCTCTAACAAGTAGATCTGAAAAGAATAATAATATATAATTCAAAAGGTAAACAGGGGTTATCAGGGCAGCATATTTCAGAAAGTGTGTTTCTGTTTTTGTTTTTTCTATTTTTTCTCCGATAAATGTGAATTAAAGGGGTGAGGCAGAGGTAAAGTAAAAAAATAAAGAATTAACGTTCAGTTGAAGTGATAAGGATTCAATTAAAACTTATTTAGCCTCAAGGTAGTTATTAAACCATCTCATTTGAACAGATGGGGAAACTGAGGCCCAAGAGAGATTTGCATCGCATGCTCAAGAGAGACATAGCGACTGACAAAAGATCTAATTCCAAAGCCTATAATCTCCTGTGTCAGAAAGAGTTAATGAACATATATTCATGTTCACTTTCATATAGAGAGCACAGATATAAGCAGGGGTAATTAATCAGTTTTCTCTTGCTTTTATTCCCCGCCAACCTTTTTACCCTACAATCTGTAAATGTAATTGATATTAATCTGCAATTTATATTGGTTTCTTATAGCAAGGGGAGACACCAGTGCCTACATTATCAGATTCTCAGAAGCGCCAACTTCTTGTTAATGCAGGACATCAAAGTAACAATGTTAAGAGAATTCATTTAGCATCTCTCTGACCTTTATACTTCAGTATTTAAGTACTGGTAGGTTAATAGAGAATAACGATGAGCAGAATGAGGGAGACAGAAATCCAGAGGAATTCAAGGACAAAAAGCAATTGGGAAACTGGAAGTAACTAGAATTATTTGTTTGCAAGCCCTGGACCAGCATGGTGAAAGCCCTGTCTCACCAAAAAAATAGCAAACATTAGCCAGGTGTGGTAGTGCACACCTGTTAGTTCCAGTTACGGAGGAGGCTGAAGGTGGAGAATCTGCTTGAACCCGAGGCAGAGTGCAGTGAGCCGAGAATTGCCGCCGACTGCACTCGGCAGCCTGGGTGACCGGGAGCCCGTCTGCAAAAATAAAATAAAATAAACTTCATTGTGTTAATGTTCAAGTTTACATAAGTGAAATCACGCCCTGTAGGCTTTGTTTCAAGTAAATAAACCGTGTCAGAAATCTTACGTTTATTATCTGTGCTATATGAAAAATATGCTGCTCATCCCTAAAAATCAGTGAACCTGATTTCTTTATAAAAAAAATCATTTGTGCATAATAGGTGAAAATTTAGTCAGAGAATGAATGGAAAAAAAGCAAATCTACTTTTTGCTGTGAAGACCTGACTAGCTTTTAAAACTGAAATAAAATTGTACTTTACCTGTCATAGATTAAAAGTTCCTGTGTATATAAACTCCCAACAGTTTCTGAAAATCCATCAGCGTCATCCTGACTCTTTGAACAAGAAAGACATTGTCTCAGAAAGTGCTTCGTCAGATCCCAAAAACTCACTAAAGGAAGCAGCACATTCTACTGAGCTTTAAAACACTGGAATTCCACGCAATCACATATGGTAACCATGTCACAGGAAACCTTGCTTCCCGCTGTTGTTCAGTGCTTCTCTAAAATGTGCTCACAGTGGTTGCGAAACTGCATTTTGAATCAGAATGGAATACCTCTTGATCATAAAAAACAAAAAGAAACAGTAATCTAGAATCTCTGAAGTCTCATCACCGTCAGTAGCGGAAGGACAGAGTACTAACTTAATAAATTTTTAGCCTCCCTTAAAATTCCTTAAGTCAAGATTTCCGATATTATGTTAAAGAATGAAGGGATCGATGCGCTTTCCTATGCTTTGTTACCTTCCGATCAAACTCACAATCTGTTTGACATCCACAATAAAGACGGTGAACTGGCAACACACTCTCTAAACACCTCTAAAAAGCAGCAGCAAACCTGACGCTTTCAGCATCTGTTGAACCTCAGAATTTTCAAGCTCACAGTAGACATACTTAGTACAGATTTTTAACCACTAAGACATGATCCTTGGACAGATAGGGCAGAACAGTACGAGTTTTAAAAACTGGCGTACCGGAAGATCACCAAAAACCTGTATTCGGCCCAGTGCAGTTTCTACTCCAAAACGAGAGGCGGCTGCCAGAAAGCGGGAATTCGCCCGCGCCATGGCTGCGTCAAAGGTCTATCACTCGCGCTCTAAGCAGGCCACACCTTCTCTTCCCACTCTCTACGCCGAGGCGGCATCCGGAGTGACAACCAAAGCCATCCCTCCTCGCTTCTGCCGCCCTGCCTCGTGCCCAAGCTCCCACTCCGGCGAATTCCACAACTGCAGAGGTGTGCCCAGGCCACCGACCGGCTGCCTAGCCGCAAAGCCTGCCACCTGCAGCCCCGACCCGTGCTGGAACTGACACAAGGAGCGCTGCCCTCCTTGATGGCCCAAAGGCTCTAGAGAGACCGGGGATGGCGGGCTGGGTGAAGTCAGGAACTACACCGATAGCAGAACTCCAAGGGGGGAACACAGTCTTCACTCTTCTCCCCATGCATCTGGAGACGCAGCCGAGGCCACGCTCTCCGCCCTCCCTATCGCTATCCACGGTGGCGTCACGTCCGCTCTGTCTTCCCGGGCAGTGTCGGGAGGGTTCTGGGCCATGGGGTCGCGGTCGCCGGCCAGGGCGGCTACCAGAGCTACCACAGAGATGGCGCACTCCCCAGCCATGCCAGTGGGTCCCCCGAAGCAGCAGGCGTCATGGATGACGAGAGTGAGGCTCGCTTAGCTGCGCAGCGCTCCGCCTGTCCTTCCCTCCATCGCGAGCATTTCTGTGCCGGCCATGTCAGCGTCTGTCGCTCTGTCGGCTCTGCGCCGAGGCCCGGCAGCACAGCACCGCGGAAGGCCTCAATCTCCTAAGCCAGCTGCGCACTGCGCTGCGGGGGCATTGTAGTTGCTTTGTCCTCTCGCCCATCATCCCTCCTTCGCGTCGGGGCCCCACCGGGAAACTGCTGCATGTTAACGGATCTCTGCAAATGGGGATTTTTTAGCTGAAATCTTGCAGCCCCTTTCCGCTAACGTACCTGAAAACTCTTGGCACCTGCGGCCCTGGTTTTTTGTGCCCCAGCTCAACTGTACCTCAGCTCCAAGAATGCCCTAACCTGGTGAACAGAATCGGGATGCACGAAAGCGGAGCAGACTGGGCACAGTCGGGCATCGCAACATTAGAGAAGGTGGCTTATACCGGAAAAAGGTTTTCGCTGCGTCTGGACAATAGATTTTAATGAACATTATTTACCAGCCACTCAGACAAAAACCAAGTGATATAATACACAAAATGCTCAAGTGAGGCGACAGGACTAACACTTTTACACTTGATCTTTCCTTCTAGCTGTACATATTTTTCAGTGTAGCTGATGAGTCAAATTCATTTTTTAAAACCCGGACAACATTATCCACGTGGCAAGGCTTCAAAAAAAACATTTGTGAACGAATAAAGTACAAAAAACTTAACAGATTTTTTTATTTCAGCTCTCATTGCTATCATGTCTTTGAACGGACGGCATACATAAAGCTAGCTTCCCTCAGAAAAAAAACAAAACAACACCAAAAGAAAAAAAGCGTGAAATCTCACGTTTCTCCAAGCGAAGCGAAAAAAAAAAAAAAAAAAAAAAGGGATTTAGTGTTTTCGCCACGGTTCGAACGCGGGGAGCCTTTTCGAGTGTTAGGCAACGTGATAAACTAACCTACGGAAACTCCATTGGAAAAGGGTTTTTGTAAAGTCCTTGATAGAAGTGCAATTCGCAATTCCAAGTGATATTACAAATTGAGAGAATGAATATAAGTATTAAAGAAAAAACAGAAAAGGAAAAAATAGCTATGCCCAATTTTGAACAGAGTCTAAAACCCATTTCAAAAGCTTGAATTGCACGCCTTTCTCAAAGTGCCTCGGTACCCGCAGTAAAACCATGCACTCGCGAGTTGCCCTTCCTTTGGGTGGCCTTTTTTTTTTGTCTCACCTGAAAGCGTTTTATTACACATCCTTTCCGCAGGTGAGCTGCTAGAGTCCGGGAAAGAAGCAGGGGCTTTCGTTATTCAGCCGCGAAAAAGCATCCTTTCAGCTTCTGGTGGAAGAACGTGTAGAAATTACTTTTGAATTTCCTACTATTTTGCTTCCGAAGACCAAGCAGAAGTTCTAGAATTGACTGTTGTTTTCAAATTCTCTACAGATGTATCAGCAATCAGACACCAAATGCTTATGACATGGCAAATGTAACTTTCAAATTTTCCACAACGTGAATTTCATGATGACCTGAATAAACTTCACTTTCTGGCAAAAAGACAGGCACGTCCTTACAGCCTAAAAATCAAGAGTACGAATTAGGCTGCCGATACACCAAAAGGATAGAATCGAAATATATATATTATATTTATATAGATAAATATAAATTTTTATACTATTATATATAAACATAAGATTTGTATATACTTTATTATATAACAACATAAATTTGTATATATTATATATATAACGGCACAAATTTATACTATATTTTATATATAAACATAATTTGTATATATTATTTATAAATAGAACATAATTTTTTATATTTATGATATATAAACAAATTTTATATTATTATACTAATAAACATCTTAATTTTTAATATATTTATATATAAACATTAATTTATATATTTATTATATAAATAAATATAATTTTTATATATTCCTGATATATAAATATACAGTTTTATATATTATGATATATAAATATAATTTTATATATTTATGATATATAAATATAAATTTATATATTTATGATATATAAATACAATTTTATATATTTATGAATATAAATATAAATTTTTATATATAGAATATAAATATAAATTATATATAAATCTTAATATAGGTATAAATTTTTATAATACTTTATGATAAAAATAAATTTTATTTATCATATCTAAATATAAATTTTATTTAGTGATACTAAATATGAAATTTTTATTTATGACGATACTAAATATAAAATTGGTTTATTTATCAGATATCTAAATATATA"; 
   char *   ref = "AATTCAACTGACAATGTGAAAACCTTCATTAATCCTAAAAACAAAGAAAAAAAGGATTCTTGAAATCTATGGAAAAAAAGTGAACATATGCAAAAGGCTAGCCAATCTGAGAATAATTACTGAAGGATTATTTGAAGTACCATTAAAAACATAATGAAGTACATATCTTGAGTCAGTATTGTATGCATTAAGTAACAAGTATGCTAAATACAAAATGTCAAGCTGTTAATATGAATACTACTGTAATATACACAATTAAGCAAATCTTTAGAAAAACACATTATCAATAACAATGACTTGAAGAGGTACAAAATACATATGAATTAAAATAGAATTTATTATATTACAAATAATAATGATATATTAAATTGAGCTTAGACCTAATAGAAAGAAACAACTTCAAACTTTCCATTTTCACTGTAGTGTCTTTGTTGAATTGCTAAATATTAGGTACAAATGCTCAAAGAGGATGTTTTTATGGCATACAGCAGAAAACTAGGTTAATATTCACATGTAGTCATGGTTTTGAGGTTTTTGACTATTACGCCTTTTAATTAATGATTTAGCAACCTTGTTTATTGAATGCATTTCTTTGGTAATTTTATTCTCAAACCCTATCTTAACTTTTTACTACCAAGATGATGATATGAATTATGAAAGTAATCGGCAATAAATACTTTTATATATAAACTCCGTTTACTAAAAAGAATCAATATTAAAGAGAAGCATTGAAAATATTATGAATCCAAATACCCAATTTTCCTTTTTTTTATGGCAACAACATTGTAGAGTTCCCCTATTTTTGTCCTCATGAATATATTTGAGAGAGTAATCACGTCCAGCATTTAGCAATATCATATTGTGGAGGGGTGTTTGTCGGATAAATCATATAAAATCCCGTGAGAAGAATACTTAAAATAACTACTCAATATCCATAATATGGATTTTCTATGGTAACTTTTTAATCAGAATATTAGTATTGTAAAAATTAGATTTTGCTTCGAAAAAATAATTCATGATTTTTTTAAGAAAACAAATGCAAAATCCAAAAAAGTCTTATAAAAATGCAAGAACCTATAGAGACATGTCATTATACAAATACTTTTTCACTCACACTGCTCACATATTGAAAATATCTATTGAAAATGAAAAGCAAAAATGTGGATCTCAGCTTAACCCTTTCATATAAAATACAACATTCTAATTTACTGAAAATCAATGTTACATTCCATTAGCAGGGTTCAACATAAGACATCCTTCAAGTCTTTCTATAAGTTCTAAAAGACAATGGTATAGAACAAGAAAAATACCAAGATGACACATAAATAATACGTAGCAAAGTGTTTGTGTTTTTCTTACGAAATAGTAGTAATTTTGTTAGCATTTTCTATGCGGCAAGTTTGTACTTCACAAGTCCTGTAGTGGTCACAGCAGTTTTTGCTGTGTTCTTTAATTATAGCTTAACTATTCTCATAGCATATCCTTGTATGATATACTTAATAAATAAAGGATATAGAGAGGCAATGTATCTATATCATGACTCTGATAAATTCTGCCTTGTCACCACAGAAAACCTTGATCACGGTCACTGACAATTTTCAACAAAGCTAGAAAATACAAGAAATATCAAGACTTCATGCTCCACTCTAACTCTGTCTTATTTTGACATAAAACTCAAACATTTTACTTGATGTTATGCTTACGCTACATCAGTTATATGCATAGCCCAACCTTTATTCATGTTTGCCTACAAAAATATGTCTTGGCAAATGTGCACATGCAAATGAATTGAGCCCAACAAATGAGTTCCCAACAAATGTGTTGATTTCTCTCTAAAATATGGCCAGACAAGATTGTGTAATTCTACATGGCCATATTATTAAACTTGTAAAAATTATATGCTGACCTGTCTCTAATAAATTATTCTGTATAATTATTCATAGCTACAGCTTAACAGTTTTCTAAAAAACTCTTACATCGACTATACCTTCAAATATGATTAAACTCCCTTTTAAATTTCCCTTGGCAATAGTGTTTTACATAGGTCACAATAATGGATAACCTTTATGTTCATTTTAATCGTGACTCATATAAAAAACAGTGCAAAATGTCCCATGTTCTACTGCTTCATATTTTAGGGAAGTTTGAATTTGTTAGCAAATCCTTTTAGCTGTTCTATTGTTGAAGGCTAAAACATTAATCTTCAAACAGAAATAAAAATTTTTACATACATTTGCCCATTTGCTTGTTCAGGATATAAAAACCAACTAAACAATAGCAATTAAGAGAGGCTACAGGCCCGGCACGATCGGCTCACACCTGTAATCCCAGCACTGTTGAGCGAGCGGGTCGATACTTAGGTCAGTGAGTTTGAGAACAGGCCTCACCCACATGGTGAAGACCCGATCTCGTACTAAAAATACAAAATTAGCCGGCATCTGGTGGCAAATGCATAATCGCAGTACTTGGGAGCCTGAGGCTGGAGAATTGCTTGTAGCCTGCGAGGCAGAGGTTGCAGTGGAGCTGAGACGCGCCATTGCACTCCAGCCTGGGCAACAAAACAAACTCCGTCTCAAAAAAAAAAAAAAAAAAAAAAAAAAGAGAGAGACAGAGAAGAGAGAGAGCTGCTAATCAGTCGATATAGAACATACTATACGTTTTCAATCATCAATAAAACATTAATGTCATTGGTGTTGCATTTCCCTTGAGCATGAGAGACTGTGTGACATAAACTAAAGATCAATTACTTTAATGAATCAATACTACAAGTTCTTTGTTATAGAATTTTTCAGAATAAGGAAATAAAATTGAATGTATAGGCATACTTTGAATTGTGATTCTATTCTTACTAACTTTAGTTCCATTTCTTCACTCTAAAACTCTTCATTGAGTAAGCTATCTTTTGCAATTATCTTACTACCAAGAGATTGATATTCGTCTAATGCCACAAATATTATAATTATTACTAAATTCTACCAATTCTAGGTACAATTGAATTGTTTTAACAGTACCTGTATAAAAGTCATTTATTCACCATAAGCTTTCAATCAAAATAATATGTGACTCTGACTACCCTCCACCTAGTTAAATTGTTTCCTCTTGCTGCCCCCTTTAAGCAAATTATATTCCTCCCATTCACCCTTCCTGATCCAACGACCTCAGCCACTAATCCTGATTTCTTGAACACACAGTTGGTCTGCCACGAAAGGATTAGTTATTTTGTCTTCGCACGGTCTCGTGACTTCAGTAAGCTCGGAATCCATACAAAATATCTATATTGTCATTGCATGCTCTTCCCTTACTCATCATGTTTTTGAAGTTTCACTTCTATTAGTGTACCTCCTTTTGTCTTAGTAGAGGTGTTAAAAATATGCCGCACATGTGTTATCCAATCTTCTGTTATTAACATTTTGATTATTTCATTTTTCTTCTCCCTGTTTGGTTACTATGATGAATATGTAATAAACATCTTTGTTAAAAGTGCTTATATTAATGATAAATGTGAATGTTAATATACTTTTATAGACTAAATAGCTGCGGAATCTTATGCTCGTGCCGCCGAGCGAGTGTAGAACCTCTCTATTGCGCATTCATCTAAATGTAGGGCCTGCTTTGTCGAAATAAATGGATCAATCATGCCCTGCAATTTACACAGATTGTAAAGTTATGTTCAAAATATAATCCCTTTAAGATGCGAACGTGTTCAAGGAAAACATTGAGCTAGGAGGAAGTGGAGGCTTGCGTGTAGAGTTGGGCAATCTTAGCAAAGGTTTCCTACTTGCGGCAACTTCTCGCAAGCCATCCTACCTCCATACAAACACATAGACAAAAAGCACCAAATCTCGCTGACCACTACTACTATGATCATGCAGCATCATCCTGTTCAATAACCAACAAGAAAAAATTATCTAATTATCCTTTCCTGGCCAATTTTGCCCTGACAGTTTTGTAGGCAAGTACTCACAATTGTAAATTAAACATCAACCGCTCCACGGAACCACACGCTTCGCCTATCCATCTACCCTCTTCCCTGAAAAGCCCAATAGTTTTAGAACCAACTCCAGGAGTGATTCCAGCGGTTTCACAGAACACCCTATTAGCGAACCCTCAAACTGAGCTACTCTTCTTTGCCGCAATGTGAGCTGGACTACACTCCACCTTTTCCTGAGTTCTTTAACTTCTCGGGTAGTAACTTGGCGCTAAGGGTAGATGTGGCTGCCTATCTATCCTGCTATTTTAAGACCTGTATTTCGTTTAGAGTTCAACTGTTAGCTAATATCTCTTGTTAATATTTCATTATTCTTTATATTAAACTTCCTCTCGGACCATAATGTTCTAGATTCCTTCTTTTGATTGAAATCAGGACTGAGTAGTACAATTGCTTGATTTCTTATAGTCAGTTTCATGTTATACAACACATTGTGTCATTTTTGTAAAACTCACTCCTTAGCTCGATAAATATTACGGTCCAACGAATTTCTTAGATTACCCTGCCATTCAAGATCTTTCCTTCAAATAGCATTAGATTATACGTCGTTTTCTACGTTTTTAACCATTCTACTACGGCCGCTTGAGAAAATTTCTCGCGCATAGGTTTTCACGATTGTCGAAACTCGCCTCGAACGCCAATAATTGTTAAGCATCTTTCATGTGCCTGTTGAGGCCATAACTTATGAATATTACTCGTGTAAATACATGAAATGCCTTTCCAAATTTTTGCCCATTAAATAAAACTAGGTCTATTCTTCATTATCAAACTCGTTTATCCACACATAGAACTTTGCATAAATTAGGATTACATGTCTACTTGGTCAGATAAAGCACACTCGGAGAATTGTTCCATAAGTATATTCTTCTCCCTTATGAACTGTCTTCCCTCTTACTTTTTAATAACTTAGCTAAATGTCATTCGAAGAGCATAAGTTTTTTAATTGATACAAAGGGCCAGTTCATTCGGTTACCTATCAATTTTTAATGCAGCACATATAATGATAACAACAATTAAGATTAATCTTACCCCTTCAAATTACCATTCGTTGTTGAGAGCACCATGTGAATAATGTAAGGTTCATTTACTTTTTAAATCACTCATGATTGCTTATCGATAACTATTCTATTGCCCAAACCATATGATCGAAATGTATTTGCCTTCCATAGTCCACTCCTCAAATTACACCTAGAGATAAAGCTTTTCTAAAATAACTTCCTTGTTGCCCTGTTTCAGCCTACTGCGCGAGGAGTGCAATGGTTGAACAATACCCCAAGTTGCGACGAGAACTGGATTGTTATCGCATTTCTTAATTTTCAAGTTTTTAGGAGTAAAATCCATATTCTACACTAAGTAGTGTTTATTTTTACAGCTTTCCAGAAATGAAGATTGTTTGAATCGGAAATATGGCTGTGGATTCAAATCAAGAACGTTATCCATCATAATAAAGATTACATATTTGACTCCAAAACTTGAGACTATATACTACAAGTTTGTGGCGTCCCTCACACACACCAGATTGATAAACATATTCATCTCCCTCAAGATATGTTAGCTCTATTGTAAGCCAGTGAAATTGGCCTCAACTACCTGACTCCTGACTACACCTAAGTCAACTCCGAACGATAGTCTGCGTGTTGAATCAAGTTTCGTGTTCTAAATTTATGTAAAGGATAAACTCACATTGTGATCTTTTTGTAAGCTCTATCTACTTAAGCACAATAATATAGGAGACGATCGCATTCCATATTGTTCGCACTGTAACAATGTATCCTTCTTATGTAATTTAATGCTAGGGAGATGACACTTCTTGGTATTTGTGTATATGAATACTAAAACATAATATTTCTTCTTAGGTACACATCCCTTATCTGTTGCAGTATAATGGGCCCTTTAAAAATTATTTTCACTATTATAAATTAAAGCTGCTATGAGCATTCATGTGTAAGGCCTTTCTGGTGGTACATATCTGGTGTTCACATTTTTTACTGGTAGGAGGTCCCTAGCACCTAAATGGCTAAGTCATCACCAAGCCCAATAAAAGGCTAACGGTGAGTTTAACATGAGCATTTGCGGATTAGAACTCCTCAAACTGTTTCAAGAAAGGGTACTTATACATTTTATATTCCCACGACAGCGAGTGTATCATGAGAGAATTTTTCATGGGCTCCACCATCCTCTCCTTGAGGTAAGTCTTATGAGGAATGATTAAGAACTATGTATATCTAACATCATGAGTAAACAACTCTAAAGAGGCAGTGTAAGTACTAGTATCTCTCATTAGGTGGCATTCATTTGCATTCTCTAATTTGAAACTTAGTTATGGTTAGTCATCACTCTTTCATAGCTACATTTGCCAAAAACCAGACAGTAATATTGTGCTTCTTTCTGTGGATTCTGTCTTGAAATATTCTTTGTCTTATGTCATTAAAGAAAGTGTCTCATATTGGCGATTATTGATAGACGCAAATTAATATGAGCTCAACGACATACCTTTCATTGACTAAGGTGATTCTGCTAAGTAACCTTTTCGCCAATACTAGCTCTTTGTTGTTAATCTCGAATTCCAGCAGTGATCTTTGAAAGACATTCATCAAATCTCCTCATTATTGGCAAAGCTAGCAACATCATTTATTGTTCCCTTGTAAAACAAACTCGATGTCTTTTGTGTTATATTTAGAAAACTTTGCACAATTCAAAGTGTGTATATAGATGTTATATTGCATTAAGATTTATTTTAAGTTAATTTTCCTATGTAGTGTGAGGTATAAGTCAGATGGAAGTTCATTTGGGGCAATATGGAATCTCAGTTTTTCCTAGTATAGATTTGTTTCACTGAGATGTCTATTTCTTTATTAAAAAAATCATTGTAAACCATTTATGTGAGGACTGATTCTTGATTTTAGTAATTTCAAAAGATTAGAAAAACATCATAGCGAGTACAAAATAACATCCAGTTATGACTTACAAATTTGGTAAATCATGTATAGAAAAAATGATAAACGGTACAGCTCACAAAAACTATACAAACATTATGTGTAAGGGTGAAATATATGTTAAATTATCTTAAATTCTGAAAAATCAAGAAAGATTGCTATCTAATCAGTATGGAAAACAAGAAAATAATAAAATTACATGATTATAAGGAAAACAAAACTCATATTCAAAGATGAGGCATGATTAATGTATATAAAGGAACCCACAGTTGATTTACAGATCAATCATTAAAAATTTAATATATTTAGAGCCAAATTATCAAATCGCACAGTTAATTAAAAGATCATTGATTTTCTTATACGGCAGAAAAACAGAATGTGTCATCAAAAAATTATGTTACTGATATTCAATCAACTAGGATCGTCACAAAAATGGTTACCTTCTAAAGTCGCAAATGAAGAACAAATGAAGAGCCTATTAATAAATAAAATGGTAAATATTACCCCATGGCGCAATCAAAAGAAGAAAAATTACTACTAATTCTTGCCAATTGCAAATGCTTCCCACCAAATATGAAAATTTAGAGTACATCCACCTTTCATTCTATAAAGGAGTAAAGGCAATTTCATAAAACTATCACACTAAATCGAAAATTGAATGAAAAATATTTGGTAAATAATTTAAGTGAAGATTTATACTAGTCACAGAAAAAGAATGGTACCATGAATATTGCCGTAGTTGCTTCCTCCTCGAGAATAGAAAAACAAGGTAACACAGTGCCTCGCTTAGGCATCCACACAGAGCCGATGCTATCGGACCAGGGTCTGGAGTCCGAAATGTTAGCAAATCAACTGAGTACACCAAAATACCAAGTTATAAGTAGATGGACAAGGAAATTGTGTACTTGGGGCAAAACAAGACACTAAATGGATTCAATACGAAGTGAGATGAGCAGAAAAAATAACATTCATATATACTTTGGGAACATCTAGCATTTGACAAAGATGGAATAGAAAAAGATAGTAGTAGAACTTGATGACTACCCTACAATTAAACACAGGCGCTGGTAAAACCTGAGTTAAAATGACAAATTATCATACGAGCGCTATCTCCATCCCTCAAATCCTTGTTATCTCCTACAATCTTCCAAAAAAAGAAGCTAAAGATCTATTGTGAAATGTATAAACTGAAACCTTCAATAAGACACACAGTAGACTTCATATAAACTTGAACATGAAAAATATTTCGCAAACCAAATACAAAGACATAAAACACATAAGTTAAAATTTGAGCATTTCCACTTACATTAATACTAACATATAATTAACCAGTAGACCACCAAAAGGTGATCAAAAAGTGGAAAGTAAGACATTTGTAACATATACAAATGTGTTGTGGTGTATGTACTTACATACACATTATATTGTATACTTCCCTTTCTATAATAGCTTAATATAGATTTGTAAAGATTTATACAAATGATTAACAAAAAGATATACACCTTACACATACCAATGTGAAAATAAATTGAACATCAGACTTCTAATAAGAAGGATATATGATAACTATTCGACCAACGAAAAATGTTAACAAATATTTACACCCGGCAAAGTAGAAGTTAACTATATAAAATATAATTTATCATCAGTTTAAAAAAATGAAAATGTCAAGAAAGTAGATAAGTGTTGACTCACCAGCAAGTGAGCAACAAGAATTCTCTGTGGGATATAAATGAGGTACAACACTTTGAAAAAATAACTAAACATCATCACACAAAGTGAAGATGGCATCACACAACCCCTGATCCAAACAATCCACAACTAGGGGCATTCACCACCAGGAAACACACCTTCCAAATGATATCTCACGAAGACGATGCTCAAGAATTATTGTATCTAAGCGAGCTTATCATTGTCAAAACAAGTAAAACCAAAACCGCTGAGAGAGCACAGCATAATCAATCGGGAGAAAATCGATAACTACTATTTTACAGCAATACTACAATAAATCTACACAATATGAAAAATAAATTATAGCATGAACTATAAGAACTAATACAGATGGTATGACTATCGAGAATTATAAAAAGTGGGAAGTGAATACATAGAGTAATGTCAACTTAACAATGTACAACAAGAATCAGCAATCACCGAATATTTAATTATAAATTGAAAATAGTGCGGAAATTGCAAAAACAATTAATTGAATTAGCGAAAACAATAGATAAGTACAAACCCACAAAAGTAAGGAAAGAAAAAGGAAAATAGGAATAAAACACAAAGGTCAAGCTGATAGCCATATCTTTTTGAATGGAAAAAGTAATAAAGCTTTAACTTAAACCTAAATTTTATTTCTTAACTGACAAAAGTGAATATAAGTATACCGCTACATAATCAAGACTTATCATCATTTGATCCACCTACACATAGAATATACACATACTCTGTATGTAAAGTAATATGTAATGTCGTTTTTTAATTCGTGAATCTAATATATAATATATTACACAGAAATAAACAGCTTGAAAATGAAAACAATGAAATATAAATTTTCAAATTTTCAATGGAAAATTTAAAATTAGATAAAATCAATTAAGGCATATAGTAATAATGTAACAATATGAAGATAGAATAACAATACTTTATTTGGTAAACAAAGGCGTTAGAGTTTTGTCAAGCAAGATTTTGTTTAAATACAAAGTTTAACTAATGAGAAAAAATCAGCAAATAAAAAGAAAAATAATGCCCGACAATAGGAGAAAATTGAGGCAGTGTGGATAAAAGTGTAAATTAAAATACGTGAAAATTTGTGAGCCCAATATTAATAACCGCGCCCACAAGTAATGTAAAAATAAAATAACAATAATTTTGAAGGCCTCAGACATATGAAGTAACATAAATCTAGAATTTGCGAAATACAATGACAATTATTAAATACAAATACACAAAAATTTACTAAAAACATAGTGTGTCTTTTCAAAAGTTTAGAAATAATAGTTAAGTACTAAAAATATATGGTAAGACTGAATCAAAGGACATGTTAAATTTATTACCTGAAGAAAAACTGTTAGTAACAAAAAAAGAGGGGAGAGATGAAAAGCTATAAAGCTGGTGGCAAAGCAACCCAGGATAAGAGGATATGAATGAAAAAAGCAAAGTATAAGCCACTTGTCTATTCAGAAGATGGACAATGTGATTAACTCAGCTTCATAAACCCGTGTATCTAGGTTAGAAATAGTCAAAAAATAATACTGTACTATGAAGATTTACAGTGAAAATTGAGTATGTAATGACTTAATATCTCAATAAATGCATTTAAAAAAAATGAATGAAAACAATGCCACACTATCTAATGTTTGAGGAATACAGTAAATGAAAGCTGTTAACTTAATTTTTATAAAAACGTACAGGTTTAAAAATAATGCACGGTATTAAAAGATAATAAGTCAACCAGGGTCAGGGATGGAAAGTGGAGGCACTGTTCCTATAAGGGTAATATAATTGCCATTAAATATTTATTTTAAACGTCTTAACCAAATCATTATAAGAGAAGAAAATAAACAAAATAAACTAGAATAAATAAAAGTTTGGCAGAGCAGAAAACCAATCAATAAAATAAGAAAAGGCAAAGACAGCAGAAATGGAGAAATATTTGCAATCATATATGCTGACTCAATATTACCATCACATCTGACAAGGATTAATATTAAATTTTAAATCGGAACTTACGACTCAAATAATCAAAAATCCAATTAAAAATGAGGTCAAAAGGATATGAACAGACATTTTTCCAAAAATAGACATAACCCACACATTTACAAAGAGTATACGAAAAGGTGCTCAAAGACGTCATTATTTAAGCAAGCGGCGAATCAATCAAAATGCGCACATGTCATTCCTCTCACACTGGGATGTATCTTGCAAAAAGCAAAAGATAATAAACAATTTTGAAAATGTGACAAAACATTCAGCAAATGGGAAACCCTTCCTAATACATTGTTTGCAAGAATGTAAATTGGCACAGCTAATTAATTAAGAACATTACTGGATGCATCCTATAAAATTTTAAAATATTATTATTATAGGTTTCTAGAACACCGTCACTATCTGGGATAATGTGTTATATATATGTTTATGTTTATGTGTGAAAGTGTGTTGTATATATAAGGTCCCAAAAAATCACTTAGTCTTTCGAAGAGAGAATAATCTTGCATAAACCTTGTATGTTTAGATTACAGCAATTACCATTTATAAAAGTCACGGATACGGAATAACCCAAGGTGAATATAGATAGATGAGATGATAAAGAGAGAATGATATATATATAATACACATGCTCTATACTATACCTACACACCCTCCTTAGTAATATGCACAATGTAATATTATTCAGGCCTTAAAAAAGAGAAGTTTTGTGTTTTGCAACAAAATGGATGACCTGGAGATATCATGCTAAGCAAAATAAGCAGACACACGAAAGACACACTAAAAAATATACTACAGATCTCAGTTATATATGGTCAAACTCATAGCAAAAGAAGTCAAAGGCATGATAACCAGAATGGAGGGAGCAGAGAAGTGTTACACAGGATACAATTCTTGCAGGGCTGTGAGATGAGTTAACGTTCCCTGGAAAGCTACATGTCCGGCATGATGACTACGTAGTTAATAAGAATGTGTCTAGGTACTTGAATTTCTAGAAACGTAACTCTAAGCAGGCGCCGTGGCTCATCGCATGTAATCAGCACTTGGAGCCGAGGGCCGGGCGATCCCACCGACGCTGCAGGATGACCAGACCATCCTACGCTACACACCGGTGAACACCCATCTCCTAAATATCACACCAAAAATTAGCCTGGCACTGGGGCTCGGAGGGTAGTCCAGCACGGAACGCTAAGCAAGCGAGCATATACGTCGTCGAACCCTGCGAGGCGAGCTCGCAAGTTGATCCAAGACTCTATCCACCTAGCCTCACCTGAGACAGAGCGAGGACTCCATTCTCGGAAAAAAAATTATACCTTTACGATGTTCTCAACTAGACACACATCCCTGCATCATACAACACACCCAATTCACAAGAAAGGTAACAAATGAGGTGATGGACTATGAAATCTATATAAAAGCTGAGAGATGGGGTAATATTCAACAACCATAAAGTTCTAACGTAAAAAAAGCCTCTATCTATATACAATACACTCTAGAAATAACTAACAATTGTTATTTGCACTAATATGCCTAAAGATACTGAAGAACTTTTATAATGGAGAATATAGAGAATCTAAACGAGCATCTGGAGACTGCAGAGCATCTAGAACAGAGAATAAATATATCATCCCCTTAGAGGGCTCCGGAGAGCCGACAGAAAAAACACGCACCAGGCCTGCACCCGAACACCACTCTGCTTCAGAGACGCGCGGAAGACTTTACTGTCAATGAACGAATGCACATCCTTAACATGCTTTCCTCTACCGCCAACTGAAGATGTTCTGTCACCCTGTTTTTGTAGCGGCAGCAGAGTTGGCAGTCAGACCATTCACAGATGCCTCGCATCGTTGGTGCAAGTTACATACAATAAGCGATTGAAGCCAGAAAAAAGCACTATCGTCATGTTCTCAATCTCTTTCATCGCTCATTAGAGAAGAGACACTACCGACTTCTTCATTTCAGTACACGTCTTAAGGATACACACTGCTCCAGCGACATTCTTCCTGGGCATTCAAGAGTGCGAGTACTCTGAGCCGCCCCTCTGCTCCAGAAAGGTCACATCGTTTGCCCGTGCCTTTTGCAAATCTAATAATTTTATTTTAAGTTTGTGTTTGGACATGAAGTCTGGTAGAGCACTAGGACATGATTCAGCAAGACATTATCACAACATACAAGTGGGCCCTTAATGCCCACTCTAGACCTACCAGGCTACCTCTTCCCCAAACTCTCTCTTGACACCTCATGATGGTGAGCCTACCTTCCATCGTAGTCCTCCCACACTTGGAGAGGCTGGGCATTGGCAAGCAGAGAGTGAAAAGCGCATGGTTGCACTGCACCGGCCTCTTGATGGTAAGGGCAAAAAGTGCGCATTCCCTCCAGCCTTGTGCTTCCACAAGGTTTTGGCTCTCACCTACCCATGTAGATCTAGGTGGCTGAGTGTCCGCCAGACACAGGTTGCAATCATCCTGAGGTCTTCAATCATCTGTGCATTGAAGAGTCCCGCCATGAAAAGATATATTGATTTCCCTGCCCATCTCGAGCCCTGCCTTTTTTTGTTTCACTGGGACCCTACCAAATTGTAGCTGGCCCTGTCTATAAATGTCTATAATCCCCCAAAACAGATATAGATTGGCTAGAGATGGGTAACTTCCAGTCTTATATGGAGTTTGATAGAATACCTGACGATTCCTCCACCAACTAAAGACAGAAGGCTGGTGAAATAGAGTCGCCACAAACAGTAGCCACCATTTGTGGATGGCATGCCTGACAGCGACGTGTTCTAGGCGGTAC";
      int awidth = 256;
      //char * query = "GGGTGGGTCGGTTTTGGGGTGGAGAGAGAGAATATGGGGAAACTTTCCGCACAAATACTACATAATGTATGGTTTGACGCTAGTAGGAAAAATAAAGAGATAGCGAAGTGGTGTACTATGACCTGGAAGATAGTATATTGCTATCAATTTACAGATTAATCTAAGAGTAACTTTTCTGGAAGTATGTAGTTGTGTAAATTCGAAGGAATCTCTGCTATAGTTAATGTATCTTTATGTAGAGTATTCGTAAGTGATCCAAGTAAAATGAGATAAATGTAATAATATTGTCATACTGTTCTATTAAGTTTTGCATATATTAAAACTTTATTCCTCAAATGTCGGGCTATCTAAATAGGAGGATGATGTTGGGCAAGGGGATATTTGATTTGTTATATGGATGTAAAAAAAAGAAGAGGAAGCATGTCAATTTCATAAGCGCGCACGCGACATTTCTATTCTTGGCTAATCCGTACTATAGTTCAAGTAGAAGGAGAATAAAAGTAGTGTAAGCGGAAAGTCTTTTTTAAAAAACTGTACCTAAAGGCTAAAAAAGTGAAACATTTGGTTGGTCTCACCAGAACTTGCTAAGTTTGTTGGCGATGGCTGAAGTTACCGTTATTTTGAAAGATCCCAGAATATCTGTGCTAGGGAAAGGTCCTAAGTAAGTTTAAAGAATCCAGTGTTCAACCAAATCAGTCTCCCCTAAGGGCGTCTAAGCTAATGAGAGATGATCCCTTTAGGAAGCTGAAAGGTTTTGTAATAGAGGAGTTCAAAGAAGGCAAGTCTCACGATGGCAGAGTTTATATAAATATCAAAAATATGTCACTGATGTTTAATGTGTAAGTTATCATAATTGTATGGTTCAACACACCTTGGTAATTATTACTATGTAGAAATTAAGTGCAGCTTTATGAATGTTAACGAAATATGTGCAGGAAAAGTCATAAAACGATTGAGCTGTAGTAGATAATATAAAACAGACTATCTAAACTAAAAGTTTCCTGGATCTTACTTCGCTAAAAGCCTCGAAGACCCTTTTGTCCCTTTTATTTAGTATATCTTTTATTTTAGAGCAGTTCTTCTGGCCCTGTCAAACTACCGTGTATTGTTTTCGAAGTTAATCGGAGTTGATAAGAGGAACTAGAGAAGCAGATGCCGTTCCACAGGTTTGATGGCACATTACATAAGAGTGTTTTTCTGCTGCAGTAGCAGGACATTGATAAGGTAGTGGTGCTGGGCTGAGCGATTCATCTCGTGGTCGCACTACTATCAGCAGACATAAAGTGGCCTTCTCGTCCACTATGCTTCATGTTAGTGAAATAAAGTTAAATGATGAGTAAATACAAGTTGGAGGTCAGTCTATATGAGCTAAGGATATCAGTAAAGTTTTTATGATTTTATTTCATGTCATAGCTTAACAGCACCGATTAACTGATGTATTTTAAAATCAGTAGTTGTGTTCAGTGTAAATCTACTGCCAAATAAACTAAATTAATAGTTCCGTATTCGTCAAACATTAGTTCGGAGATCAGTTAAAAAGTTTTTCCATGATTTATAATGCGTTGTCAAGTGGGCCCCTAAATACTGGCAGGCCAATTATTTTCGATTGGAGTCTATCACGCTTCTTGACTTGTGAACCTCCCTCAAGACAGTCAAGCATCTGCCTTGCCCATTGTAAAGTACTCTCGAAGGTGACAATCCCTGCTTCATATTTCACTGAGAAAGAATCAATGACATGAGGGTGACAGTTTCATCACTGAAAATCCATCAATTTCGCGAATTTTATACTGAAGATCCTACATTTAATTGATATCATTCTGCAGTTTTCCCCAGTGCTACATCATCCATGTTCTCACTTCCATTTGGATTATGTAATACAAATAACTGGATGTCTCCTCATATTAAAAAAACTCAAAAAGAATAACAAAGACCTTGACCTACTTGCTCCCCATCGTCTAGCTCCCTATTCAAAACCGTTGAGACCTC";
      //char *   ref = "AATTCAACTGACAATGTGAAAACCTTCATTAATCCTAAAAACAAAGAAAAAAAGGATTCTTGAAATCTATGGAAAAAAAGTGAACATATGCAAAAGGCTAGCCAATCTGAGAATAATTACTGAAGGATTATTTGAAGTACCATTAAAAACATAATGAAGTACATATCTTGAGTCAGTATTGTATGCATTAAGTAACAAGTATGCTAAATACAAAATGTCAAGCTGTTAATATGAATACTACTGTAATATACACAATTAAGCAAATCTTTAGAAAAACACATTATCAATAACAATGACTTGAAGAGGTACAAAATACATATGAATTAAAATAGAATTTATTATATTACAAATAATAATGATATATTAAATTGAGCTTAGACCTAATAGAAAGAAACAACTTCAAACTTTCCATTTTCACTGTAGTGTCTTTGTTGAATTGCTAAATATTAGGTACAAATGCTCAAAGAGGATGTTTTTATGGCATACAGCAGAAAACTAGGTTAATATTCACATGTAGTCATGGTTTTGAGGTTTTTGACTATTACGCCTTTTAATTAATGATTTAGCAACCTTGTTTATTGAATGCATTTCTTTGGTAATTTTATTCTCAAACCCTATCTTAACTTTTTACTACCAAGATGATGATATGAATTATGAAAGTAATCGGCAATAAATACTTTTATATATAAACTCCGTTTACTAAAAAGAATCAATATTAAAGAGAAGCATTGAAAATATTATGAATCCAAATACCCAATTTTCCTTTTTTTTATGGCAACAACATTGTAGAGTTCCCCTATTTTTGTCCTCATGAATATATTTGAGAGAGTAATCACGTCCAGCATTTAGCAATATCATATTGTGGAGGGGTGTTTGTCGGATAAATCATATAAAATCCCGTGAGAAGAATACTTAAAATAACTACTCAATATCCATAATATGGATTTTCTATGGTAACTTTTTAATCAGAATATTAGTATTGTAAAAATTAGATTTTGCTTCGAAAAAATAATTCATGATTTTTTTAAGAAAACAAATGCAAAATCCAAAAAAGTCTTATAAAAATGCAAGAACCTATAGAGACATGTCATTATACAAATACTTTTTCACTCACACTGCTCACATATTGAAAATATCTATTGAAAATGAAAAGCAAAAATGTGGATCTCAGCTTAACCCTTTCATATAAAATACAACATTCTAATTTACTGAAAATCAATGTTACATTCCATTAGCAGGGTTCAACATAAGACATCCTTCAAGTCTTTCTATAAGTTCTAAAAGACAATGGTATAGAACAAGAAAAATACCAAGATGACACATAAATAATACGTAGCAAAGTGTTTGTGTTTTTCTTACGAAATAGTAGTAATTTTGTTAGCATTTTCTATGCGGCAAGTTTGTACTTCACAAGTCCTGTAGTGGTCACAGCAGTTTTTGCTGTGTTCTTTAATTATAGCTTAACTATTCTCATAGCATATCCTTGTATGATATACTTAATAAATAAAGGATATAGAGAGGCAATGTATCTATATCATGACTCTGATAAATTCTGCCTTGTCACCACAGAAAACCTTGATCACGGTCACTGACAATTTTCAACAAAGCTAGAAAATACAAGAAATATCAAGACTTCATGCTCCACTCTACTGTCTTATTTTGACATAAAACTCAAACATTTTACTTGATGTTATGCTTACGCTACATCAGTTATATGCATAGCCCAACCTTTATTCATGTTTGCCTACAAAAATATGTCTTGGCAAATGTGCACATGCAAATGAATTGAGCCCAACAAATGAGTTCCCAACAAATGTGTTGATTTCTCTCTAAAATATGGCCAGACAAGATTGTGTAATTCTACATGGCCATATTATTAAACTTGTAAAAATTATATGCTGACCTGTCTCTAATAAATTATTCTGTATAATTATTCATAGCTACAGCTTAACAGTTTTCTAAAAAACTCTTACATCGACTATACCT";
      //int awidth = 128;
   //char * query = "TAAAAAAAAAAAAAAAAAAACTGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGA";
   //char * ref   = "AAAAAAAAAAAAAAAAAAAAACTGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGA";
   //int    awidth= 64;
   //   char * query = "AAAATTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
   //   char * ref   = "AAAAATTTTTAAAAAATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAA";
   //   int    awidth= 64;
   //   char * query = "TGACTGACTGACTGACGTAGTCGTCGTACTATCAGTCGTACGTAGTCAGTCACGTCACGACGTACGTCTGAGTCTGACGTACGCGTAGTCATGCTGACGTACGTAGTCATGCGACCGCATCATCGACG";
   //char * ref = "ATCTAGTCGTCATGCTGAGTCTGCATGCGTAGCTGTACGTACCAGCGCAGCGAGAGTAGTAGTATGGCAGACGTACGGCACCACGTACTGCGTACGTAGTCGTCAGTCTGATCTGACGTACGTCGTATGC";
   //char * query = "TAAATCATGCCCCCCGGGGGGTTTTTATATATA";
   //char * ref   = "TAAATATGCCCCCCGGGGGGTTTTTAATATATA";
   //int    awidth= 5;


   //Compute query blocks.
   uint32_t rlen = strlen(ref);
   uint32_t qlen = strlen(query);
   fprintf(stdout, "query: %d nt, ref: %d nt, cells: %d\n", qlen, rlen, qlen*rlen);

   //   dumb_align(query, ref, qlen, rlen, awidth);
   //   uint32_t score = mbf_align(qlen, query, rlen, ref, 1, awidth);

   alignopt_t options = {
      .bp_thr = 10.0,
      .bp_period = 10,
      .bp_repeats = 5,
      .read_error = 0.2,
      .rand_error = 0.5
   };
   path_t cell = dbf_align(qlen, query, rlen, ref, 1, awidth, options);

   fprintf(stdout, "mbf score: %d (row=%d, col=%d)\n", cell.score, cell.row, cell.col);

   return 0;
}
