#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#define WORD_SIZE 64
#define MASK_MSB 0x8000000000000000
#define min(a,b) ((a) < (b) ? (a) : (b))
#define max(a,b) ((a) > (b) ? (a) : (b))

char translate[256] = {[0 ... 255] = 4,
                       ['a'] = 0, ['c'] = 1, ['g'] = 2, ['t'] = 3,
                       ['A'] = 0, ['C'] = 1, ['G'] = 2, ['T'] = 3 };

void
update
(
 uint64_t   Eq,
 uint64_t * Pv,
 uint64_t * Mv,
 uint8_t  * Phin,
 uint8_t  * Mhin
 )
{
   uint64_t Xv, Xh, Ph, Mh;
   // Get current match sequence.
   Eq |= *Mhin;

   // Compute output of Xh blocks (Mh, Ph).
   Xh = (((Eq & *Pv) + *Pv) ^ *Pv) | Eq;
   Ph = *Mv | ~(Xh | *Pv);
   Mh = *Pv & Xh;

   // Save hout.
   uint8_t Phout = (Ph & MASK_MSB) > 0;
   uint8_t Mhout = (Mh & MASK_MSB) > 0;

   // Feed Ph, Mh to Xv blocks.
   Xv = Eq | *Mv;
   Ph = (Ph << 1) | *Phin;
   Mh = (Mh << 1) | *Mhin;
   *Pv = Mh | ~(Xv | Ph);
   *Mv = Ph & Xv;
   *Phin = Phout;
   *Mhin = Mhout;
}

uint64_t **
precompute_eq
(
 int        len,
 uint8_t  * text,
 uint32_t * words
)
{
   uint32_t w = (len + WORD_SIZE-1)/WORD_SIZE;
   uint64_t ** Peq = malloc((w+1)*sizeof(uint64_t*));
   for (int i = 0; i <= w; i++) Peq[i] = calloc(4, sizeof(uint64_t));
   for (int i = 0; i < w; i++)
      for (int b = 0; b < WORD_SIZE && i*WORD_SIZE+b < len; b++)
         Peq[i][translate[text[i*WORD_SIZE+b]]] |= ((uint64_t)1) << b;
   if (words != NULL) *words = w;
   return Peq;
}

void
free_eq
(
 uint64_t ** Eq,
 int         words
)
{
   for (int i = 0; i < words; i++) free(Eq[i]);
   free(Eq);
}



uint32_t
mbf_align
(
 int         qlen,
 uint8_t   * qry,
 int         rlen,
 uint8_t   * ref,
 int         dir_ref,
 int         align_w
 )
{
   // Precompute query eq values.
   uint32_t qwords;
   uint64_t ** Peq = precompute_eq(qlen, qry, &qwords);

   // Reduce width if align_w is bigger than the available query words.
   uint32_t awords = min(qwords, (align_w + WORD_SIZE - 1)/WORD_SIZE);
   if (awords * WORD_SIZE <= rlen) align_w = awords * WORD_SIZE;
   else align_w = rlen;

   // Initialize
   // Right bitfield.
   uint64_t * Mr = calloc(awords, sizeof(uint64_t));
   uint64_t * Pr = malloc(awords * sizeof(uint64_t));
   memset(Pr, 0xFF, awords * sizeof(uint64_t));
   // Bottom bitfield.
   uint64_t * Pb = calloc(awords, sizeof(uint64_t));
   uint64_t * Mb = calloc(awords, sizeof(uint64_t));

   // Square block.
   for (int i = 0; i < align_w; i++) {
      uint32_t c = translate[ref[i]];

      // Update bitfields vertically.
      uint8_t  Phin = 1, Mhin = 0;
      for (int j = 0; j < awords; j++)
         update(Peq[j][c], Pr+j, Mr+j, &Phin, &Mhin);

      // Update Mb, Pb. (Bottom bitfield).
      uint64_t mask = ((uint64_t)1) << (i%WORD_SIZE);
      if      (Phin) Pb[i/WORD_SIZE] |= mask;
      else if (Mhin) Mb[i/WORD_SIZE] |= mask;
   }

   // Compute score at this point.
   uint32_t score = align_w;
   int last_bit = (awords * WORD_SIZE > qlen ? WORD_SIZE - (((qlen-1) % WORD_SIZE) + 1) : 0);
   int j = 0;
   for (; j < awords-1; j++) score += __builtin_popcountl(Pr[j]) - __builtin_popcountl(Mr[j]);
   score += __builtin_popcountl(Pr[j] << last_bit) - __builtin_popcountl(Mr[j] << last_bit);

   // Check whether the matrix is full.
   if (min(rlen,qlen) <= align_w) {
      free_eq(Peq, awords);
      free(Mr); free(Pr); free(Mb); free(Pb);
      return score;
   }

   // ***
   // Compute diagonals
   // ***
   int        diag_max = min(qlen, rlen);
   
   // Precompute Eq for reference.
   uint32_t rwords;
   uint64_t ** Req = precompute_eq(rlen, ref, &rwords);

   // Alloc words for shifted Eq values.
   uint64_t * Eqr = malloc(awords * sizeof(uint64_t));
   uint64_t * Eqb = malloc(awords * sizeof(uint64_t));
   uint8_t    Eqc;

   // Alloc horizontal/vertical input deltas.
   uint8_t Phinr, Mhinr, Phinb, Mhinb;
   uint8_t Pvinr = 0, Mvinr = 1, Pvinb = 0, Mvinb = 1;

   for (int d = 0, i = align_w; i < diag_max; i++, d++) {
      Phinr = Phinb = 1;
      Mhinr = Mhinb = 0;

      int bits = d%WORD_SIZE;
      if (bits) {
         for (int j = 0, s = d/WORD_SIZE; j < awords; j++) {
            Eqr[j] = (Peq[s+j][translate[ref[i]]] >> bits) | (Peq[s+j+1][translate[ref[i]]] << (WORD_SIZE - bits));
            Eqb[j] = (Req[s+j][translate[qry[i]]] >> bits) | (Req[s+j+1][translate[qry[i]]] << (WORD_SIZE - bits));
         }
      }
      else {
         for (int j = 0, s = d/WORD_SIZE; j < awords; j++) {
            Eqr[j] = Peq[s+j][translate[ref[i]]];
            Eqb[j] = Req[s+j][translate[qry[i]]];
         }
      }

      // Update bitfields.
      for (int j = 0; j < awords; j++) {
         update(Eqr[j], Pr+j, Mr+j, &Phinr, &Mhinr);
         update(Eqb[j], Pb+j, Mb+j, &Phinb, &Mhinb);
      }

      // Compute the central cell.
      uint64_t Pvc, Mvc, Phc, Mhc;
      if (ref[i] == qry[i]) {
         Mhc = Phinb;
         Phc = Mhinb;
         Mvc = Phinr;
         Pvc = Mhinr;
      } else {
         Mhc = Phinb & Mhinr;
         Phc = !Phinb & (Mhinb | !Mhinr);
         Mvc = Phinr & Mhinb;
         Pvc = !Phinr & (Mhinr | !Mhinb);;
      }

      score += Phinr - Mhinr + Pvc - Mvc;

      // Now shift the bitfields and insert center cell.
      int j = 0;
      for (; j < awords-1; j++) {
         Pr[j] = (Pr[j] >> 1) | (Pr[j+1] << (WORD_SIZE-1));
         Mr[j] = (Mr[j] >> 1) | (Mr[j+1] << (WORD_SIZE-1));
         Pb[j] = (Pb[j] >> 1) | (Pb[j+1] << (WORD_SIZE-1));
         Mb[j] = (Mb[j] >> 1) | (Mb[j+1] << (WORD_SIZE-1));
      }
      Pr[j] = (Pr[j] >> 1) | (Pvc << (WORD_SIZE-1));
      Mr[j] = (Mr[j] >> 1) | (Mvc << (WORD_SIZE-1));
      Pb[j] = (Pb[j] >> 1) | (Phc << (WORD_SIZE-1));
      Mb[j] = (Mb[j] >> 1) | (Mhc << (WORD_SIZE-1));
   }
   // Free shifted Eq values.   
   free(Eqr);
   free(Eqb);

   // Check whether the matrix is full.
   if (rlen == qlen) {
      free_eq(Peq, awords);
      free_eq(Req, awords);
      free(Mr); free(Pr); free(Mb); free(Pb);
      return score;
   }

   // If the matrix is not square, compute the last block.
   uint64_t  * Pv = (qlen > rlen ? Pb : Pr);
   uint64_t  * Mv = (qlen > rlen ? Mb : Mr);
   uint8_t   * nt = (qlen > rlen ? qry : ref);
   uint64_t ** Eq;
   if (qlen > rlen) {
      Eq = precompute_eq(awords*WORD_SIZE, ref + rlen - awords*WORD_SIZE, NULL);
   } else {
      Eq = precompute_eq(awords*WORD_SIZE, qry + qlen - awords*WORD_SIZE, NULL);
   }

   // Iterate over the remaining rows/columns.
   for (int i = min(qlen, rlen); i < max(qlen, rlen); i++) {
      uint32_t c = translate[nt[i]];

      // Update bitfields.
      uint8_t  Phin = 1, Mhin = 0;
      for (int j = 0; j < awords; j++)
         update(Eq[j][c], Pv+j, Mv+j, &Phin, &Mhin);
      score += Phin - Mhin;
      
   }

   free_eq(Peq, awords);
   free_eq(Req, awords);
   free_eq(Eq, awords);
   free(Mr); free(Pr); free(Mb); free(Pb);
   return score;
}

void
dumb_align
(
 char * q,
 char * r,
 int qlen,
 int rlen,
 int d_print
)
{
   int * m = malloc((qlen+1)*(rlen+1)*sizeof(int));
   int cols = rlen + 1;
   int rows = qlen + 1;
   m[0] = 0;
   for(int i = 1; i < cols; i++) m[i] = i;
   for(int i = 1; i < rows; i++) m[cols*i] = i;

   // Compute matrix
   for (int i = 1; i < cols; i++) {
      for (int j = 1; j < rows; j++) {
         int match = m[(i-1)+(j-1)*cols] + (r[i-1] != q[j-1]);
         int gap   = (m[(i-1)+j*cols] < m[i+(j-1)*cols] ? m[(i-1)+j*cols] : m[i+(j-1)*cols]) + 1;
         m[i+j*cols] = (match < gap ? match : gap);
      }
   }

   // Compute intermediate values.
   int words = (rlen + WORD_SIZE - 1)/WORD_SIZE;
   uint64_t * Pb = calloc(words, sizeof(uint64_t));
   uint64_t * Mb = calloc(words, sizeof(uint64_t));
   for (int j = 0; j < (rows + WORD_SIZE -1)/WORD_SIZE; j++) {
      for (int i = 0; i < cols-1; i++) {
         int dval = m[j*WORD_SIZE*cols+i+1] - m[j*WORD_SIZE*cols+i];
         if (dval > 0) Pb[i/WORD_SIZE] |= ((uint64_t)1) << (i%WORD_SIZE);
         if (dval < 0) Mb[i/WORD_SIZE] |= ((uint64_t)1) << (i%WORD_SIZE);
      }
      //fprintf(stdout, "Pb[%d] =", j);
      for (int i = 0; i < words; i++) { //fprintf(stdout, " %016lX", Pb[i]);
         Pb[i] = 0; }
      //fprintf(stdout, "\nMb[%d] =", j);
      for (int i = 0; i < words; i++) { //fprintf(stdout, " %016lX", Mb[i]);
         Mb[i] = 0; }
      //fprintf(stdout, "\n");
   }

   uint64_t Mr = 0, Pr = 0;
   for (int i = 0; i < rows - 1; i++) {
      if (i > 0 && i%64 == 0) {
         //fprintf(stdout, "Pr Mr: %016lX %016lX\n", Pr, Mr);
         Pr = Mr = 0;
      }
      int dval = m[(i+1)*cols + cols - 1] - m[i*cols + cols - 1];
      if (dval < 0) Mr |= ((uint64_t)1) << (i%WORD_SIZE);
      if (dval > 0) Pr |= ((uint64_t)1) << (i%WORD_SIZE);
   }
   // Print diagonals
   /*
   for (int i = 0; i < min(qlen,rlen) - d_print; i++) {
      fprintf(stdout, "%d\t%d\n", m[i*cols+i+d_print], m[(i+d_print)*cols+i]);
   }
   */
   /*
   for (int i = 1; i < min(qlen,rlen); i++) {
      //      fprintf(stdout, "%d\t(%d,%d,%d)\t%c-%c\n", i-1, m[i*cols+i-1], m[i*cols+i], m[(i-1)*cols+i],q[i-1],r[i-1]);
   }
   */
   fprintf(stdout, "align score: %d\n", m[(qlen+1)*(rlen+1)-1]);
   
}


int main(int argc, char *argv[])
{
   char * query = "GGGTGGGTCGGTTTTGGGGTGGAGAGAGAGAATATGGGGAAACTTTCCGCACAAATACTACATAATGTATGGTTTGACGCTAGTAGGAAAAATAAAGAGATAGCGAAGTGGTGTACTATGACCTGGAAGATAGTATATTGCTATCAATTTACAGATTAATCTAAGAGTAACTTTTCTGGAAGTATGTAGTTGTGTAAATTCGAAGGAATCTCTGCTATAGTTAATGTATCTTTATGTAGAGTATTCGTAAGTGATCCAAGTAAAATGAGATAAATGTAATAATATTGTCATACTGTTCTATTAAGTTTTGCATATATTAAAACTTTATTCCTCAAATGTCGGGCTATCTAAATAGGAGGATGATGTTGGGCAAGGGGATATTTGATTTGTTATATGGATGTAAAAAAAAGAAGAGGAAGCATGTCAATTTCATAAGCGCGCACGCGACATTTCTATTCTTGGCTAATCCGTACTATAGTTCAAGTAGAAGGAGAATAAAAGTAGTGTAAGCGGAAAGTCTTTTTTAAAAAACTGTACCTAAAGGCTAAAAAAGTGAAACATTTGGTTGGTCTCACCAGAACTTGCTAAGTTTGTTGGCGATGGCTGAAGTTACCGTTATTTTGAAAGATCCCAGAATATCTGTGCTAGGGAAAGGTCCTAAGTAAGTTTAAAGAATCCAGTGTTCAACCAAATCAGTCTCCCCTAAGGGCGTCTAAGCTAATGAGAGATGATCCCTTTAGGAAGCTGAAAGGTTTTGTAATAGAGGAGTTCAAAGAAGGCAAGTCTCACGATGGCAGAGTTTATATAAATATCAAAAATATGTCACTGATGTTTAATGTGTAAGTTATCATAATTGTATGGTTCAACACACCTTGGTAATTATTACTATGTAGAAATTAAGTGCAGCTTTATGAATGTTAACGAAATATGTGCAGGAAAAGTCATAAAACGATTGAGCTGTAGTAGATAATATAAAACAGACTATCTAAACTAAAAGTTTCCTGGATCTTACTTCGCTAAAAGCCTCGAAGACCCTTTTGTCCCTTTTATTTAGTATATCTTTTATTTTAGAGCAGTTCTTCTGGCCCTGTCAAACTACCGTGTATTGTTTTCGAAGTTAATCGGAGTTGATAAGAGGAACTAGAGAAGCAGATGCCGTTCCACAGGTTTGATGGCACATTACATAAGAGTGTTTTTCTGCTGCAGTAGCAGGACATTGATAAGGTAGTGGTGCTGGGCTGAGCGATTCATCTCGTGGTCGCACTACTATCAGCAGACATAAAGTGGCCTTCTCGTCCACTATGCTTCATGTTAGTGAAATAAAGTTAAATGATGAGTAAATACAAGTTGGAGGTCAGTCTATATGAGCTAAGGATATCAGTAAAGTTTTTATGATTTTATTTCATGTCATAGCTTAACAGCACCGATTAACTGATGTATTTTAAAATCAGTAGTTGTGTTCAGTGTAAATCTACTGCCAAATAAACTAAATTAATAGTTCCGTATTCGTCAAACATTAGTTCGGAGATCAGTTAAAAAGTTTTTCCATGATTTATAATGCGTTGTCAAGTGGGCCCCTAAATACTGGCAGGCCAATTATTTTCGATTGGAGTCTATCACGCTTCTTGACTTGTGAACCTCCCTCAAGACAGTCAAGCATCTGCCTTGCCCATTGTAAAGTACTCTCGAAGGTGACAATCCCTGCTTCATATTTCACTGAGAAAGAATCAATGACATGAGGGTGACAGTTTCATCACTGAAAATCCATCAATTTCGCGAATTTTATACTGAAGATCCTACATTTAATTGATATCATTCTGCAGTTTTCCCCAGTGCTACATCATCCATGTTCTCACTTCCATTTGGATTATGTAATACAAATAACTGGATGTCTCCTCATATTAAAAAAACTCAAAAAGAATAACAAAGACCTTGACCTACTTGCTCCCCATCGTCTAGCTCCCTATTCAAAACCGTTGAGACCTCCAAGTCGTTCTATCTAAGCTCCACTTTCTGCTCTATCTGGCCTTCTACTAATTGATAACTTTTGTCAAGAGCAGCCTGCTGACTCCCATCTGTTACTTAAATCCACGTCAGTTCTCAGTCTTCAAGTCTCCGCCTAACACATTGTAATTGTACTTAAATTACTCAGCTCCCATCTGGAATAACTTCCTTGCACTTGGGATTCCAGGGAGCCCTCTTTCATGGGTTTTCCTCCTCTACTGGCTGTCCCGTTCCTTGAGTTACCTCTGGCTGGTTCTCACCCATTCTCGTCAGAACTCATAAAGTTAGAGTGCCTCAGGGCCTCTTTTATTCTCTTCTGTCCACATTCACGTCTCTTGTGACTTTAGGGCTCAGGGTTACAGCTTTAAAATACCTGTCATATGCTGATGACTGCCAAACGCTAATGATGCTAACTGTTATCTTCACTCAAACCAGTCCCCTGAACTGCAGACTATAATAACCAGAATTTGCTATTGCACACCTCTATTCAGAAATTTAAGTTCATCTCATAATTTAAACACACATACAGAACTGTACTCGTAAATTCTAGGCACTTCTCACTTAAACTAGTTCTAAAGCCCACAACCTTCTCATCTCATTTAATGGCAGATCCATCTTATAGGGGTCAGCGCCCGCAAACCTCAGAAAATCATCTTTGACTCTCTTCCAACCGACTTCACAAAATACAAATCTTGTTTGCAAATTCCATTATTCTAAAAATTTAAATATATCCAGATATACTACGTACTATTATTCTTTCAGCCTGCTGCCACCAGTGGGCTGGCCTGAACCGAACCATCACCTTGCTTGGGTTTTATCTAAAGATTCCTGTTTACGCCTGATTCCACTCTCTATAACTGCTAATACCAGTCAGAATGATCCTCTTAAGCTGCATTCTGGACATTCTATGCTACTTCTGGACGATCTGACTATTCCTATTAGTCCCCACCCCTGCTTAGTTTCGCTATCAACCCACTGCTGGCTTCCTTGGTTCCTTGAACAGGTTAACATGTTTGTGAACACATATTACAATTCTATCTGTCCTGATTCTAATATAATAAGCTATCATAAGATAGTGGTGATTAAAAAGACTAAAAAACAAACAACCTCATCTTGTTTTTTACCCTTGCATAATGCTGAGATGCAGAATTGCAAACGAAGTGTGCAATACAATCACATTTTATAGGGTTTTTCTTCCACCATGATGCAGCGGACTATGCGAGCACTACTGAAACATCTTACTGAGCAAATCCTTATCCACAACCAATTCACATTTGTATGCTTCTCACACTAAAGGAACAATAAAAATTTATATTTAGAAAAAAAGTGTTGGTGCATAAAGTCATGATAATATTTCAATCAACAGTAGTGAGCTTTGGTTATTGAATGAAAATGTAAACTGTTGGAACTGAAAACAAATATAATCTTTTCCCAGACCATGATAACACCAGTAGAGATCAAAAGAAATTAGTGTTTCTGAATTCACGAGATATATCATACAGCTATTTGAAAAAGTAGAATCTAGGGCTGGCTCTGGTGGCTCACTCCTATAACCCAGCACTATTTGAACAGGCGAGCGGGCAGGATCACGAGTTCAGGAGATCGAGACATCCTGGCTAACAATGGTGAAACCTCTCTACTAAAAAACAAAAAATGTAGCCGGACTTGGTGGGGCATGTCACTGAAACTGCCGCTCTACGGGAGCGAAGGCAGCAGAATGCTTGAAACGTCCGGAGGGCGAGCTTGCAGTGAGCCGAGATGCCCACAACTTGTACCCATGCCTGGGCGACCAGTGAGACTCTGTCTCAGAAAAAAAAAAAGAAAAAAGTATTCGAAAATGTAAAAGTACCAATAGGTGCTCATACTTTACACCAGGCAGAGGACATCAAAATAAGAGGTAACTGTAGAGCTTAGGAAACCACTGTATGTGTAATTCCAATGAACAATGTCTCCAGAAGTCAACAGAGTCAGAAGTAATGTAATGAAATGTTGCAATATCTGAAATTGGCCCTGAAATTGTTAATTACATTTTTCTCTTTATCAGTTTTTTTGAAACAATGTCTTTGTCTCTGTTAAATACTTGGTAACTAGAATCAACAATACTTTATTTGGAGGGAAATGGTATAACAGGAGTTGATGCATTAGGCGCTTAAACAGCGCATTAAATACCTTGGTTTACAATTTCAAATAAATTTCAACCATTTAAACACTGTAAATATTGATGAATAGAAAAATATACCAAGATTCTGGTCAACTAAGTAGTGTGTGCTAAGTACTCTCCTATAAAAATAACCCTATATTAGTCAGCAGTATAAAAAAAACCCCGTAATACTCCCCACACACCCGTCTCACCATTATGATTCCTTACACATGCGTTTTCAGTGGTTTACATGGGTAAATGCTTTCCACATAAGTGGCCAGACAGTAAGTTTTACTCCTTTATGTATTCTCATGTGCCTTCTCAAACTGCTGGCATCTAGAAAAGCACTTTCCCACATGTGTTAATCACATTGGCTGGCCTAATCGGAAATACCTCTGATCGCAGCTCTTCCCCGAGTTCTCCGCTCATAAGAGACTCTTGACGCGCTGGCTATCATTAGACATAGGTGTTCTTTCAGAGCAACAGTTGTGCTGTGGATTTTCACGTTTCCGTTTCACTGTAAAGCTGTGCACAAATATCTTGAGTGCTGGAAAAGATTTTCCACAACTGAATGTCAACCTCGACGTCTGATTATCATACTTATTTGTGCAACCTTGTTCTACTACAGGTGTGGGCAGTTTATTTGCATCAGAATAATTCAACAGATTGCATTACTCTAAGAATGTCACTGGGTATATTCACTGCGTTTTAATTCTGTCCCCACTGTTTCGTGGGTAGTTGAAAGCCTCTTCTCTTTTCGTTGACGAGACTTTTTCGGTCTAACTGCGCCTTGTTTATGCGATTTGCCTGAATCAAATCTGTAGATACTGCTGATTCTCTCGATTATTAATAATTCTGGCCAGAGTAAGAAGCAGCAAAGTCCTGGTTGAATGTCAATCAATGTTTCCAGTAATACTAGATATCCTCTGTAGAAAAAGATTACGCAATAAAATCAAAATCTCCAATCTTTATTTTCATTTAGTGACCACCTCTTCCACTTTTGAGCATAAGTCCAGCCTGATGAATTTCTTTAACATGTCCAACTGCAAGGAAACAAGGCTACATGACAAAATCGATGCAAAGAAAAACTTCGAAAACAGGAGCTGCATATATATCTGTAAATGTATTCTAAGACCTAATGAAGCAGAATGCTGAAAAAGCACATATACTAGAGAAAATAAGATTTAAAGATATTCATCAGTATGGTTAGCGTAAAAAATCTCCAATTTTACAGAACTTGGTCAGAGATTAAAGATAATGGCTATCACAGCTGACAGTGAACCACTGCAGAAAAATTAAATGTTATAATTGTTCTGGCTTTTTTTTAAAACCCTAGAACACAAAAAATAGACTGATGGTAACTCACAGACTCCTCCATTCATCGCTGAGGCTCTCAGATAGCAACCAACTTTCTGGATTGGCAAGAGGGAAAGTCTATATGACCACTTGTTTGCCAGTATCTATTTTCTCCTGCTACCCTTAGGGACTCTTACATTATCGTTTGCCCAACTTTCTGCCTGTGCATGTCGGAATGCACCCGGAATCTTTTAAATGTAGATCAAAATTCAGTAGGTCTGTGATGGGGCCAGTCTGAGATCTGCATTATTTCTGTCTTAGATGGGTATTCTTCTGTTGCGCCTAAGCAGGAGTGCACTGGTATATATGATAGACTCACCGCAAGAACTTCAATCCTGGCTCGGCTGCTCAGCTTCCGCAAGTAACGTTGGGACACAAGGCCATTTGCTACATGACCTGGCTATTTTTTTTATAGATGCAGGTCTGCTATGCTGCCCGGCTGGTCTCGACTCGCTGGCTCAAGTGATCCTTCCCACCTTGGGCTCCAAGTGCTAAGGATTACAAGCTGATTGCACCCAGCACAGCCTGCATTTCTAATAACAGCTTCCTGGTGATGCCAATGTTGCTACGAGGAATCCACCGTAGAGGAACACCAGTTTAGAATGTAAACTCTCTCTAGCAACCCTACCACCTTTTTGTGAACTACCAAATAAGCTGGAGTGTTCGTGAGTGAGAGCTTACAAAGAAAGACTTAAGCTCACTTCGTCCCTCACATATCTAGTCAAATGTTTACTAAGTCATCTACGATGTGAGGTACTAAAATATTAATAAGTAAATAGTCCTGCCGTTCAAGAAGTTCACAATGTGGTGAACGTGTTTGATAATCTAGCACGGCTCTGGCATTACTCTGCTGACTTAATTAGGGGTAATTCAGCATCTTGGGGTTCAAGCTTTCTTAAGAATGTAAATAGAGTTGAGTTGGTTAACACTAAAAACAGTGACTGTTATAAGTATGCTGAGGATGTAAACGCGTATATCAGTAATTAACCGCCGTCTCACACACACCATCAACACACACCCCTTACCCTCAAATAATCTTCCTACTTGATTTTTCCCTAAATATGGTTTATCTTTGGGAAAGATGATCTCTTTCCCTCTCTGTTGTAAAGTATAAGCCAGAAAAAGGTTTAATCATAACGACAATGTAAATAAAGTGCTGTGATATCTATTTTATAAAGGACTAAAATTGAATTAAAATAAAAATAGCTTAGTTGCATGAACCCTCTAAAGATCTCTATATAGTATGCTAAGTATCTACAAATCTCTACCCACATGTTCTCATCATCTTCTAATTAAACTGCTTTGCCTCAAGTGCACCTGGATGTTTCCCCTTATTAAATAATGTTTAGCATCACAACACTTCTAAAAATATGTCTTTTGGTCCTGGGCCACTAAAAAGATCTTTGGTCTCTAAATTGTGTTTAAGTGCTCGCAATAAAATAAACCGCCAAACAGATAACAAAGGTCAGGTAGCCTTTAAGACGCAATATAAGTTAGCAGGAAGTCATACCACATTAATTGTTCAAGCAGGTCAGGTGCCTATCCCTTAAGACGCCTAAGGTCGGCGCATCACCTGAGGTCAGGAGTTCAAGAACCCAGCTGCCAACATGTAAAACGCCGTGATCTACAAAATAACAAAAATTAGCTGGGCATTGATGGCGTTGCCTGTAATTCCAACGCTACTCGGTGAGGCTGAGCAGGAGAATCCCTTGAACGCTGGGAGGTGGAGTTTGCAGTGAGCCCAGACTCAACAGCCATTGCATCCCACCTGGGGACAGAGTGAGACTCCATCTCAAAAAAAAAAAAAAAAAAAAAAATAATTTGTTCATTCATGAAATGGTAATTCATACAAACTATTTCCAATAAGATGGCTATAATTCAGTCACATGTAAGCAGCACTAATGCAATACTTCATAACAGATATTGTCTTTTGTTTACAAAGTATTAGATAACATCCTCTGAACAGTCACTGAAGGTCATTAATTACATATTGCCAAAGGTACATGTCCTAAATGCTTATAAGATTACCTCAGGACATGCCTATGAAAATCTATTATTAATCCTCATTTTAAACAACACAATGAAAAATCTAGTAGTCCAAAGAAATAAATAACCTGTCCAAAGCACAGAATGTTAGAAACCAGATTTGAGCCAAGGTAATCATGGCCCCTTGATGCAAACTTAATATATCCTACCTGTTTCTTTAATCACGTAAGTTGTAACAATTTCTATTGGTATAACATCCTCTTTACATGTTCTAGCTGAACTCGAGAATTAGCTCACCATCAAGTCTCACAGGAGAAGAATATGTACTGCTAAAAGCAGACTGAACAAAACACCTGGCCATTCTTCAAAGCATTGGTTTCTTTGAATAATCTCAAAGAAAATGTGCCTACCGGTGATTCAAATGAAGATTGTTTTGTTTTTGCATAGTAATTGAGATGAAAGGGAAACCATTATAATTGCAGGCCAGCCAAAAATTCACCACCTGCTCTTCGCTTAATCAACTATACAAGAACTCACATTTGAAGATTTCATTATAGCCAAAATTTAAAATAATTCCAAATAGCATGAAAGTTTACTTTTCTGTCACCTCCCTGCCGCTCACACTGGATACTTCTTACACAAGAAGGTCCTCGTCAAAAAGATTAATGAGCACCCTGATCTAGATTTTTAAATAGATATATTTCCAAGATAATTACAATATAAAGTGAGGAAAGATTATTGCTAATTATACATGAACATCTCTAACAAGTAGATCTGAAAAGAATAATAATATATAATTCAAAAGGTAAACAGGGGTTATCAGGGCAGCATATTTCAGAAAGTGTGTTTCTGTTTTTGTTTTTTCTATTTTTTCTCCGATAAATGTGAATTAAAGGGGTGAGGCAGAGGTAAAGTAAAAAAATAAAGAATTAACGTTCAGTTGAAGTGATAAGGATTCAATTAAAACTTATTTAGCCTCAAGGTAGTTATTAAACCATCTCATTTGAACAGATGGGGAAACTGAGGCCCAAGAGAGATTTGCATCGCATGCTCAAGAGAGACATAGCGACTGACAAAAGATCTAATTCCAAAGCCTATAATCTCCTGTGTCAGAAAGAGTTAATGAACATATATTCATGTTCACTTTCATATAGAGAGCACAGATATAAGCAGGGGTAATTAATCAGTTTTCTCTTGCTTTTATTCCCCGCCAACCTTTTTACCCTACAATCTGTAAATGTAATTGATATTAATCTGCAATTTATATTGGTTTCTTATAGCAAGGGGAGACACCAGTGCCTACATTATCAGATTCTCAGAAGCGCCAACTTCTTGTTAATGCAGGACATCAAAGTAACAATGTTAAGAGAATTCATTTAGCATCTCTCTGACCTTTATACTTCAGTATTTAAGTACTGGTAGGTTAATAGAGAATAACGATGAGCAGAATGAGGGAGACAGAAATCCAGAGGAATTCAAGGACAAAAAGCAATTGGGAAACTGGAAGTAACTAGAATTATTTGTTTGCAAGCCCTGGACCAGCATGGTGAAAGCCCTGTCTCACCAAAAAAATAGCAAACATTAGCCAGGTGTGGTAGTGCACACCTGTTAGTTCCAGTTACGGAGGAGGCTGAAGGTGGAGAATCTGCTTGAACCCGAGGCAGAGTGCAGTGAGCCGAGAATTGCCGCCGACTGCACTCGGCAGCCTGGGTGACCGGGAGCCCGTCTGCAAAAATAAAATAAAATAAACTTCATTGTGTTAATGTTCAAGTTTACATAAGTGAAATCACGCCCTGTAGGCTTTGTTTCAAGTAAATAAACCGTGTCAGAAATCTTACGTTTATTATCTGTGCTATATGAAAAATATGCTGCTCATCCCTAAAAATCAGTGAACCTGATTTCTTTATAAAAAAAATCATTTGTGCATAATAGGTGAAAATTTAGTCAGAGAATGAATGGAAAAAAAGCAAATCTACTTTTTGCTGTGAAGACCTGACTAGCTTTTAAAACTGAAATAAAATTGTACTTTACCTGTCATAGATTAAAAGTTCCTGTGTATATAAACTCCCAACAGTTTCTGAAAATCCATCAGCGTCATCCTGACTCTTTGAACAAGAAAGACATTGTCTCAGAAAGTGCTTCGTCAGATCCCAAAAACTCACTAAAGGAAGCAGCACATTCTACTGAGCTTTAAAACACTGGAATTCCACGCAATCACATATGGTAACCATGTCACAGGAAACCTTGCTTCCCGCTGTTGTTCAGTGCTTCTCTAAAATGTGCTCACAGTGGTTGCGAAACTGCATTTTGAATCAGAATGGAATACCTCTTGATCATAAAAAACAAAAAGAAACAGTAATCTAGAATCTCTGAAGTCTCATCACCGTCAGTAGCGGAAGGACAGAGTACTAACTTAATAAATTTTTAGCCTCCCTTAAAATTCCTTAAGTCAAGATTTCCGATATTATGTTAAAGAATGAAGGGATCGATGCGCTTTCCTATGCTTTGTTACCTTCCGATCAAACTCACAATCTGTTTGACATCCACAATAAAGACGGTGAACTGGCAACACACTCTCTAAACACCTCTAAAAAGCAGCAGCAAACCTGACGCTTTCAGCATCTGTTGAACCTCAGAATTTTCAAGCTCACAGTAGACATACTTAGTACAGATTTTTAACCACTAAGACATGATCCTTGGACAGATAGGGCAGAACAGTACGAGTTTTAAAAACTGGCGTACCGGAAGATCACCAAAAACCTGTATTCGGCCCAGTGCAGTTTCTACTCCAAAACGAGAGGCGGCTGCCAGAAAGCGGGAATTCGCCCGCGCCATGGCTGCGTCAAAGGTCTATCACTCGCGCTCTAAGCAGGCCACACCTTCTCTTCCCACTCTCTACGCCGAGGCGGCATCCGGAGTGACAACCAAAGCCATCCCTCCTCGCTTCTGCCGCCCTGCCTCGTGCCCAAGCTCCCACTCCGGCGAATTCCACAACTGCAGAGGTGTGCCCAGGCCACCGACCGGCTGCCTAGCCGCAAAGCCTGCCACCTGCAGCCCCGACCCGTGCTGGAACTGACACAAGGAGCGCTGCCCTCCTTGATGGCCCAAAGGCTCTAGAGAGACCGGGGATGGCGGGCTGGGTGAAGTCAGGAACTACACCGATAGCAGAACTCCAAGGGGGGAACACAGTCTTCACTCTTCTCCCCATGCATCTGGAGACGCAGCCGAGGCCACGCTCTCCGCCCTCCCTATCGCTATCCACGGTGGCGTCACGTCCGCTCTGTCTTCCCGGGCAGTGTCGGGAGGGTTCTGGGCCATGGGGTCGCGGTCGCCGGCCAGGGCGGCTACCAGAGCTACCACAGAGATGGCGCACTCCCCAGCCATGCCAGTGGGTCCCCCGAAGCAGCAGGCGTCATGGATGACGAGAGTGAGGCTCGCTTAGCTGCGCAGCGCTCCGCCTGTCCTTCCCTCCATCGCGAGCATTTCTGTGCCGGCCATGTCAGCGTCTGTCGCTCTGTCGGCTCTGCGCCGAGGCCCGGCAGCACAGCACCGCGGAAGGCCTCAATCTCCTAAGCCAGCTGCGCACTGCGCTGCGGGGGCATTGTAGTTGCTTTGTCCTCTCGCCCATCATCCCTCCTTCGCGTCGGGGCCCCACCGGGAAACTGCTGCATGTTAACGGATCTCTGCAAATGGGGATTTTTTAGCTGAAATCTTGCAGCCCCTTTCCGCTAACGTACCTGAAAACTCTTGGCACCTGCGGCCCTGGTTTTTTGTGCCCCAGCTCAACTGTACCTCAGCTCCAAGAATGCCCTAACCTGGTGAACAGAATCGGGATGCACGAAAGCGGAGCAGACTGGGCACAGTCGGGCATCGCAACATTAGAGAAGGTGGCTTATACCGGAAAAAGGTTTTCGCTGCGTCTGGACAATAGATTTTAATGAACATTATTTACCAGCCACTCAGACAAAAACCAAGTGATATAATACACAAAATGCTCAAGTGAGGCGACAGGACTAACACTTTTACACTTGATCTTTCCTTCTAGCTGTACATATTTTTCAGTGTAGCTGATGAGTCAAATTCATTTTTTAAAACCCGGACAACATTATCCACGTGGCAAGGCTTCAAAAAAAACATTTGTGAACGAATAAAGTACAAAAAACTTAACAGATTTTTTTATTTCAGCTCTCATTGCTATCATGTCTTTGAACGGACGGCATACATAAAGCTAGCTTCCCTCAGAAAAAAAACAAAACAACACCAAAAGAAAAAAAGCGTGAAATCTCACGTTTCTCCAAGCGAAGCGAAAAAAAAAAAAAAAAAAAAAAGGGATTTAGTGTTTTCGCCACGGTTCGAACGCGGGGAGCCTTTTCGAGTGTTAGGCAACGTGATAAACTAACCTACGGAAACTCCATTGGAAAAGGGTTTTTGTAAAGTCCTTGATAGAAGTGCAATTCGCAATTCCAAGTGATATTACAAATTGAGAGAATGAATATAAGTATTAAAGAAAAAACAGAAAAGGAAAAAATAGCTATGCCCAATTTTGAACAGAGTCTAAAACCCATTTCAAAAGCTTGAATTGCACGCCTTTCTCAAAGTGCCTCGGTACCCGCAGTAAAACCATGCACTCGCGAGTTGCCCTTCCTTTGGGTGGCCTTTTTTTTTTGTCTCACCTGAAAGCGTTTTATTACACATCCTTTCCGCAGGTGAGCTGCTAGAGTCCGGGAAAGAAGCAGGGGCTTTCGTTATTCAGCCGCGAAAAAGCATCCTTTCAGCTTCTGGTGGAAGAACGTGTAGAAATTACTTTTGAATTTCCTACTATTTTGCTTCCGAAGACCAAGCAGAAGTTCTAGAATTGACTGTTGTTTTCAAATTCTCTACAGATGTATCAGCAATCAGACACCAAATGCTTATGACATGGCAAATGTAACTTTCAAATTTTCCACAACGTGAATTTCATGATGACCTGAATAAACTTCACTTTCTGGCAAAAAGACAGGCACGTCCTTACAGCCTAAAAATCAAGAGTACGAATTAGGCTGCCGATACACCAAAAGGATAGAATCGAAATATATATATTATATTTATATAGATAAATATAAATTTTTATACTATTATATATAAACATAAGATTTGTATATACTTTATTATATAACAACATAAATTTGTATATATTATATATATAACGGCACAAATTTATACTATATTTTATATATAAACATAATTTGTATATATTATTTATAAATAGAACATAATTTTTTATATTTATGATATATAAACAAATTTTATATTATTATACTAATAAACATCTTAATTTTTAATATATTTATATATAAACATTAATTTATATATTTATTATATAAATAAATATAATTTTTATATATTCCTGATATATAAATATACAGTTTTATATATTATGATATATAAATATAATTTTATATATTTATGATATATAAATATAAATTTATATATTTATGATATATAAATACAATTTTATATATTTATGAATATAAATATAAATTTTTATATATAGAATATAAATATAAATTATATATAAATCTTAATATAGGTATAAATTTTTATAATACTTTATGATAAAAATAAATTTTATTTATCATATCTAAATATAAATTTTATTTAGTGATACTAAATATGAAATTTTTATTTATGACGATACTAAATATAAAATTGGTTTATTTATCAGATATCTAAATATATA"; 
   char *   ref = "AATTCAACTGACAATGTGAAAACCTTCATTAATCCTAAAAACAAAGAAAAAAAGGATTCTTGAAATCTATGGAAAAAAAGTGAACATATGCAAAAGGCTAGCCAATCTGAGAATAATTACTGAAGGATTATTTGAAGTACCATTAAAAACATAATGAAGTACATATCTTGAGTCAGTATTGTATGCATTAAGTAACAAGTATGCTAAATACAAAATGTCAAGCTGTTAATATGAATACTACTGTAATATACACAATTAAGCAAATCTTTAGAAAAACACATTATCAATAACAATGACTTGAAGAGGTACAAAATACATATGAATTAAAATAGAATTTATTATATTACAAATAATAATGATATATTAAATTGAGCTTAGACCTAATAGAAAGAAACAACTTCAAACTTTCCATTTTCACTGTAGTGTCTTTGTTGAATTGCTAAATATTAGGTACAAATGCTCAAAGAGGATGTTTTTATGGCATACAGCAGAAAACTAGGTTAATATTCACATGTAGTCATGGTTTTGAGGTTTTTGACTATTACGCCTTTTAATTAATGATTTAGCAACCTTGTTTATTGAATGCATTTCTTTGGTAATTTTATTCTCAAACCCTATCTTAACTTTTTACTACCAAGATGATGATATGAATTATGAAAGTAATCGGCAATAAATACTTTTATATATAAACTCCGTTTACTAAAAAGAATCAATATTAAAGAGAAGCATTGAAAATATTATGAATCCAAATACCCAATTTTCCTTTTTTTTATGGCAACAACATTGTAGAGTTCCCCTATTTTTGTCCTCATGAATATATTTGAGAGAGTAATCACGTCCAGCATTTAGCAATATCATATTGTGGAGGGGTGTTTGTCGGATAAATCATATAAAATCCCGTGAGAAGAATACTTAAAATAACTACTCAATATCCATAATATGGATTTTCTATGGTAACTTTTTAATCAGAATATTAGTATTGTAAAAATTAGATTTTGCTTCGAAAAAATAATTCATGATTTTTTTAAGAAAACAAATGCAAAATCCAAAAAAGTCTTATAAAAATGCAAGAACCTATAGAGACATGTCATTATACAAATACTTTTTCACTCACACTGCTCACATATTGAAAATATCTATTGAAAATGAAAAGCAAAAATGTGGATCTCAGCTTAACCCTTTCATATAAAATACAACATTCTAATTTACTGAAAATCAATGTTACATTCCATTAGCAGGGTTCAACATAAGACATCCTTCAAGTCTTTCTATAAGTTCTAAAAGACAATGGTATAGAACAAGAAAAATACCAAGATGACACATAAATAATACGTAGCAAAGTGTTTGTGTTTTTCTTACGAAATAGTAGTAATTTTGTTAGCATTTTCTATGCGGCAAGTTTGTACTTCACAAGTCCTGTAGTGGTCACAGCAGTTTTTGCTGTGTTCTTTAATTATAGCTTAACTATTCTCATAGCATATCCTTGTATGATATACTTAATAAATAAAGGATATAGAGAGGCAATGTATCTATATCATGACTCTGATAAATTCTGCCTTGTCACCACAGAAAACCTTGATCACGGTCACTGACAATTTTCAACAAAGCTAGAAAATACAAGAAATATCAAGACTTCATGCTCCACTCTAACTCTGTCTTATTTTGACATAAAACTCAAACATTTTACTTGATGTTATGCTTACGCTACATCAGTTATATGCATAGCCCAACCTTTATTCATGTTTGCCTACAAAAATATGTCTTGGCAAATGTGCACATGCAAATGAATTGAGCCCAACAAATGAGTTCCCAACAAATGTGTTGATTTCTCTCTAAAATATGGCCAGACAAGATTGTGTAATTCTACATGGCCATATTATTAAACTTGTAAAAATTATATGCTGACCTGTCTCTAATAAATTATTCTGTATAATTATTCATAGCTACAGCTTAACAGTTTTCTAAAAAACTCTTACATCGACTATACCTTCAAATATGATTAAACTCCCTTTTAAATTTCCCTTGGCAATAGTGTTTTACATAGGTCACAATAATGGATAACCTTTATGTTCATTTTAATCGTGACTCATATAAAAAACAGTGCAAAATGTCCCATGTTCTACTGCTTCATATTTTAGGGAAGTTTGAATTTGTTAGCAAATCCTTTTAGCTGTTCTATTGTTGAAGGCTAAAACATTAATCTTCAAACAGAAATAAAAATTTTTACATACATTTGCCCATTTGCTTGTTCAGGATATAAAAACCAACTAAACAATAGCAATTAAGAGAGGCTACAGGCCCGGCACGATCGGCTCACACCTGTAATCCCAGCACTGTTGAGCGAGCGGGTCGATACTTAGGTCAGTGAGTTTGAGAACAGGCCTCACCCACATGGTGAAGACCCGATCTCGTACTAAAAATACAAAATTAGCCGGCATCTGGTGGCAAATGCATAATCGCAGTACTTGGGAGCCTGAGGCTGGAGAATTGCTTGTAGCCTGCGAGGCAGAGGTTGCAGTGGAGCTGAGACGCGCCATTGCACTCCAGCCTGGGCAACAAAACAAACTCCGTCTCAAAAAAAAAAAAAAAAAAAAAAAAAAGAGAGAGACAGAGAAGAGAGAGAGCTGCTAATCAGTCGATATAGAACATACTATACGTTTTCAATCATCAATAAAACATTAATGTCATTGGTGTTGCATTTCCCTTGAGCATGAGAGACTGTGTGACATAAACTAAAGATCAATTACTTTAATGAATCAATACTACAAGTTCTTTGTTATAGAATTTTTCAGAATAAGGAAATAAAATTGAATGTATAGGCATACTTTGAATTGTGATTCTATTCTTACTAACTTTAGTTCCATTTCTTCACTCTAAAACTCTTCATTGAGTAAGCTATCTTTTGCAATTATCTTACTACCAAGAGATTGATATTCGTCTAATGCCACAAATATTATAATTATTACTAAATTCTACCAATTCTAGGTACAATTGAATTGTTTTAACAGTACCTGTATAAAAGTCATTTATTCACCATAAGCTTTCAATCAAAATAATATGTGACTCTGACTACCCTCCACCTAGTTAAATTGTTTCCTCTTGCTGCCCCCTTTAAGCAAATTATATTCCTCCCATTCACCCTTCCTGATCCAACGACCTCAGCCACTAATCCTGATTTCTTGAACACACAGTTGGTCTGCCACGAAAGGATTAGTTATTTTGTCTTCGCACGGTCTCGTGACTTCAGTAAGCTCGGAATCCATACAAAATATCTATATTGTCATTGCATGCTCTTCCCTTACTCATCATGTTTTTGAAGTTTCACTTCTATTAGTGTACCTCCTTTTGTCTTAGTAGAGGTGTTAAAAATATGCCGCACATGTGTTATCCAATCTTCTGTTATTAACATTTTGATTATTTCATTTTTCTTCTCCCTGTTTGGTTACTATGATGAATATGTAATAAACATCTTTGTTAAAAGTGCTTATATTAATGATAAATGTGAATGTTAATATACTTTTATAGACTAAATAGCTGCGGAATCTTATGCTCGTGCCGCCGAGCGAGTGTAGAACCTCTCTATTGCGCATTCATCTAAATGTAGGGCCTGCTTTGTCGAAATAAATGGATCAATCATGCCCTGCAATTTACACAGATTGTAAAGTTATGTTCAAAATATAATCCCTTTAAGATGCGAACGTGTTCAAGGAAAACATTGAGCTAGGAGGAAGTGGAGGCTTGCGTGTAGAGTTGGGCAATCTTAGCAAAGGTTTCCTACTTGCGGCAACTTCTCGCAAGCCATCCTACCTCCATACAAACACATAGACAAAAAGCACCAAATCTCGCTGACCACTACTACTATGATCATGCAGCATCATCCTGTTCAATAACCAACAAGAAAAAATTATCTAATTATCCTTTCCTGGCCAATTTTGCCCTGACAGTTTTGTAGGCAAGTACTCACAATTGTAAATTAAACATCAACCGCTCCACGGAACCACACGCTTCGCCTATCCATCTACCCTCTTCCCTGAAAAGCCCAATAGTTTTAGAACCAACTCCAGGAGTGATTCCAGCGGTTTCACAGAACACCCTATTAGCGAACCCTCAAACTGAGCTACTCTTCTTTGCCGCAATGTGAGCTGGACTACACTCCACCTTTTCCTGAGTTCTTTAACTTCTCGGGTAGTAACTTGGCGCTAAGGGTAGATGTGGCTGCCTATCTATCCTGCTATTTTAAGACCTGTATTTCGTTTAGAGTTCAACTGTTAGCTAATATCTCTTGTTAATATTTCATTATTCTTTATATTAAACTTCCTCTCGGACCATAATGTTCTAGATTCCTTCTTTTGATTGAAATCAGGACTGAGTAGTACAATTGCTTGATTTCTTATAGTCAGTTTCATGTTATACAACACATTGTGTCATTTTTGTAAAACTCACTCCTTAGCTCGATAAATATTACGGTCCAACGAATTTCTTAGATTACCCTGCCATTCAAGATCTTTCCTTCAAATAGCATTAGATTATACGTCGTTTTCTACGTTTTTAACCATTCTACTACGGCCGCTTGAGAAAATTTCTCGCGCATAGGTTTTCACGATTGTCGAAACTCGCCTCGAACGCCAATAATTGTTAAGCATCTTTCATGTGCCTGTTGAGGCCATAACTTATGAATATTACTCGTGTAAATACATGAAATGCCTTTCCAAATTTTTGCCCATTAAATAAAACTAGGTCTATTCTTCATTATCAAACTCGTTTATCCACACATAGAACTTTGCATAAATTAGGATTACATGTCTACTTGGTCAGATAAAGCACACTCGGAGAATTGTTCCATAAGTATATTCTTCTCCCTTATGAACTGTCTTCCCTCTTACTTTTTAATAACTTAGCTAAATGTCATTCGAAGAGCATAAGTTTTTTAATTGATACAAAGGGCCAGTTCATTCGGTTACCTATCAATTTTTAATGCAGCACATATAATGATAACAACAATTAAGATTAATCTTACCCCTTCAAATTACCATTCGTTGTTGAGAGCACCATGTGAATAATGTAAGGTTCATTTACTTTTTAAATCACTCATGATTGCTTATCGATAACTATTCTATTGCCCAAACCATATGATCGAAATGTATTTGCCTTCCATAGTCCACTCCTCAAATTACACCTAGAGATAAAGCTTTTCTAAAATAACTTCCTTGTTGCCCTGTTTCAGCCTACTGCGCGAGGAGTGCAATGGTTGAACAATACCCCAAGTTGCGACGAGAACTGGATTGTTATCGCATTTCTTAATTTTCAAGTTTTTAGGAGTAAAATCCATATTCTACACTAAGTAGTGTTTATTTTTACAGCTTTCCAGAAATGAAGATTGTTTGAATCGGAAATATGGCTGTGGATTCAAATCAAGAACGTTATCCATCATAATAAAGATTACATATTTGACTCCAAAACTTGAGACTATATACTACAAGTTTGTGGCGTCCCTCACACACACCAGATTGATAAACATATTCATCTCCCTCAAGATATGTTAGCTCTATTGTAAGCCAGTGAAATTGGCCTCAACTACCTGACTCCTGACTACACCTAAGTCAACTCCGAACGATAGTCTGCGTGTTGAATCAAGTTTCGTGTTCTAAATTTATGTAAAGGATAAACTCACATTGTGATCTTTTTGTAAGCTCTATCTACTTAAGCACAATAATATAGGAGACGATCGCATTCCATATTGTTCGCACTGTAACAATGTATCCTTCTTATGTAATTTAATGCTAGGGAGATGACACTTCTTGGTATTTGTGTATATGAATACTAAAACATAATATTTCTTCTTAGGTACACATCCCTTATCTGTTGCAGTATAATGGGCCCTTTAAAAATTATTTTCACTATTATAAATTAAAGCTGCTATGAGCATTCATGTGTAAGGCCTTTCTGGTGGTACATATCTGGTGTTCACATTTTTTACTGGTAGGAGGTCCCTAGCACCTAAATGGCTAAGTCATCACCAAGCCCAATAAAAGGCTAACGGTGAGTTTAACATGAGCATTTGCGGATTAGAACTCCTCAAACTGTTTCAAGAAAGGGTACTTATACATTTTATATTCCCACGACAGCGAGTGTATCATGAGAGAATTTTTCATGGGCTCCACCATCCTCTCCTTGAGGTAAGTCTTATGAGGAATGATTAAGAACTATGTATATCTAACATCATGAGTAAACAACTCTAAAGAGGCAGTGTAAGTACTAGTATCTCTCATTAGGTGGCATTCATTTGCATTCTCTAATTTGAAACTTAGTTATGGTTAGTCATCACTCTTTCATAGCTACATTTGCCAAAAACCAGACAGTAATATTGTGCTTCTTTCTGTGGATTCTGTCTTGAAATATTCTTTGTCTTATGTCATTAAAGAAAGTGTCTCATATTGGCGATTATTGATAGACGCAAATTAATATGAGCTCAACGACATACCTTTCATTGACTAAGGTGATTCTGCTAAGTAACCTTTTCGCCAATACTAGCTCTTTGTTGTTAATCTCGAATTCCAGCAGTGATCTTTGAAAGACATTCATCAAATCTCCTCATTATTGGCAAAGCTAGCAACATCATTTATTGTTCCCTTGTAAAACAAACTCGATGTCTTTTGTGTTATATTTAGAAAACTTTGCACAATTCAAAGTGTGTATATAGATGTTATATTGCATTAAGATTTATTTTAAGTTAATTTTCCTATGTAGTGTGAGGTATAAGTCAGATGGAAGTTCATTTGGGGCAATATGGAATCTCAGTTTTTCCTAGTATAGATTTGTTTCACTGAGATGTCTATTTCTTTATTAAAAAAATCATTGTAAACCATTTATGTGAGGACTGATTCTTGATTTTAGTAATTTCAAAAGATTAGAAAAACATCATAGCGAGTACAAAATAACATCCAGTTATGACTTACAAATTTGGTAAATCATGTATAGAAAAAATGATAAACGGTACAGCTCACAAAAACTATACAAACATTATGTGTAAGGGTGAAATATATGTTAAATTATCTTAAATTCTGAAAAATCAAGAAAGATTGCTATCTAATCAGTATGGAAAACAAGAAAATAATAAAATTACATGATTATAAGGAAAACAAAACTCATATTCAAAGATGAGGCATGATTAATGTATATAAAGGAACCCACAGTTGATTTACAGATCAATCATTAAAAATTTAATATATTTAGAGCCAAATTATCAAATCGCACAGTTAATTAAAAGATCATTGATTTTCTTATACGGCAGAAAAACAGAATGTGTCATCAAAAAATTATGTTACTGATATTCAATCAACTAGGATCGTCACAAAAATGGTTACCTTCTAAAGTCGCAAATGAAGAACAAATGAAGAGCCTATTAATAAATAAAATGGTAAATATTACCCCATGGCGCAATCAAAAGAAGAAAAATTACTACTAATTCTTGCCAATTGCAAATGCTTCCCACCAAATATGAAAATTTAGAGTACATCCACCTTTCATTCTATAAAGGAGTAAAGGCAATTTCATAAAACTATCACACTAAATCGAAAATTGAATGAAAAATATTTGGTAAATAATTTAAGTGAAGATTTATACTAGTCACAGAAAAAGAATGGTACCATGAATATTGCCGTAGTTGCTTCCTCCTCGAGAATAGAAAAACAAGGTAACACAGTGCCTCGCTTAGGCATCCACACAGAGCCGATGCTATCGGACCAGGGTCTGGAGTCCGAAATGTTAGCAAATCAACTGAGTACACCAAAATACCAAGTTATAAGTAGATGGACAAGGAAATTGTGTACTTGGGGCAAAACAAGACACTAAATGGATTCAATACGAAGTGAGATGAGCAGAAAAAATAACATTCATATATACTTTGGGAACATCTAGCATTTGACAAAGATGGAATAGAAAAAGATAGTAGTAGAACTTGATGACTACCCTACAATTAAACACAGGCGCTGGTAAAACCTGAGTTAAAATGACAAATTATCATACGAGCGCTATCTCCATCCCTCAAATCCTTGTTATCTCCTACAATCTTCCAAAAAAAGAAGCTAAAGATCTATTGTGAAATGTATAAACTGAAACCTTCAATAAGACACACAGTAGACTTCATATAAACTTGAACATGAAAAATATTTCGCAAACCAAATACAAAGACATAAAACACATAAGTTAAAATTTGAGCATTTCCACTTACATTAATACTAACATATAATTAACCAGTAGACCACCAAAAGGTGATCAAAAAGTGGAAAGTAAGACATTTGTAACATATACAAATGTGTTGTGGTGTATGTACTTACATACACATTATATTGTATACTTCCCTTTCTATAATAGCTTAATATAGATTTGTAAAGATTTATACAAATGATTAACAAAAAGATATACACCTTACACATACCAATGTGAAAATAAATTGAACATCAGACTTCTAATAAGAAGGATATATGATAACTATTCGACCAACGAAAAATGTTAACAAATATTTACACCCGGCAAAGTAGAAGTTAACTATATAAAATATAATTTATCATCAGTTTAAAAAAATGAAAATGTCAAGAAAGTAGATAAGTGTTGACTCACCAGCAAGTGAGCAACAAGAATTCTCTGTGGGATATAAATGAGGTACAACACTTTGAAAAAATAACTAAACATCATCACACAAAGTGAAGATGGCATCACACAACCCCTGATCCAAACAATCCACAACTAGGGGCATTCACCACCAGGAAACACACCTTCCAAATGATATCTCACGAAGACGATGCTCAAGAATTATTGTATCTAAGCGAGCTTATCATTGTCAAAACAAGTAAAACCAAAACCGCTGAGAGAGCACAGCATAATCAATCGGGAGAAAATCGATAACTACTATTTTACAGCAATACTACAATAAATCTACACAATATGAAAAATAAATTATAGCATGAACTATAAGAACTAATACAGATGGTATGACTATCGAGAATTATAAAAAGTGGGAAGTGAATACATAGAGTAATGTCAACTTAACAATGTACAACAAGAATCAGCAATCACCGAATATTTAATTATAAATTGAAAATAGTGCGGAAATTGCAAAAACAATTAATTGAATTAGCGAAAACAATAGATAAGTACAAACCCACAAAAGTAAGGAAAGAAAAAGGAAAATAGGAATAAAACACAAAGGTCAAGCTGATAGCCATATCTTTTTGAATGGAAAAAGTAATAAAGCTTTAACTTAAACCTAAATTTTATTTCTTAACTGACAAAAGTGAATATAAGTATACCGCTACATAATCAAGACTTATCATCATTTGATCCACCTACACATAGAATATACACATACTCTGTATGTAAAGTAATATGTAATGTCGTTTTTTAATTCGTGAATCTAATATATAATATATTACACAGAAATAAACAGCTTGAAAATGAAAACAATGAAATATAAATTTTCAAATTTTCAATGGAAAATTTAAAATTAGATAAAATCAATTAAGGCATATAGTAATAATGTAACAATATGAAGATAGAATAACAATACTTTATTTGGTAAACAAAGGCGTTAGAGTTTTGTCAAGCAAGATTTTGTTTAAATACAAAGTTTAACTAATGAGAAAAAATCAGCAAATAAAAAGAAAAATAATGCCCGACAATAGGAGAAAATTGAGGCAGTGTGGATAAAAGTGTAAATTAAAATACGTGAAAATTTGTGAGCCCAATATTAATAACCGCGCCCACAAGTAATGTAAAAATAAAATAACAATAATTTTGAAGGCCTCAGACATATGAAGTAACATAAATCTAGAATTTGCGAAATACAATGACAATTATTAAATACAAATACACAAAAATTTACTAAAAACATAGTGTGTCTTTTCAAAAGTTTAGAAATAATAGTTAAGTACTAAAAATATATGGTAAGACTGAATCAAAGGACATGTTAAATTTATTACCTGAAGAAAAACTGTTAGTAACAAAAAAAGAGGGGAGAGATGAAAAGCTATAAAGCTGGTGGCAAAGCAACCCAGGATAAGAGGATATGAATGAAAAAAGCAAAGTATAAGCCACTTGTCTATTCAGAAGATGGACAATGTGATTAACTCAGCTTCATAAACCCGTGTATCTAGGTTAGAAATAGTCAAAAAATAATACTGTACTATGAAGATTTACAGTGAAAATTGAGTATGTAATGACTTAATATCTCAATAAATGCATTTAAAAAAAATGAATGAAAACAATGCCACACTATCTAATGTTTGAGGAATACAGTAAATGAAAGCTGTTAACTTAATTTTTATAAAAACGTACAGGTTTAAAAATAATGCACGGTATTAAAAGATAATAAGTCAACCAGGGTCAGGGATGGAAAGTGGAGGCACTGTTCCTATAAGGGTAATATAATTGCCATTAAATATTTATTTTAAACGTCTTAACCAAATCATTATAAGAGAAGAAAATAAACAAAATAAACTAGAATAAATAAAAGTTTGGCAGAGCAGAAAACCAATCAATAAAATAAGAAAAGGCAAAGACAGCAGAAATGGAGAAATATTTGCAATCATATATGCTGACTCAATATTACCATCACATCTGACAAGGATTAATATTAAATTTTAAATCGGAACTTACGACTCAAATAATCAAAAATCCAATTAAAAATGAGGTCAAAAGGATATGAACAGACATTTTTCCAAAAATAGACATAACCCACACATTTACAAAGAGTATACGAAAAGGTGCTCAAAGACGTCATTATTTAAGCAAGCGGCGAATCAATCAAAATGCGCACATGTCATTCCTCTCACACTGGGATGTATCTTGCAAAAAGCAAAAGATAATAAACAATTTTGAAAATGTGACAAAACATTCAGCAAATGGGAAACCCTTCCTAATACATTGTTTGCAAGAATGTAAATTGGCACAGCTAATTAATTAAGAACATTACTGGATGCATCCTATAAAATTTTAAAATATTATTATTATAGGTTTCTAGAACACCGTCACTATCTGGGATAATGTGTTATATATATGTTTATGTTTATGTGTGAAAGTGTGTTGTATATATAAGGTCCCAAAAAATCACTTAGTCTTTCGAAGAGAGAATAATCTTGCATAAACCTTGTATGTTTAGATTACAGCAATTACCATTTATAAAAGTCACGGATACGGAATAACCCAAGGTGAATATAGATAGATGAGATGATAAAGAGAGAATGATATATATATAATACACATGCTCTATACTATACCTACACACCCTCCTTAGTAATATGCACAATGTAATATTATTCAGGCCTTAAAAAAGAGAAGTTTTGTGTTTTGCAACAAAATGGATGACCTGGAGATATCATGCTAAGCAAAATAAGCAGACACACGAAAGACACACTAAAAAATATACTACAGATCTCAGTTATATATGGTCAAACTCATAGCAAAAGAAGTCAAAGGCATGATAACCAGAATGGAGGGAGCAGAGAAGTGTTACACAGGATACAATTCTTGCAGGGCTGTGAGATGAGTTAACGTTCCCTGGAAAGCTACATGTCCGGCATGATGACTACGTAGTTAATAAGAATGTGTCTAGGTACTTGAATTTCTAGAAACGTAACTCTAAGCAGGCGCCGTGGCTCATCGCATGTAATCAGCACTTGGAGCCGAGGGCCGGGCGATCCCACCGACGCTGCAGGATGACCAGACCATCCTACGCTACACACCGGTGAACACCCATCTCCTAAATATCACACCAAAAATTAGCCTGGCACTGGGGCTCGGAGGGTAGTCCAGCACGGAACGCTAAGCAAGCGAGCATATACGTCGTCGAACCCTGCGAGGCGAGCTCGCAAGTTGATCCAAGACTCTATCCACCTAGCCTCACCTGAGACAGAGCGAGGACTCCATTCTCGGAAAAAAAATTATACCTTTACGATGTTCTCAACTAGACACACATCCCTGCATCATACAACACACCCAATTCACAAGAAAGGTAACAAATGAGGTGATGGACTATGAAATCTATATAAAAGCTGAGAGATGGGGTAATATTCAACAACCATAAAGTTCTAACGTAAAAAAAGCCTCTATCTATATACAATACACTCTAGAAATAACTAACAATTGTTATTTGCACTAATATGCCTAAAGATACTGAAGAACTTTTATAATGGAGAATATAGAGAATCTAAACGAGCATCTGGAGACTGCAGAGCATCTAGAACAGAGAATAAATATATCATCCCCTTAGAGGGCTCCGGAGAGCCGACAGAAAAAACACGCACCAGGCCTGCACCCGAACACCACTCTGCTTCAGAGACGCGCGGAAGACTTTACTGTCAATGAACGAATGCACATCCTTAACATGCTTTCCTCTACCGCCAACTGAAGATGTTCTGTCACCCTGTTTTTGTAGCGGCAGCAGAGTTGGCAGTCAGACCATTCACAGATGCCTCGCATCGTTGGTGCAAGTTACATACAATAAGCGATTGAAGCCAGAAAAAAGCACTATCGTCATGTTCTCAATCTCTTTCATCGCTCATTAGAGAAGAGACACTACCGACTTCTTCATTTCAGTACACGTCTTAAGGATACACACTGCTCCAGCGACATTCTTCCTGGGCATTCAAGAGTGCGAGTACTCTGAGCCGCCCCTCTGCTCCAGAAAGGTCACATCGTTTGCCCGTGCCTTTTGCAAATCTAATAATTTTATTTTAAGTTTGTGTTTGGACATGAAGTCTGGTAGAGCACTAGGACATGATTCAGCAAGACATTATCACAACATACAAGTGGGCCCTTAATGCCCACTCTAGACCTACCAGGCTACCTCTTCCCCAAACTCTCTCTTGACACCTCATGATGGTGAGCCTACCTTCCATCGTAGTCCTCCCACACTTGGAGAGGCTGGGCATTGGCAAGCAGAGAGTGAAAAGCGCATGGTTGCACTGCACCGGCCTCTTGATGGTAAGGGCAAAAAGTGCGCATTCCCTCCAGCCTTGTGCTTCCACAAGGTTTTGGCTCTCACCTACCCATGTAGATCTAGGTGGCTGAGTGTCCGCCAGACACAGGTTGCAATCATCCTGAGGTCTTCAATCATCTGTGCATTGAAGAGTCCCGCCATGAAAAGATATATTGATTTCCCTGCCCATCTCGAGCCCTGCCTTTTTTTGTTTCACTGGGACCCTACCAAATTGTAGCTGGCCCTGTCTATAAATGTCTATAATCCCCCAAAACAGATATAGATTGGCTAGAGATGGGTAACTTCCAGTCTTATATGGAGTTTGATAGAATACCTGACGATTCCTCCACCAACTAAAGACAGAAGGCTGGTGAAATAGAGTCGCCACAAACAGTAGCCACCATTTGTGGATGGCATGCCTGACAGCGACGTGTTCTAGGCGGTAC";
   int awidth = 256;
   //   char * query = "GGGTGGGTCGGTTTTGGGGTGGAGAGAGAGAATATGGGGAAACTTTCCGCACAAATACTACATAATGTATGGTTTGACGCTAGTAGGAAAAATAAAGAGATAGCGAAGTGGTGTACTATGACCTGGAAGATAGTATATTGCTATCAATTTACAGATTAATCTAAGAGTAACTTTTCTGGAAGTATGTAGTTGTGTAAATTCGAAGGAATCTCTGCTATAGTTAATGTATCTTTATGTAGAGTATTCGTAAGTGATCCAAGTAAAATGAGATAAATGTAATAATATTGTCATACTGTTCTATTAAGTTTTGCATATATTAAAACTTTATTCCTCAAATGTCGGGCTATCTAAATAGGAGGATGATGTTGGGCAAGGGGATATTTGATTTGTTATATGGATGTAAAAAAAAGAAGAGGAAGCATGTCAATTTCATAAGCGCGCACGCGACATTTCTATTCTTGGCTAATCCGTACTATAGTTCAAGTAGAAGGAGAATAAAAGTAGTGTAAGCGGAAAGTCTTTTTTAAAAAACTGTACCTAAAGGCTAAAAAAGTGAAACATTTGGTTGGTCTCACCAGAACTTGCTAAGTTTGTTGGCGATGGCTGAAGTTACCGTTATTTTGAAAGATCCCAGAATATCTGTGCTAGGGAAAGGTCCTAAGTAAGTTTAAAGAATCCAGTGTTCAACCAAATCAGTCTCCCCTAAGGGCGTCTAAGCTAATGAGAGATGATCCCTTTAGGAAGCTGAAAGGTTTTGTAATAGAGGAGTTCAAAGAAGGCAAGTCTCACGATGGCAGAGTTTATATAAATATCAAAAATATGTCACTGATGTTTAATGTGTAAGTTATCATAATTGTATGGTTCAACACACCTTGGTAATTATTACTATGTAGAAATTAAGTGCAGCTTTATGAATGTTAACGAAATATGTGCAGGAAAAGTCATAAAACGATTGAGCTGTAGTAGATAATATAAAACAGACTATCTAAACTAAAAGTTTCCTGGATCTTACTTCGCTAAAAGCCTCGAAGACCCTTTTGTCCCTTTTATTTAGTATATCTTTTATTTTAGAGCAGTTCTTCTGGCCCTGTCAAACTACCGTGTATTGTTTTCGAAGTTAATCGGAGTTGATAAGAGGAACTAGAGAAGCAGATGCCGTTCCACAGGTTTGATGGCACATTACATAAGAGTGTTTTTCTGCTGCAGTAGCAGGACATTGATAAGGTAGTGGTGCTGGGCTGAGCGATTCATCTCGTGGTCGCACTACTATCAGCAGACATAAAGTGGCCTTCTCGTCCACTATGCTTCATGTTAGTGAAATAAAGTTAAATGATGAGTAAATACAAGTTGGAGGTCAGTCTATATGAGCTAAGGATATCAGTAAAGTTTTTATGATTTTATTTCATGTCATAGCTTAACAGCACCGATTAACTGATGTATTTTAAAATCAGTAGTTGTGTTCAGTGTAAATCTACTGCCAAATAAACTAAATTAATAGTTCCGTATTCGTCAAACATTAGTTCGGAGATCAGTTAAAAAGTTTTTCCATGATTTATAATGCGTTGTCAAGTGGGCCCCTAAATACTGGCAGGCCAATTATTTTCGATTGGAGTCTATCACGCTTCTTGACTTGTGAACCTCCCTCAAGACAGTCAAGCATCTGCCTTGCCCATTGTAAAGTACTCTCGAAGGTGACAATCCCTGCTTCATATTTCACTGAGAAAGAATCAATGACATGAGGGTGACAGTTTCATCACTGAAAATCCATCAATTTCGCGAATTTTATACTGAAGATCCTACATTTAATTGATATCATTCTGCAGTTTTCCCCAGTGCTACATCATCCATGTTCTCACTTCCATTTGGATTATGTAATACAAATAACTGGATGTCTCCTCATATTAAAAAAACTCAAAAAGAATAACAAAGACCTTGACCTACTTGCTCCCCATCGTCTAGCTCCCTATTCAAAACCGTTGAGACCTC";
   //   char *   ref = "AATTCAACTGACAATGTGAAAACCTTCATTAATCCTAAAAACAAAGAAAAAAAGGATTCTTGAAATCTATGGAAAAAAAGTGAACATATGCAAAAGGCTAGCCAATCTGAGAATAATTACTGAAGGATTATTTGAAGTACCATTAAAAACATAATGAAGTACATATCTTGAGTCAGTATTGTATGCATTAAGTAACAAGTATGCTAAATACAAAATGTCAAGCTGTTAATATGAATACTACTGTAATATACACAATTAAGCAAATCTTTAGAAAAACACATTATCAATAACAATGACTTGAAGAGGTACAAAATACATATGAATTAAAATAGAATTTATTATATTACAAATAATAATGATATATTAAATTGAGCTTAGACCTAATAGAAAGAAACAACTTCAAACTTTCCATTTTCACTGTAGTGTCTTTGTTGAATTGCTAAATATTAGGTACAAATGCTCAAAGAGGATGTTTTTATGGCATACAGCAGAAAACTAGGTTAATATTCACATGTAGTCATGGTTTTGAGGTTTTTGACTATTACGCCTTTTAATTAATGATTTAGCAACCTTGTTTATTGAATGCATTTCTTTGGTAATTTTATTCTCAAACCCTATCTTAACTTTTTACTACCAAGATGATGATATGAATTATGAAAGTAATCGGCAATAAATACTTTTATATATAAACTCCGTTTACTAAAAAGAATCAATATTAAAGAGAAGCATTGAAAATATTATGAATCCAAATACCCAATTTTCCTTTTTTTTATGGCAACAACATTGTAGAGTTCCCCTATTTTTGTCCTCATGAATATATTTGAGAGAGTAATCACGTCCAGCATTTAGCAATATCATATTGTGGAGGGGTGTTTGTCGGATAAATCATATAAAATCCCGTGAGAAGAATACTTAAAATAACTACTCAATATCCATAATATGGATTTTCTATGGTAACTTTTTAATCAGAATATTAGTATTGTAAAAATTAGATTTTGCTTCGAAAAAATAATTCATGATTTTTTTAAGAAAACAAATGCAAAATCCAAAAAAGTCTTATAAAAATGCAAGAACCTATAGAGACATGTCATTATACAAATACTTTTTCACTCACACTGCTCACATATTGAAAATATCTATTGAAAATGAAAAGCAAAAATGTGGATCTCAGCTTAACCCTTTCATATAAAATACAACATTCTAATTTACTGAAAATCAATGTTACATTCCATTAGCAGGGTTCAACATAAGACATCCTTCAAGTCTTTCTATAAGTTCTAAAAGACAATGGTATAGAACAAGAAAAATACCAAGATGACACATAAATAATACGTAGCAAAGTGTTTGTGTTTTTCTTACGAAATAGTAGTAATTTTGTTAGCATTTTCTATGCGGCAAGTTTGTACTTCACAAGTCCTGTAGTGGTCACAGCAGTTTTTGCTGTGTTCTTTAATTATAGCTTAACTATTCTCATAGCATATCCTTGTATGATATACTTAATAAATAAAGGATATAGAGAGGCAATGTATCTATATCATGACTCTGATAAATTCTGCCTTGTCACCACAGAAAACCTTGATCACGGTCACTGACAATTTTCAACAAAGCTAGAAAATACAAGAAATATCAAGACTTCATGCTCCACTCTACTGTCTTATTTTGACATAAAACTCAAACATTTTACTTGATGTTATGCTTACGCTACATCAGTTATATGCATAGCCCAACCTTTATTCATGTTTGCCTACAAAAATATGTCTTGGCAAATGTGCACATGCAAATGAATTGAGCCCAACAAATGAGTTCCCAACAAATGTGTTGATTTCTCTCTAAAATATGGCCAGACAAGATTGTGTAATTCTACATGGCCATATTATTAAACTTGTAAAAATTATATGCTGACCTGTCTCTAATAAATTATTCTGTATAATTATTCATAGCTACAGCTTAACAGTTTTCTAAAAAACTCTTACATCGACTATACCT";
   //   int awidth = 128;
   //char * query = "TAAAAAAAAAAAAAAAAAAACTGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGA";
   //char * ref   = "AAAAAAAAAAAAAAAAAAAAACTGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGA";
   //int    awidth= 64;
   //   char * query = "AAAATTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
   //   char * ref   = "AAAAATTTTTAAAAAATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAA";
   //   int    awidth= 64;
   //   char * query = "TGACTGACTGACTGACGTAGTCGTCGTACTATCAGTCGTACGTAGTCAGTCACGTCACGACGTACGTCTGAGTCTGACGTACGCGTAGTCATGCTGACGTACGTAGTCATGCGACCGCATCATCGACG";
   //char * ref = "ATCTAGTCGTCATGCTGAGTCTGCATGCGTAGCTGTACGTACCAGCGCAGCGAGAGTAGTAGTATGGCAGACGTACGGCACCACGTACTGCGTACGTAGTCGTCAGTCTGATCTGACGTACGTCGTATGC";
   //char * query = "TAAATCATGCCCCCCGGGGGGTTTTTATATATA";
   //char * ref   = "TAAATATGCCCCCCGGGGGGTTTTTAATATATA";
   //int    awidth= 5;


   //Compute query blocks.
   uint32_t rlen = strlen(ref);
   uint32_t qlen = strlen(query);
   fprintf(stdout, "query: %d nt, ref: %d nt, cells: %d\n", qlen, rlen, qlen*rlen);

   //   dumb_align(query, ref, qlen, rlen, awidth);
   uint32_t score = mbf_align(qlen, query, rlen, ref, 1, awidth);

   fprintf(stdout, "mbf score: %d\n", score);

   return 0;
}
