#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

/*
#include <mmintrin.h>  // MMX
#include <xmmintrin.h> // SSE
#include <emmintrin.h> // SSE2
#include <pmmintrin.h> // SSE3
#include <tmmintrin.h> // SSSE3
#include <smmintrin.h> // SSE4.1
#include <nmmintrin.h> // SSE4.2
#include <immintrin.h> // AVX
*/
#include <x86intrin.h>

#define align_min(a,b) ((a) < (b) ? (a) : (b))
#define align_max(a,b) ((a) > (b) ? (a) : (b))

#define _reg    __m128i
#define REG_WIDTH 128
#define _reg_andn(a,b)  _mm_andnot_si128(a,b) //SSE2
#define _reg_and(a,b)   _mm_and_si128(a,b)    //SSE2

// word: 8bits
/*
#define _word              uint8_t
#define REG_WORDS          16
#define MAX_VALUE          0xFF
#define _reg_sll(a,b)      _mm_slli_si128(a,b)    //SSE2
#define _reg_srl(a,b)      _mm_srli_si128(a,b)    //SSE2
#define _reg_set(a)        _mm_set1_epi8(a)       //SSE2
#define _reg_adds(a,b)     _mm_adds_epu8(a,b)     //SSE2
#define _reg_add(a,b)      _mm_add_epi8(a,b)      //SSE2
#define _reg_cmpeq(a,b)    _mm_cmpeq_epi8(a,b)    //SSE2
#define _reg_cmplt(a,b)    _mm_cmplt_epi8(a,b)    //SSE2
#define _reg_min(a,b)      _mm_min_epu8(a,b)      //SSE2
#define _reg_blend(a,b,c)  _mm_blendv_epi8(a,b,c) //SSE4.1
*/

//word: 16bits
#define _word              uint16_t
#define REG_WORDS          8
#define MAX_VALUE          0xFFFF
#define _reg_sll(a,b)      _mm_slli_si128(a,2*b)  //SSE2
#define _reg_srl(a,b)      _mm_srli_si128(a,2*b)  //SSE2
#define _reg_set(a)        _mm_set1_epi16(a)      //SSE2
#define _reg_add(a,b)      _mm_add_epi16(a,b)     //SSE2
#define _reg_adds(a,b)     _mm_adds_epu16(a,b)    //SSE2
#define _reg_cmpeq(a,b)    _mm_cmpeq_epi16(a,b)   //SSE2
#define _reg_cmplt(a,b)    _mm_cmplt_epi16(a,b)   //SSE2
#define _reg_min(a,b)      _mm_min_epu16(a,b)     //SSE4.1
#define _reg_blend(a,b,c)  _mm_blendv_epi8(a,b,c) //SSE4.1


int
simd_align_sse2
(
 char * qry,
 char * ref,
 int qlen,
 int rlen,
 int align_width
)
{
   size_t regcnt = 1+2*((align_width+REG_WORDS/2)/REG_WORDS);
   int    regwrd = regcnt * REG_WORDS;
   int    dif    = rlen - qlen;
   int    steps  = align_min(qlen,rlen) + dif/2;

   if (align_width < dif) return -1;

   // Aux vars.
   _reg ones = _reg_set(1);

   // Registers.
   _reg * Q  = calloc(regcnt,sizeof(_reg));
   _reg * R  = calloc(regcnt,sizeof(_reg));
   _reg * D  = malloc(regcnt*sizeof(_reg));
   _reg * S  = malloc(regcnt*sizeof(_reg));

   // Register byte access.
   _word * q  = (_word *) Q;
   _word * r  = (_word *) R;
   _word * d  = (_word *) D;
   _word * s  = (_word *) S;

   // Initialize Q,R,S,D.
   int k;
   // Initialize Q.
   for (k = regwrd/2 - 1; k >= qlen; k--) q[regwrd/2 - 1 - k] = 'Q';
   for (; k >= 0; k--) q[regwrd/2 - 1 - k] = qry[k];
   for (k = regwrd/2; k < regwrd; k++) q[k] = 'Q';
   // Initialize R.
   for (k = 0; k < regwrd/2; k++) r[k] = 'R';
   for (k = 0; k < regwrd/2 && k < rlen; k++) r[regwrd/2 + k] = ref[k];
   for (; k < regwrd/2; k++) r[regwrd/2 + k] = 'R';
   // Initialize S.
   for (int i = 0, v = regwrd/2; i < regwrd/2; i++)
      s[i] = s[regwrd-1-i] = v--;
   // Initialize D.
   for (int i = 0, v = regwrd/2; i < regwrd/2; i++) {
      d[regwrd-1-i] = v--;
      d[i] = v;
   }

   // Alignment.
   for (int i = 0; i < steps; i++) {
      // TODO: at the end of the alignment, there will be parts of the
      // diagonal that fall off the matrix, in that case the values of j
      // can be restricted only to these words that represent matrix values.

      // Step Right D,S -> D.
      _word R_in = (regwrd/2 + i >= rlen ? 'R' : ref[regwrd/2 + i]);
      _word S_in = MAX_VALUE;
      for (int j = regcnt-1; j >= 0; j--) {
         // Update R.
         r = (_word *)&(R[j]);
         _word R_out = r[0];
         R[j] = _reg_srl(R[j], 1);
         r[REG_WORDS-1] = R_in;
         R_in = R_out;
         // Update upper and side scores (gap).
         _reg G = _reg_adds(S[j], ones);
         // Compare Q and R (match/mismatch).
         _reg M = _reg_andn(_reg_cmpeq(Q[j],R[j]), ones);
         M = _reg_adds(M,D[j]);
         // Minimum between G and M.
         M = _reg_min(G, M);
         // Right shift the gaps and insert S_in.
         _word * g = (_word *)&G;
         _word S_out = g[0];
         G = _reg_srl(G, 1);
         g[REG_WORDS-1] = S_in;
         S_in = S_out;
         // Minimum between G and M.
         D[j] = _reg_min(G, M);
      }

      // Step Down S,D -> S.
      _word Q_in = (regwrd/2 + i >= qlen ? 'Q' : qry[regwrd/2 + i]);
      _word D_in = MAX_VALUE;
      for (int j = 0; j < regcnt; j++) {
         // Update Q.
         q = (_word *)&(Q[j]);
         _word Q_out = q[REG_WORDS-1];
         Q[j] = _reg_sll(Q[j], 1);
         q[0] = Q_in;
         Q_in = Q_out;
         // Update upper and side scores (gap).
         _reg G = _reg_adds(D[j], ones);
         // Compare Q and R (match/mismatch).
         _reg M = _reg_andn(_reg_cmpeq(Q[j],R[j]), ones);
         M = _reg_adds(M,S[j]);
         // Minimum between G and M.
         M = _reg_min(G, M);
         // Left shift the gaps and insert D_in.
         _word * g = (_word *)&G;
         _word D_out = g[REG_WORDS-1];
         G = _reg_sll(G, 1);
         g[0] = D_in;
         D_in = D_out;
         // Minimum between G and M.
         S[j] = _reg_min(G, M);
      }
   }

   // Return right-bottom corner.
   int byte = regwrd/2-1+dif/2+dif%2;

   if (dif%2) return s[byte];
   else       return d[byte];

}

/*
int
simd_align_ub
(
 char * qry,
 char * ref,
 int qlen,
 int rlen,
 int align_width
)
{
   size_t regcnt = 1+2*((align_width+REG_WORDS/2)/REG_WORDS);
   int    regwrd = regcnt * REG_WORDS;
   int    dif    = rlen - qlen;
   int    steps  = align_min(qlen,rlen) + dif/2;

   if (align_width < dif) return -1;

   // Aux vars.
   _reg ones = _reg_set(1);

   // Registers.
   _reg * Q  = calloc(regcnt,sizeof(_reg));
   _reg * R  = calloc(regcnt,sizeof(_reg));
   _reg * D  = malloc(regcnt*sizeof(_reg));
   _reg * UD = calloc(regcnt,sizeof(_reg));
   _reg * S  = malloc(regcnt*sizeof(_reg));
   _reg * US = calloc(regcnt,sizeof(_reg));

   // Register byte access.
   _word * q  = (_word *) Q;
   _word * r  = (_word *) R;
   _word * d  = (_word *) D;
   _word * s  = (_word *) S;

   // Initialize Q,R,S,D.
   int k;
   // Initialize Q.
   for (k = regwrd/2 - 1; k >= qlen; k--) q[regwrd/2 - 1 - k] = 'Q';
   for (; k >= 0; k--) q[regwrd/2 - 1 - k] = qry[k];
   for (k = regwrd/2; k < regwrd; k++) q[k] = 'Q';
   // Initialize R.
   for (k = 0; k < regwrd/2; k++) r[k] = 'R';
   for (k = 0; k < regwrd/2 && k < rlen; k++) r[regwrd/2 + k] = ref[k];
   for (; k < regwrd/2; k++) r[regwrd/2 + k] = 'R';
   // Initialize S.
   for (int i = 0, v = regwrd/2; i < regwrd/2; i++)
      s[i] = s[regwrd-1-i] = v--;
   // Initialize D.
   for (int i = 0, v = regwrd/2; i < regwrd/2; i++) {
      d[regwrd-1-i] = v--;
      d[i] = v;
   }

   // Alignment.
   for (int i = 0; i < steps; i++) {
      // TODO: at the end of the alignment, there will be parts of the
      // diagonal that fall off the matrix, in that case the values of j
      // can be restricted only to these words that represent matrix values.

      // Step Right D,S -> D.
      _word R_in = (regwrd/2 + i >= rlen ? 'R' : ref[regwrd/2 + i]);
      _word S_in = MAX_VALUE, US_in = MAX_VALUE;
      for (int j = regcnt-1; j >= 0; j--) {
         // Update R.
         r = (_word *)&(R[j]);
         _word R_out = r[0];
         R[j] = _reg_srl(R[j], 1);
         r[REG_WORDS-1] = R_in;
         R_in = R_out;
         // Update upper and side scores (gap).
         _reg G  = _reg_add(S[j], ones);
         _reg UG = _reg_adds(_reg_and(_reg_cmplt(G,S[j]),ones),US[j]);
         // Compare Q and R (match/mismatch).
         _reg M  = _reg_andn(_reg_cmpeq(Q[j],R[j]), ones);
         M = _reg_add(M,D[j]);
         _reg UM = _reg_adds(_reg_and(_reg_cmplt(M,D[j]),ones),UD[j]);
         // Minimum between G and M.
         M  = _reg_blend(G,M,_reg_cmplt(UG,UM));
         UM = _reg_min(UG, UM);
         M  = _reg_min(G, M);
         // Right shift the gaps and insert S_in.
         _word * g  = (_word *)&G;
         _word * ug = (_word *)&UG;
         _word S_out = g[0];
         _word US_out = ug[0];
         G = _reg_srl(G, 1);
         UG = _reg_srl(G, 1);
         g[REG_WORDS-1] = S_in;
         ug[REG_WORDS-1] = US_in;
         S_in = S_out;
         US_in = US_out;
         // Minimum between G and M.
         M     = _reg_blend(G,M,_reg_cmplt(UG,UM));
         UD[j] = _reg_min(UG, UM);
         D[j]  = _reg_min(G, M);
      }

      // Step Down S,D -> S.
      _word Q_in = (regwrd/2 + i >= qlen ? 'Q' : qry[regwrd/2 + i]);
      _word D_in = MAX_VALUE, UD_in = MAX_VALUE;
      for (int j = 0; j < regcnt; j++) {
         // Update Q.
         q = (_word *)&(Q[j]);
         _word Q_out = q[REG_WORDS-1];
         Q[j] = _reg_sll(Q[j], 1);
         q[0] = Q_in;
         Q_in = Q_out;
         // Update upper and side scores (gap).
         _reg G = _reg_add(D[j], ones);
         _reg UG = _reg_adds(_reg_and(_reg_cmplt(G,D[j]),ones),UD[j]);
         // Compare Q and R (match/mismatch).
         _reg M = _reg_andn(_reg_cmpeq(Q[j],R[j]), ones);
         M = _reg_add(M,S[j]);
         _reg UM = _reg_adds(_reg_and(_reg_cmplt(M,S[j]),ones),US[j]);
         // Minimum between G and M.
         M  = _reg_blend(G,M,_reg_cmplt(UG,UM));
         UM = _reg_min(UG, UM);
         M  = _reg_min(G, M);
         // Left shift the gaps and insert D_in.
         _word * g  = (_word *)&G;
         _word * ug = (_word *)&UG;
         _word D_out = g[REG_WORDS-1];
         _word UD_out = ug[REG_WORDS-1];
         G = _reg_sll(G, 1);
         UG = _reg_srl(G, 1);
         g[0] = D_in;
         ug[0] = UD_out;
         D_in = D_out;
         UD_in = UD_out;
         // Minimum between G and M.
         M     = _reg_blend(G,M,_reg_cmplt(UG,UM));
         US[j] = _reg_min(UG, UM);
         S[j]  = _reg_min(G, M);
      }
   }

   // Return right-bottom corner.
   int byte = REG_WORDS/2-1+dif/2+dif%2;
   int word = regcnt/2+(byte-REG_WORDS+1)/REG_WORDS;
   if (dif%2) {
      d = (_word *)&(S[word]);
      s = (_word *)&(US[word]);
   } else {
      d = (_word *)&(D[word]);
      s = (_word *)&(UD[word]);
   }

   return d[byte%REG_WORDS] | (s[byte%REG_WORDS] << 8);
}
*/

/*
// Only compatible with AVX2 hardware.
// Should work with Intel E5 v3.
int
simd_align_avx2
(
 char * qry,
 char * ref,
 int qlen,
 int rlen,
 int align_width
)
{
   // TODO: Potential use of carry flags to avoid saturated additions.
   //http://stackoverflow.com/questions/6659414/efficient-128-bit-addition-using-carry-flag

   size_t regcnt = 1+2*((align_width+16)/32);
   int    regwrd = regcnt * 32;
   int    steps  = align_max(qlen,rlen);

   // Aux vars.
   __m256i ones = _mm256_set1_epi8(1);

   // Registers.
   __m256i * Q = malloc(regcnt*sizeof(__m256i));
   __m256i * R = malloc(regcnt*sizeof(__m256i));
   __m256i * D = malloc(regcnt*sizeof(__m256i));
   __m256i * S = malloc(regcnt*sizeof(__m256i));
   __m256i * A = malloc(regcnt*sizeof(__m256i));

   // Register byte access.
   uint8_t * q = (uint8_t *) Q;
   uint8_t * r = (uint8_t *) R;
   uint8_t * d = (uint8_t *) D;
   uint8_t * s = (uint8_t *) S;
   uint8_t * a = (uint8_t *) A;

   // Initialize Q,R,S,D.
   int k;
   // Initialize Q.
   for (k = regwrd/2 - 1; k >= qlen; k--) q[regwrd/2 - 1 - k] = 'Q';
   for (; k >= 0; k--) q[regwrd/2 - 1 - k] = qry[k];
   for (k = regwrd/2; k < regwrd; k++) q[k] = 'Q';
   // Initialize R.
   for (k = 0; k < regwrd/2; k++) r[k] = 'R';
   for (k = 0; k < regwrd/2 && k < rlen; k++) r[regwrd/2 + k] = ref[k];
   for (; k < regwrd/2; k++) r[regwrd/2 + k] = 'R';
   // Initialize S.
   for (int i = 0, v = regwrd/2; i < regwrd/2; i++)
      s[i] = s[regwrd-1-i] = v--;
   // Initialize D.
   for (int i = 0, v = regwrd/2; i < regwrd/2; i++) {
      d[regwrd-1-i] = v--;
      d[i] = v;
   }

   // Alignment.
   for (int i = 0; i < steps; i++) {
      // TODO: at the end of the alignment, there will be parts of the
      // diagonal that fall off the matrix, in that case the values of j
      // can be restricted only to these words that represent matrix values.

      // Step Right D,S -> D.
      uint8_t R_in = (regwrd/2 + i >= rlen ? 'R' : ref[regwrd/2 + i]);
      uint8_t S_in = 0xFF;
      for (int j = regcnt; j >= 0; j--) {
         // Update R.
         r = (uint8_t *)&(R[j]);
         // Save middle value, AVX2 only supports 128-bit lane operations.
         uint8_t R_out = r[0], R_mid = r[16];
         _mm256_srli_si256(R[j], 1);
         r[15] = R_mid;
         r[31] = R_in;
         R_in = R_out;
         // Update upper and side scores (gap).
         __m256i G = _mm256_adds_epu8(S[j], ones);
         uint8_t * g = (uint8_t *)&G;
         // Compare Q and R (match/mismatch).
         __m256i M = _mm256_and_si256(_mm256_cmpeq_epi8(Q[j],R[j]), ones);
         T = _mm256_adds_epu8(T,D[j]);
         // Minimum between G and M.
         M = _mm256_min_epu8(G, M);
         // Right shift the gaps and insert S_in.
         // Save middle value, AVX2 only supports 128-bit lane operations.
         uint8_t S_out = g[0], S_mid = g[16];
         G = _mm256_srli_si256(G, 1);
         g[15] = S_mid;
         g[31] = S_in;
         S_in = S_out;
         // Minimum between G and M.
         D[j] = _mm256_min_epu8(G, M);
      }

      // Step Down S,D -> S.
      uint8_t Q_in = (regwrd/2 + i >= qlen ? 'Q' : qry[regwrd/2 + i]);
      uint8_t D_in = 0xFF;
      for (int j = 0; j < regwrd; j++) {
         // Update Q.
         q = (uint8_t *)&(Q[j]);
         // Save middle value, AVX2 only supports 128-bit lane operations.
         uint8_t Q_out = q[31], Q_mid = q[15];
         _mm256_slli_si256(Q[j], 1);
         q[16] = Q_mid;
         q[0] = Q_in;
         Q_in = Q_out;
         // Update upper and side scores (gap).
         __m256i G = _mm256_adds_epu8(D[j], ones);
         uint8_t * g = (uint8_t *)&G;
         // Compare Q and R (match/mismatch).
         __m256i M = _mm256_and_si256(_mm256_cmpeq_epi8(Q[j],R[j]), ones);
         T = _mm256_adds_epu8(T,S[j]);
         // Minimum between G and M.
         M = _mm256_min_epu8(G, M);
         // Left shift the gaps and insert D_in.
         // Save middle value, AVX2 only supports 128-bit lane operations.
         uint8_t D_out = g[31], D_mid = g[15];
         G = _mm256_slli_si256(G, 1);
         g[16] = D_mid;
         g[0] = D_in;
         D_in = D_out;
         // Minimum between G and M.
         S[j] = _mm256_min_epu8(G, M);
      }
   }

   d = (uint8_t *)&(D[regcnt/2]);

   return d[15];
}
*/
int main(int argc, char *argv[])
{

   char * qry = "GGGTGGGTCGGTTTTGGGGTGGAGAGAGAGAATATGGGGAAACTTTCCGCACAAATACTACATAATGTATGGTTTGACGCTAGTAGGAAAAATAAAGAGATAGCGAAGTGGTGTACTATGACCTGGAAGATAGTATATTGCTATCAATTTACAGATTAATCTAAGAGTAACTTTTCTGGAAGTATGTAGTTGTGTAAATTCGAAGGAATCTCTGCTATAGTTAATGTATCTTTATGTAGAGTATTCGTAAGTGATCCAAGTAAAATGAGATAAATGTAATAATATTGTCATACTGTTCTATTAAGTTTTGCATATATTAAAACTTTATTCCTCAAATGTCGGGCTATCTAAATAGGAGGATGATGTTGGGCAAGGGGATATTTGATTTGTTATATGGATGTAAAAAAAAGAAGAGGAAGCATGTCAATTTCATAAGCGCGCACGCGACATTTCTATTCTTGGCTAATCCGTACTATAGTTCAAGTAGAAGGAGAATAAAAGTAGTGTAAGCGGAAAGTCTTTTTTAAAAAACTGTACCTAAAGGCTAAAAAAGTGAAACATTTGGTTGGTCTCACCAGAACTTGCTAAGTTTGTTGGCGATGGCTGAAGTTACCGTTATTTTGAAAGATCCCAGAATATCTGTGCTAGGGAAAGGTCCTAAGTAAGTTTAAAGAATCCAGTGTTCAACCAAATCAGTCTCCCCTAAGGGCGTCTAAGCTAATGAGAGATGATCCCTTTAGGAAGCTGAAAGGTTTTGTAATAGAGGAGTTCAAAGAAGGCAAGTCTCACGATGGCAGAGTTTATATAAATATCAAAAATATGTCACTGATGTTTAATGTGTAAGTTATCATAATTGTATGGTTCAACACACCTTGGTAATTATTACTATGTAGAAATTAAGTGCAGCTTTATGAATGTTAACGAAATATGTGCAGGAAAAGTCATAAAACGATTGAGCTGTAGTAGATAATATAAAACAGACTATCTAAACTAAAAGTTTCCTGGATCTTACTTCGCTAAAAGCCTCGAAGACCCTTTTGTCCCTTTTATTTAGTATATCTTTTATTTTAGAGCAGTTCTTCTGGCCCTGTCAAACTACCGTGTATTGTTTTCGAAGTTAATCGGAGTTGATAAGAGGAACTAGAGAAGCAGATGCCGTTCCACAGGTTTGATGGCACATTACATAAGAGTGTTTTTCTGCTGCAGTAGCAGGACATTGATAAGGTAGTGGTGCTGGGCTGAGCGATTCATCTCGTGGTCGCACTACTATCAGCAGACATAAAGTGGCCTTCTCGTCCACTATGCTTCATGTTAGTGAAATAAAGTTAAATGATGAGTAAATACAAGTTGGAGGTCAGTCTATATGAGCTAAGGATATCAGTAAAGTTTTTATGATTTTATTTCATGTCATAGCTTAACAGCACCGATTAACTGATGTATTTTAAAATCAGTAGTTGTGTTCAGTGTAAATCTACTGCCAAATAAACTAAATTAATAGTTCCGTATTCGTCAAACATTAGTTCGGAGATCAGTTAAAAAGTTTTTCCATGATTTATAATGCGTTGTCAAGTGGGCCCCTAAATACTGGCAGGCCAATTATTTTCGATTGGAGTCTATCACGCTTCTTGACTTGTGAACCTCCCTCAAGACAGTCAAGCATCTGCCTTGCCCATTGTAAAGTACTCTCGAAGGTGACAATCCCTGCTTCATATTTCACTGAGAAAGAATCAATGACATGAGGGTGACAGTTTCATCACTGAAAATCCATCAATTTCGCGAATTTTATACTGAAGATCCTACATTTAATTGATATCATTCTGCAGTTTTCCCCAGTGCTACATCATCCATGTTCTCACTTCCATTTGGATTATGTAATACAAATAACTGGATGTCTCCTCATATTAAAAAAACTCAAAAAGAATAACAAAGACCTTGACCTACTTGCTCCCCATCGTCTAGCTCCCTATTCAAAACCGTTGAGACCTCCAAGTCGTTCTATCTAAGCTCCACTTTCTGCTCTATCTGGCCTTCTACTAATTGATAACTTTTGTCAAGAGCAGCCTGCTGACTCCCATCTGTTACTTAAATCCACGTCAGTTCTCAGTCTTCAAGTCTCCGCCTAACACATTGTAATTGTACTTAAATTACTCAGCTCCCATCTGGAATAACTTCCTTGCACTTGGGATTCCAGGGAGCCCTCTTTCATGGGTTTTCCTCCTCTACTGGCTGTCCCGTTCCTTGAGTTACCTCTGGCTGGTTCTCACCCATTCTCGTCAGAACTCATAAAGTTAGAGTGCCTCAGGGCCTCTTTTATTCTCTTCTGTCCACATTCACGTCTCTTGTGACTTTAGGGCTCAGGGTTACAGCTTTAAAATACCTGTCATATGCTGATGACTGCCAAACGCTAATGATGCTAACTGTTATCTTCACTCAAACCAGTCCCCTGAACTGCAGACTATAATAACCAGAATTTGCTATTGCACACCTCTATTCAGAAATTTAAGTTCATCTCATAATTTAAACACACATACAGAACTGTACTCGTAAATTCTAGGCACTTCTCACTTAAACTAGTTCTAAAGCCCACAACCTTCTCATCTCATTTAATGGCAGATCCATCTTATAGGGGTCAGCGCCCGCAAACCTCAGAAAATCATCTTTGACTCTCTTCCAACCGACTTCACAAAATACAAATCTTGTTTGCAAATTCCATTATTCTAAAAATTTAAATATATCCAGATATACTACGTACTATTATTCTTTCAGCCTGCTGCCACCAGTGGGCTGGCCTGAACCGAACCATCACCTTGCTTGGGTTTTATCTAAAGATTCCTGTTTACGCCTGATTCCACTCTCTATAACTGCTAATACCAGTCAGAATGATCCTCTTAAGCTGCATTCTGGACATTCTATGCTACTTCTGGACGATCTGACTATTCCTATTAGTCCCCACCCCTGCTTAGTTTCGCTATCAACCCACTGCTGGCTTCCTTGGTTCCTTGAACAGGTTAACATGTTTGTGAACACATATTACAATTCTATCTGTCCTGATTCTAATATAATAAGCTATCATAAGATAGTGGTGATTAAAAAGACTAAAAAACAAACAACCTCATCTTGTTTTTTACCCTTGCATAATGCTGAGATGCAGAATTGCAAACGAAGTGTGCAATACAATCACATTTTATAGGGTTTTTCTTCCACCATGATGCAGCGGACTATGCGAGCACTACTGAAACATCTTACTGAGCAAATCCTTATCCACAACCAATTCACATTTGTATGCTTCTCACACTAAAGGAACAATAAAAATTTATATTTAGAAAAAAAGTGTTGGTGCATAAAGTCATGATAATATTTCAATCAACAGTAGTGAGCTTTGGTTATTGAATGAAAATGTAAACTGTTGGAACTGAAAACAAATATAATCTTTTCCCAGACCATGATAACACCAGTAGAGATCAAAAGAAATTAGTGTTTCTGAATTCACGAGATATATCATACAGCTATTTGAAAAAGTAGAATCTAGGGCTGGCTCTGGTGGCTCACTCCTATAACCCAGCACTATTTGAACAGGCGAGCGGGCAGGATCACGAGTTCAGGAGATCGAGACATCCTGGCTAACAATGGTGAAACCTCTCTACTAAAAAACAAAAAATGTAGCCGGACTTGGTGGGGCATGTCACTGAAACTGCCGCTCTACGGGAGCGAAGGCAGCAGAATGCTTGAAACGTCCGGAGGGCGAGCTTGCAGTGAGCCGAGATGCCCACAACTTGTACCCATGCCTGGGCGACCAGTGAGACTCTGTCTCAGAAAAAAAAAAAGAAAAAAGTATTCGAAAATGTAAAAGTACCAATAGGTGCTCATACTTTACACCAGGCAGAGGACATCAAAATAAGAGGTAACTGTAGAGCTTAGGAAACCACTGTATGTGTAATTCCAATGAACAATGTCTCCAGAAGTCAACAGAGTCAGAAGTAATGTAATGAAATGTTGCAATATCTGAAATTGGCCCTGAAATTGTTAATTACATTTTTCTCTTTATCAGTTTTTTTGAAACAATGTCTTTGTCTCTGTTAAATACTTGGTAACTAGAATCAACAATACTTTATTTGGAGGGAAATGGTATAACAGGAGTTGATGCATTAGGCGCTTAAACAGCGCATTAAATACCTTGGTTTACAATTTCAAATAAATTTCAACCATTTAAACACTGTAAATATTGATGAATAGAAAAATATACCAAGATTCTGGTCAACTAAGTAGTGTGTGCTAAGTACTCTCCTATAAAAATAACCCTATATTAGTCAGCAGTATAAAAAAAACCCCGTAATACTCCCCACACACCCGTCTCACCATTATGATTCCTTACACATGCGTTTTCAGTGGTTTACATGGGTAAATGCTTTCCACATAAGTGGCCAGACAGTAAGTTTTACTCCTTTATGTATTCTCATGTGCCTTCTCAAACTGCTGGCATCTAGAAAAGCACTTTCCCACATGTGTTAATCACATTGGCTGGCCTAATCGGAAATACCTCTGATCGCAGCTCTTCCCCGAGTTCTCCGCTCATAAGAGACTCTTGACGCGCTGGCTATCATTAGACATAGGTGTTCTTTCAGAGCAACAGTTGTGCTGTGGATTTTCACGTTTCCGTTTCACTGTAAAGCTGTGCACAAATATCTTGAGTGCTGGAAAAGATTTTCCACAACTGAATGTCAACCTCGACGTCTGATTATCATACTTATTTGTGCAACCTTGTTCTACTACAGGTGTGGGCAGTTTATTTGCATCAGAATAATTCAACAGATTGCATTACTCTAAGAATGTCACTGGGTATATTCACTGCGTTTTAATTCTGTCCCCACTGTTTCGTGGGTAGTTGAAAGCCTCTTCTCTTTTCGTTGACGAGACTTTTTCGGTCTAACTGCGCCTTGTTTATGCGATTTGCCTGAATCAAATCTGTAGATACTGCTGATTCTCTCGATTATTAATAATTCTGGCCAGAGTAAGAAGCAGCAAAGTCCTGGTTGAATGTCAATCAATGTTTCCAGTAATACTAGATATCCTCTGTAGAAAAAGATTACGCAATAAAATCAAAATCTCCAATCTTTATTTTCATTTAGTGACCACCTCTTCCACTTTTGAGCATAAGTCCAGCCTGATGAATTTCTTTAACATGTCCAACTGCAAGGAAACAAGGCTACATGACAAAATCGATGCAAAGAAAAACTTCGAAAACAGGAGCTGCATATATATCTGTAAATGTATTCTAAGACCTAATGAAGCAGAATGCTGAAAAAGCACATATACTAGAGAAAATAAGATTTAAAGATATTCATCAGTATGGTTAGCGTAAAAAATCTCCAATTTTACAGAACTTGGTCAGAGATTAAAGATAATGGCTATCACAGCTGACAGTGAACCACTGCAGAAAAATTAAATGTTATAATTGTTCTGGCTTTTTTTTAAAACCCTAGAACACAAAAAATAGACTGATGGTAACTCACAGACTCCTCCATTCATCGCTGAGGCTCTCAGATAGCAACCAACTTTCTGGATTGGCAAGAGGGAAAGTCTATATGACCACTTGTTTGCCAGTATCTATTTTCTCCTGCTACCCTTAGGGACTCTTACATTATCGTTTGCCCAACTTTCTGCCTGTGCATGTCGGAATGCACCCGGAATCTTTTAAATGTAGATCAAAATTCAGTAGGTCTGTGATGGGGCCAGTCTGAGATCTGCATTATTTCTGTCTTAGATGGGTATTCTTCTGTTGCGCCTAAGCAGGAGTGCACTGGTATATATGATAGACTCACCGCAAGAACTTCAATCCTGGCTCGGCTGCTCAGCTTCCGCAAGTAACGTTGGGACACAAGGCCATTTGCTACATGACCTGGCTATTTTTTTTATAGATGCAGGTCTGCTATGCTGCCCGGCTGGTCTCGACTCGCTGGCTCAAGTGATCCTTCCCACCTTGGGCTCCAAGTGCTAAGGATTACAAGCTGATTGCACCCAGCACAGCCTGCATTTCTAATAACAGCTTCCTGGTGATGCCAATGTTGCTACGAGGAATCCACCGTAGAGGAACACCAGTTTAGAATGTAAACTCTCTCTAGCAACCCTACCACCTTTTTGTGAACTACCAAATAAGCTGGAGTGTTCGTGAGTGAGAGCTTACAAAGAAAGACTTAAGCTCACTTCGTCCCTCACATATCTAGTCAAATGTTTACTAAGTCATCTACGATGTGAGGTACTAAAATATTAATAAGTAAATAGTCCTGCCGTTCAAGAAGTTCACAATGTGGTGAACGTGTTTGATAATCTAGCACGGCTCTGGCATTACTCTGCTGACTTAATTAGGGGTAATTCAGCATCTTGGGGTTCAAGCTTTCTTAAGAATGTAAATAGAGTTGAGTTGGTTAACACTAAAAACAGTGACTGTTATAAGTATGCTGAGGATGTAAACGCGTATATCAGTAATTAACCGCCGTCTCACACACACCATCAACACACACCCCTTACCCTCAAATAATCTTCCTACTTGATTTTTCCCTAAATATGGTTTATCTTTGGGAAAGATGATCTCTTTCCCTCTCTGTTGTAAAGTATAAGCCAGAAAAAGGTTTAATCATAACGACAATGTAAATAAAGTGCTGTGATATCTATTTTATAAAGGACTAAAATTGAATTAAAATAAAAATAGCTTAGTTGCATGAACCCTCTAAAGATCTCTATATAGTATGCTAAGTATCTACAAATCTCTACCCACATGTTCTCATCATCTTCTAATTAAACTGCTTTGCCTCAAGTGCACCTGGATGTTTCCCCTTATTAAATAATGTTTAGCATCACAACACTTCTAAAAATATGTCTTTTGGTCCTGGGCCACTAAAAAGATCTTTGGTCTCTAAATTGTGTTTAAGTGCTCGCAATAAAATAAACCGCCAAACAGATAACAAAGGTCAGGTAGCCTTTAAGACGCAATATAAGTTAGCAGGAAGTCATACCACATTAATTGTTCAAGCAGGTCAGGTGCCTATCCCTTAAGACGCCTAAGGTCGGCGCATCACCTGAGGTCAGGAGTTCAAGAACCCAGCTGCCAACATGTAAAACGCCGTGATCTACAAAATAACAAAAATTAGCTGGGCATTGATGGCGTTGCCTGTAATTCCAACGCTACTCGGTGAGGCTGAGCAGGAGAATCCCTTGAACGCTGGGAGGTGGAGTTTGCAGTGAGCCCAGACTCAACAGCCATTGCATCCCACCTGGGGACAGAGTGAGACTCCATCTCAAAAAAAAAAAAAAAAAAAAAAATAATTTGTTCATTCATGAAATGGTAATTCATACAAACTATTTCCAATAAGATGGCTATAATTCAGTCACATGTAAGCAGCACTAATGCAATACTTCATAACAGATATTGTCTTTTGTTTACAAAGTATTAGATAACATCCTCTGAACAGTCACTGAAGGTCATTAATTACATATTGCCAAAGGTACATGTCCTAAATGCTTATAAGATTACCTCAGGACATGCCTATGAAAATCTATTATTAATCCTCATTTTAAACAACACAATGAAAAATCTAGTAGTCCAAAGAAATAAATAACCTGTCCAAAGCACAGAATGTTAGAAACCAGATTTGAGCCAAGGTAATCATGGCCCCTTGATGCAAACTTAATATATCCTACCTGTTTCTTTAATCACGTAAGTTGTAACAATTTCTATTGGTATAACATCCTCTTTACATGTTCTAGCTGAACTCGAGAATTAGCTCACCATCAAGTCTCACAGGAGAAGAATATGTACTGCTAAAAGCAGACTGAACAAAACACCTGGCCATTCTTCAAAGCATTGGTTTCTTTGAATAATCTCAAAGAAAATGTGCCTACCGGTGATTCAAATGAAGATTGTTTTGTTTTTGCATAGTAATTGAGATGAAAGGGAAACCATTATAATTGCAGGCCAGCCAAAAATTCACCACCTGCTCTTCGCTTAATCAACTATACAAGAACTCACATTTGAAGATTTCATTATAGCCAAAATTTAAAATAATTCCAAATAGCATGAAAGTTTACTTTTCTGTCACCTCCCTGCCGCTCACACTGGATACTTCTTACACAAGAAGGTCCTCGTCAAAAAGATTAATGAGCACCCTGATCTAGATTTTTAAATAGATATATTTCCAAGATAATTACAATATAAAGTGAGGAAAGATTATTGCTAATTATACATGAACATCTCTAACAAGTAGATCTGAAAAGAATAATAATATATAATTCAAAAGGTAAACAGGGGTTATCAGGGCAGCATATTTCAGAAAGTGTGTTTCTGTTTTTGTTTTTTCTATTTTTTCTCCGATAAATGTGAATTAAAGGGGTGAGGCAGAGGTAAAGTAAAAAAATAAAGAATTAACGTTCAGTTGAAGTGATAAGGATTCAATTAAAACTTATTTAGCCTCAAGGTAGTTATTAAACCATCTCATTTGAACAGATGGGGAAACTGAGGCCCAAGAGAGATTTGCATCGCATGCTCAAGAGAGACATAGCGACTGACAAAAGATCTAATTCCAAAGCCTATAATCTCCTGTGTCAGAAAGAGTTAATGAACATATATTCATGTTCACTTTCATATAGAGAGCACAGATATAAGCAGGGGTAATTAATCAGTTTTCTCTTGCTTTTATTCCCCGCCAACCTTTTTACCCTACAATCTGTAAATGTAATTGATATTAATCTGCAATTTATATTGGTTTCTTATAGCAAGGGGAGACACCAGTGCCTACATTATCAGATTCTCAGAAGCGCCAACTTCTTGTTAATGCAGGACATCAAAGTAACAATGTTAAGAGAATTCATTTAGCATCTCTCTGACCTTTATACTTCAGTATTTAAGTACTGGTAGGTTAATAGAGAATAACGATGAGCAGAATGAGGGAGACAGAAATCCAGAGGAATTCAAGGACAAAAAGCAATTGGGAAACTGGAAGTAACTAGAATTATTTGTTTGCAAGCCCTGGACCAGCATGGTGAAAGCCCTGTCTCACCAAAAAAATAGCAAACATTAGCCAGGTGTGGTAGTGCACACCTGTTAGTTCCAGTTACGGAGGAGGCTGAAGGTGGAGAATCTGCTTGAACCCGAGGCAGAGTGCAGTGAGCCGAGAATTGCCGCCGACTGCACTCGGCAGCCTGGGTGACCGGGAGCCCGTCTGCAAAAATAAAATAAAATAAACTTCATTGTGTTAATGTTCAAGTTTACATAAGTGAAATCACGCCCTGTAGGCTTTGTTTCAAGTAAATAAACCGTGTCAGAAATCTTACGTTTATTATCTGTGCTATATGAAAAATATGCTGCTCATCCCTAAAAATCAGTGAACCTGATTTCTTTATAAAAAAAATCATTTGTGCATAATAGGTGAAAATTTAGTCAGAGAATGAATGGAAAAAAAGCAAATCTACTTTTTGCTGTGAAGACCTGACTAGCTTTTAAAACTGAAATAAAATTGTACTTTACCTGTCATAGATTAAAAGTTCCTGTGTATATAAACTCCCAACAGTTTCTGAAAATCCATCAGCGTCATCCTGACTCTTTGAACAAGAAAGACATTGTCTCAGAAAGTGCTTCGTCAGATCCCAAAAACTCACTAAAGGAAGCAGCACATTCTACTGAGCTTTAAAACACTGGAATTCCACGCAATCACATATGGTAACCATGTCACAGGAAACCTTGCTTCCCGCTGTTGTTCAGTGCTTCTCTAAAATGTGCTCACAGTGGTTGCGAAACTGCATTTTGAATCAGAATGGAATACCTCTTGATCATAAAAAACAAAAAGAAACAGTAATCTAGAATCTCTGAAGTCTCATCACCGTCAGTAGCGGAAGGACAGAGTACTAACTTAATAAATTTTTAGCCTCCCTTAAAATTCCTTAAGTCAAGATTTCCGATATTATGTTAAAGAATGAAGGGATCGATGCGCTTTCCTATGCTTTGTTACCTTCCGATCAAACTCACAATCTGTTTGACATCCACAATAAAGACGGTGAACTGGCAACACACTCTCTAAACACCTCTAAAAAGCAGCAGCAAACCTGACGCTTTCAGCATCTGTTGAACCTCAGAATTTTCAAGCTCACAGTAGACATACTTAGTACAGATTTTTAACCACTAAGACATGATCCTTGGACAGATAGGGCAGAACAGTACGAGTTTTAAAAACTGGCGTACCGGAAGATCACCAAAAACCTGTATTCGGCCCAGTGCAGTTTCTACTCCAAAACGAGAGGCGGCTGCCAGAAAGCGGGAATTCGCCCGCGCCATGGCTGCGTCAAAGGTCTATCACTCGCGCTCTAAGCAGGCCACACCTTCTCTTCCCACTCTCTACGCCGAGGCGGCATCCGGAGTGACAACCAAAGCCATCCCTCCTCGCTTCTGCCGCCCTGCCTCGTGCCCAAGCTCCCACTCCGGCGAATTCCACAACTGCAGAGGTGTGCCCAGGCCACCGACCGGCTGCCTAGCCGCAAAGCCTGCCACCTGCAGCCCCGACCCGTGCTGGAACTGACACAAGGAGCGCTGCCCTCCTTGATGGCCCAAAGGCTCTAGAGAGACCGGGGATGGCGGGCTGGGTGAAGTCAGGAACTACACCGATAGCAGAACTCCAAGGGGGGAACACAGTCTTCACTCTTCTCCCCATGCATCTGGAGACGCAGCCGAGGCCACGCTCTCCGCCCTCCCTATCGCTATCCACGGTGGCGTCACGTCCGCTCTGTCTTCCCGGGCAGTGTCGGGAGGGTTCTGGGCCATGGGGTCGCGGTCGCCGGCCAGGGCGGCTACCAGAGCTACCACAGAGATGGCGCACTCCCCAGCCATGCCAGTGGGTCCCCCGAAGCAGCAGGCGTCATGGATGACGAGAGTGAGGCTCGCTTAGCTGCGCAGCGCTCCGCCTGTCCTTCCCTCCATCGCGAGCATTTCTGTGCCGGCCATGTCAGCGTCTGTCGCTCTGTCGGCTCTGCGCCGAGGCCCGGCAGCACAGCACCGCGGAAGGCCTCAATCTCCTAAGCCAGCTGCGCACTGCGCTGCGGGGGCATTGTAGTTGCTTTGTCCTCTCGCCCATCATCCCTCCTTCGCGTCGGGGCCCCACCGGGAAACTGCTGCATGTTAACGGATCTCTGCAAATGGGGATTTTTTAGCTGAAATCTTGCAGCCCCTTTCCGCTAACGTACCTGAAAACTCTTGGCACCTGCGGCCCTGGTTTTTTGTGCCCCAGCTCAACTGTACCTCAGCTCCAAGAATGCCCTAACCTGGTGAACAGAATCGGGATGCACGAAAGCGGAGCAGACTGGGCACAGTCGGGCATCGCAACATTAGAGAAGGTGGCTTATACCGGAAAAAGGTTTTCGCTGCGTCTGGACAATAGATTTTAATGAACATTATTTACCAGCCACTCAGACAAAAACCAAGTGATATAATACACAAAATGCTCAAGTGAGGCGACAGGACTAACACTTTTACACTTGATCTTTCCTTCTAGCTGTACATATTTTTCAGTGTAGCTGATGAGTCAAATTCATTTTTTAAAACCCGGACAACATTATCCACGTGGCAAGGCTTCAAAAAAAACATTTGTGAACGAATAAAGTACAAAAAACTTAACAGATTTTTTTATTTCAGCTCTCATTGCTATCATGTCTTTGAACGGACGGCATACATAAAGCTAGCTTCCCTCAGAAAAAAAACAAAACAACACCAAAAGAAAAAAAGCGTGAAATCTCACGTTTCTCCAAGCGAAGCGAAAAAAAAAAAAAAAAAAAAAAGGGATTTAGTGTTTTCGCCACGGTTCGAACGCGGGGAGCCTTTTCGAGTGTTAGGCAACGTGATAAACTAACCTACGGAAACTCCATTGGAAAAGGGTTTTTGTAAAGTCCTTGATAGAAGTGCAATTCGCAATTCCAAGTGATATTACAAATTGAGAGAATGAATATAAGTATTAAAGAAAAAACAGAAAAGGAAAAAATAGCTATGCCCAATTTTGAACAGAGTCTAAAACCCATTTCAAAAGCTTGAATTGCACGCCTTTCTCAAAGTGCCTCGGTACCCGCAGTAAAACCATGCACTCGCGAGTTGCCCTTCCTTTGGGTGGCCTTTTTTTTTTGTCTCACCTGAAAGCGTTTTATTACACATCCTTTCCGCAGGTGAGCTGCTAGAGTCCGGGAAAGAAGCAGGGGCTTTCGTTATTCAGCCGCGAAAAAGCATCCTTTCAGCTTCTGGTGGAAGAACGTGTAGAAATTACTTTTGAATTTCCTACTATTTTGCTTCCGAAGACCAAGCAGAAGTTCTAGAATTGACTGTTGTTTTCAAATTCTCTACAGATGTATCAGCAATCAGACACCAAATGCTTATGACATGGCAAATGTAACTTTCAAATTTTCCACAACGTGAATTTCATGATGACCTGAATAAACTTCACTTTCTGGCAAAAAGACAGGCACGTCCTTACAGCCTAAAAATCAAGAGTACGAATTAGGCTGCCGATACACCAAAAGGATAGAATCGAAATATATATATTATATTTATATAGATAAATATAAATTTTTATACTATTATATATAAACATAAGATTTGTATATACTTTATTATATAACAACATAAATTTGTATATATTATATATATAACGGCACAAATTTATACTATATTTTATATATAAACATAATTTGTATATATTATTTATAAATAGAACATAATTTTTTATATTTATGATATATAAACAAATTTTATATTATTATACTAATAAACATCTTAATTTTTAATATATTTATATATAAACATTAATTTATATATTTATTATATAAATAAATATAATTTTTATATATTCCTGATATATAAATATACAGTTTTATATATTATGATATATAAATATAATTTTATATATTTATGATATATAAATATAAATTTATATATTTATGATATATAAATACAATTTTATATATTTATGAATATAAATATAAATTTTTATATATAGAATATAAATATAAATTATATATAAATCTTAATATAGGTATAAATTTTTATAATACTTTATGATAAAAATAAATTTTATTTATCATATCTAAATATAAATTTTATTTAGTGATACTAAATATGAAATTTTTATTTATGACGATACTAAATATAAAATTGGTTTATTTATCAGATATCTAAATATATA"; 
   char *   ref = "AATTCAACTGACAATGTGAAAACCTTCATTAATCCTAAAAACAAAGAAAAAAAGGATTCTTGAAATCTATGGAAAAAAAGTGAACATATGCAAAAGGCTAGCCAATCTGAGAATAATTACTGAAGGATTATTTGAAGTACCATTAAAAACATAATGAAGTACATATCTTGAGTCAGTATTGTATGCATTAAGTAACAAGTATGCTAAATACAAAATGTCAAGCTGTTAATATGAATACTACTGTAATATACACAATTAAGCAAATCTTTAGAAAAACACATTATCAATAACAATGACTTGAAGAGGTACAAAATACATATGAATTAAAATAGAATTTATTATATTACAAATAATAATGATATATTAAATTGAGCTTAGACCTAATAGAAAGAAACAACTTCAAACTTTCCATTTTCACTGTAGTGTCTTTGTTGAATTGCTAAATATTAGGTACAAATGCTCAAAGAGGATGTTTTTATGGCATACAGCAGAAAACTAGGTTAATATTCACATGTAGTCATGGTTTTGAGGTTTTTGACTATTACGCCTTTTAATTAATGATTTAGCAACCTTGTTTATTGAATGCATTTCTTTGGTAATTTTATTCTCAAACCCTATCTTAACTTTTTACTACCAAGATGATGATATGAATTATGAAAGTAATCGGCAATAAATACTTTTATATATAAACTCCGTTTACTAAAAAGAATCAATATTAAAGAGAAGCATTGAAAATATTATGAATCCAAATACCCAATTTTCCTTTTTTTTATGGCAACAACATTGTAGAGTTCCCCTATTTTTGTCCTCATGAATATATTTGAGAGAGTAATCACGTCCAGCATTTAGCAATATCATATTGTGGAGGGGTGTTTGTCGGATAAATCATATAAAATCCCGTGAGAAGAATACTTAAAATAACTACTCAATATCCATAATATGGATTTTCTATGGTAACTTTTTAATCAGAATATTAGTATTGTAAAAATTAGATTTTGCTTCGAAAAAATAATTCATGATTTTTTTAAGAAAACAAATGCAAAATCCAAAAAAGTCTTATAAAAATGCAAGAACCTATAGAGACATGTCATTATACAAATACTTTTTCACTCACACTGCTCACATATTGAAAATATCTATTGAAAATGAAAAGCAAAAATGTGGATCTCAGCTTAACCCTTTCATATAAAATACAACATTCTAATTTACTGAAAATCAATGTTACATTCCATTAGCAGGGTTCAACATAAGACATCCTTCAAGTCTTTCTATAAGTTCTAAAAGACAATGGTATAGAACAAGAAAAATACCAAGATGACACATAAATAATACGTAGCAAAGTGTTTGTGTTTTTCTTACGAAATAGTAGTAATTTTGTTAGCATTTTCTATGCGGCAAGTTTGTACTTCACAAGTCCTGTAGTGGTCACAGCAGTTTTTGCTGTGTTCTTTAATTATAGCTTAACTATTCTCATAGCATATCCTTGTATGATATACTTAATAAATAAAGGATATAGAGAGGCAATGTATCTATATCATGACTCTGATAAATTCTGCCTTGTCACCACAGAAAACCTTGATCACGGTCACTGACAATTTTCAACAAAGCTAGAAAATACAAGAAATATCAAGACTTCATGCTCCACTCTAACTCTGTCTTATTTTGACATAAAACTCAAACATTTTACTTGATGTTATGCTTACGCTACATCAGTTATATGCATAGCCCAACCTTTATTCATGTTTGCCTACAAAAATATGTCTTGGCAAATGTGCACATGCAAATGAATTGAGCCCAACAAATGAGTTCCCAACAAATGTGTTGATTTCTCTCTAAAATATGGCCAGACAAGATTGTGTAATTCTACATGGCCATATTATTAAACTTGTAAAAATTATATGCTGACCTGTCTCTAATAAATTATTCTGTATAATTATTCATAGCTACAGCTTAACAGTTTTCTAAAAAACTCTTACATCGACTATACCTTCAAATATGATTAAACTCCCTTTTAAATTTCCCTTGGCAATAGTGTTTTACATAGGTCACAATAATGGATAACCTTTATGTTCATTTTAATCGTGACTCATATAAAAAACAGTGCAAAATGTCCCATGTTCTACTGCTTCATATTTTAGGGAAGTTTGAATTTGTTAGCAAATCCTTTTAGCTGTTCTATTGTTGAAGGCTAAAACATTAATCTTCAAACAGAAATAAAAATTTTTACATACATTTGCCCATTTGCTTGTTCAGGATATAAAAACCAACTAAACAATAGCAATTAAGAGAGGCTACAGGCCCGGCACGATCGGCTCACACCTGTAATCCCAGCACTGTTGAGCGAGCGGGTCGATACTTAGGTCAGTGAGTTTGAGAACAGGCCTCACCCACATGGTGAAGACCCGATCTCGTACTAAAAATACAAAATTAGCCGGCATCTGGTGGCAAATGCATAATCGCAGTACTTGGGAGCCTGAGGCTGGAGAATTGCTTGTAGCCTGCGAGGCAGAGGTTGCAGTGGAGCTGAGACGCGCCATTGCACTCCAGCCTGGGCAACAAAACAAACTCCGTCTCAAAAAAAAAAAAAAAAAAAAAAAAAAGAGAGAGACAGAGAAGAGAGAGAGCTGCTAATCAGTCGATATAGAACATACTATACGTTTTCAATCATCAATAAAACATTAATGTCATTGGTGTTGCATTTCCCTTGAGCATGAGAGACTGTGTGACATAAACTAAAGATCAATTACTTTAATGAATCAATACTACAAGTTCTTTGTTATAGAATTTTTCAGAATAAGGAAATAAAATTGAATGTATAGGCATACTTTGAATTGTGATTCTATTCTTACTAACTTTAGTTCCATTTCTTCACTCTAAAACTCTTCATTGAGTAAGCTATCTTTTGCAATTATCTTACTACCAAGAGATTGATATTCGTCTAATGCCACAAATATTATAATTATTACTAAATTCTACCAATTCTAGGTACAATTGAATTGTTTTAACAGTACCTGTATAAAAGTCATTTATTCACCATAAGCTTTCAATCAAAATAATATGTGACTCTGACTACCCTCCACCTAGTTAAATTGTTTCCTCTTGCTGCCCCCTTTAAGCAAATTATATTCCTCCCATTCACCCTTCCTGATCCAACGACCTCAGCCACTAATCCTGATTTCTTGAACACACAGTTGGTCTGCCACGAAAGGATTAGTTATTTTGTCTTCGCACGGTCTCGTGACTTCAGTAAGCTCGGAATCCATACAAAATATCTATATTGTCATTGCATGCTCTTCCCTTACTCATCATGTTTTTGAAGTTTCACTTCTATTAGTGTACCTCCTTTTGTCTTAGTAGAGGTGTTAAAAATATGCCGCACATGTGTTATCCAATCTTCTGTTATTAACATTTTGATTATTTCATTTTTCTTCTCCCTGTTTGGTTACTATGATGAATATGTAATAAACATCTTTGTTAAAAGTGCTTATATTAATGATAAATGTGAATGTTAATATACTTTTATAGACTAAATAGCTGCGGAATCTTATGCTCGTGCCGCCGAGCGAGTGTAGAACCTCTCTATTGCGCATTCATCTAAATGTAGGGCCTGCTTTGTCGAAATAAATGGATCAATCATGCCCTGCAATTTACACAGATTGTAAAGTTATGTTCAAAATATAATCCCTTTAAGATGCGAACGTGTTCAAGGAAAACATTGAGCTAGGAGGAAGTGGAGGCTTGCGTGTAGAGTTGGGCAATCTTAGCAAAGGTTTCCTACTTGCGGCAACTTCTCGCAAGCCATCCTACCTCCATACAAACACATAGACAAAAAGCACCAAATCTCGCTGACCACTACTACTATGATCATGCAGCATCATCCTGTTCAATAACCAACAAGAAAAAATTATCTAATTATCCTTTCCTGGCCAATTTTGCCCTGACAGTTTTGTAGGCAAGTACTCACAATTGTAAATTAAACATCAACCGCTCCACGGAACCACACGCTTCGCCTATCCATCTACCCTCTTCCCTGAAAAGCCCAATAGTTTTAGAACCAACTCCAGGAGTGATTCCAGCGGTTTCACAGAACACCCTATTAGCGAACCCTCAAACTGAGCTACTCTTCTTTGCCGCAATGTGAGCTGGACTACACTCCACCTTTTCCTGAGTTCTTTAACTTCTCGGGTAGTAACTTGGCGCTAAGGGTAGATGTGGCTGCCTATCTATCCTGCTATTTTAAGACCTGTATTTCGTTTAGAGTTCAACTGTTAGCTAATATCTCTTGTTAATATTTCATTATTCTTTATATTAAACTTCCTCTCGGACCATAATGTTCTAGATTCCTTCTTTTGATTGAAATCAGGACTGAGTAGTACAATTGCTTGATTTCTTATAGTCAGTTTCATGTTATACAACACATTGTGTCATTTTTGTAAAACTCACTCCTTAGCTCGATAAATATTACGGTCCAACGAATTTCTTAGATTACCCTGCCATTCAAGATCTTTCCTTCAAATAGCATTAGATTATACGTCGTTTTCTACGTTTTTAACCATTCTACTACGGCCGCTTGAGAAAATTTCTCGCGCATAGGTTTTCACGATTGTCGAAACTCGCCTCGAACGCCAATAATTGTTAAGCATCTTTCATGTGCCTGTTGAGGCCATAACTTATGAATATTACTCGTGTAAATACATGAAATGCCTTTCCAAATTTTTGCCCATTAAATAAAACTAGGTCTATTCTTCATTATCAAACTCGTTTATCCACACATAGAACTTTGCATAAATTAGGATTACATGTCTACTTGGTCAGATAAAGCACACTCGGAGAATTGTTCCATAAGTATATTCTTCTCCCTTATGAACTGTCTTCCCTCTTACTTTTTAATAACTTAGCTAAATGTCATTCGAAGAGCATAAGTTTTTTAATTGATACAAAGGGCCAGTTCATTCGGTTACCTATCAATTTTTAATGCAGCACATATAATGATAACAACAATTAAGATTAATCTTACCCCTTCAAATTACCATTCGTTGTTGAGAGCACCATGTGAATAATGTAAGGTTCATTTACTTTTTAAATCACTCATGATTGCTTATCGATAACTATTCTATTGCCCAAACCATATGATCGAAATGTATTTGCCTTCCATAGTCCACTCCTCAAATTACACCTAGAGATAAAGCTTTTCTAAAATAACTTCCTTGTTGCCCTGTTTCAGCCTACTGCGCGAGGAGTGCAATGGTTGAACAATACCCCAAGTTGCGACGAGAACTGGATTGTTATCGCATTTCTTAATTTTCAAGTTTTTAGGAGTAAAATCCATATTCTACACTAAGTAGTGTTTATTTTTACAGCTTTCCAGAAATGAAGATTGTTTGAATCGGAAATATGGCTGTGGATTCAAATCAAGAACGTTATCCATCATAATAAAGATTACATATTTGACTCCAAAACTTGAGACTATATACTACAAGTTTGTGGCGTCCCTCACACACACCAGATTGATAAACATATTCATCTCCCTCAAGATATGTTAGCTCTATTGTAAGCCAGTGAAATTGGCCTCAACTACCTGACTCCTGACTACACCTAAGTCAACTCCGAACGATAGTCTGCGTGTTGAATCAAGTTTCGTGTTCTAAATTTATGTAAAGGATAAACTCACATTGTGATCTTTTTGTAAGCTCTATCTACTTAAGCACAATAATATAGGAGACGATCGCATTCCATATTGTTCGCACTGTAACAATGTATCCTTCTTATGTAATTTAATGCTAGGGAGATGACACTTCTTGGTATTTGTGTATATGAATACTAAAACATAATATTTCTTCTTAGGTACACATCCCTTATCTGTTGCAGTATAATGGGCCCTTTAAAAATTATTTTCACTATTATAAATTAAAGCTGCTATGAGCATTCATGTGTAAGGCCTTTCTGGTGGTACATATCTGGTGTTCACATTTTTTACTGGTAGGAGGTCCCTAGCACCTAAATGGCTAAGTCATCACCAAGCCCAATAAAAGGCTAACGGTGAGTTTAACATGAGCATTTGCGGATTAGAACTCCTCAAACTGTTTCAAGAAAGGGTACTTATACATTTTATATTCCCACGACAGCGAGTGTATCATGAGAGAATTTTTCATGGGCTCCACCATCCTCTCCTTGAGGTAAGTCTTATGAGGAATGATTAAGAACTATGTATATCTAACATCATGAGTAAACAACTCTAAAGAGGCAGTGTAAGTACTAGTATCTCTCATTAGGTGGCATTCATTTGCATTCTCTAATTTGAAACTTAGTTATGGTTAGTCATCACTCTTTCATAGCTACATTTGCCAAAAACCAGACAGTAATATTGTGCTTCTTTCTGTGGATTCTGTCTTGAAATATTCTTTGTCTTATGTCATTAAAGAAAGTGTCTCATATTGGCGATTATTGATAGACGCAAATTAATATGAGCTCAACGACATACCTTTCATTGACTAAGGTGATTCTGCTAAGTAACCTTTTCGCCAATACTAGCTCTTTGTTGTTAATCTCGAATTCCAGCAGTGATCTTTGAAAGACATTCATCAAATCTCCTCATTATTGGCAAAGCTAGCAACATCATTTATTGTTCCCTTGTAAAACAAACTCGATGTCTTTTGTGTTATATTTAGAAAACTTTGCACAATTCAAAGTGTGTATATAGATGTTATATTGCATTAAGATTTATTTTAAGTTAATTTTCCTATGTAGTGTGAGGTATAAGTCAGATGGAAGTTCATTTGGGGCAATATGGAATCTCAGTTTTTCCTAGTATAGATTTGTTTCACTGAGATGTCTATTTCTTTATTAAAAAAATCATTGTAAACCATTTATGTGAGGACTGATTCTTGATTTTAGTAATTTCAAAAGATTAGAAAAACATCATAGCGAGTACAAAATAACATCCAGTTATGACTTACAAATTTGGTAAATCATGTATAGAAAAAATGATAAACGGTACAGCTCACAAAAACTATACAAACATTATGTGTAAGGGTGAAATATATGTTAAATTATCTTAAATTCTGAAAAATCAAGAAAGATTGCTATCTAATCAGTATGGAAAACAAGAAAATAATAAAATTACATGATTATAAGGAAAACAAAACTCATATTCAAAGATGAGGCATGATTAATGTATATAAAGGAACCCACAGTTGATTTACAGATCAATCATTAAAAATTTAATATATTTAGAGCCAAATTATCAAATCGCACAGTTAATTAAAAGATCATTGATTTTCTTATACGGCAGAAAAACAGAATGTGTCATCAAAAAATTATGTTACTGATATTCAATCAACTAGGATCGTCACAAAAATGGTTACCTTCTAAAGTCGCAAATGAAGAACAAATGAAGAGCCTATTAATAAATAAAATGGTAAATATTACCCCATGGCGCAATCAAAAGAAGAAAAATTACTACTAATTCTTGCCAATTGCAAATGCTTCCCACCAAATATGAAAATTTAGAGTACATCCACCTTTCATTCTATAAAGGAGTAAAGGCAATTTCATAAAACTATCACACTAAATCGAAAATTGAATGAAAAATATTTGGTAAATAATTTAAGTGAAGATTTATACTAGTCACAGAAAAAGAATGGTACCATGAATATTGCCGTAGTTGCTTCCTCCTCGAGAATAGAAAAACAAGGTAACACAGTGCCTCGCTTAGGCATCCACACAGAGCCGATGCTATCGGACCAGGGTCTGGAGTCCGAAATGTTAGCAAATCAACTGAGTACACCAAAATACCAAGTTATAAGTAGATGGACAAGGAAATTGTGTACTTGGGGCAAAACAAGACACTAAATGGATTCAATACGAAGTGAGATGAGCAGAAAAAATAACATTCATATATACTTTGGGAACATCTAGCATTTGACAAAGATGGAATAGAAAAAGATAGTAGTAGAACTTGATGACTACCCTACAATTAAACACAGGCGCTGGTAAAACCTGAGTTAAAATGACAAATTATCATACGAGCGCTATCTCCATCCCTCAAATCCTTGTTATCTCCTACAATCTTCCAAAAAAAGAAGCTAAAGATCTATTGTGAAATGTATAAACTGAAACCTTCAATAAGACACACAGTAGACTTCATATAAACTTGAACATGAAAAATATTTCGCAAACCAAATACAAAGACATAAAACACATAAGTTAAAATTTGAGCATTTCCACTTACATTAATACTAACATATAATTAACCAGTAGACCACCAAAAGGTGATCAAAAAGTGGAAAGTAAGACATTTGTAACATATACAAATGTGTTGTGGTGTATGTACTTACATACACATTATATTGTATACTTCCCTTTCTATAATAGCTTAATATAGATTTGTAAAGATTTATACAAATGATTAACAAAAAGATATACACCTTACACATACCAATGTGAAAATAAATTGAACATCAGACTTCTAATAAGAAGGATATATGATAACTATTCGACCAACGAAAAATGTTAACAAATATTTACACCCGGCAAAGTAGAAGTTAACTATATAAAATATAATTTATCATCAGTTTAAAAAAATGAAAATGTCAAGAAAGTAGATAAGTGTTGACTCACCAGCAAGTGAGCAACAAGAATTCTCTGTGGGATATAAATGAGGTACAACACTTTGAAAAAATAACTAAACATCATCACACAAAGTGAAGATGGCATCACACAACCCCTGATCCAAACAATCCACAACTAGGGGCATTCACCACCAGGAAACACACCTTCCAAATGATATCTCACGAAGACGATGCTCAAGAATTATTGTATCTAAGCGAGCTTATCATTGTCAAAACAAGTAAAACCAAAACCGCTGAGAGAGCACAGCATAATCAATCGGGAGAAAATCGATAACTACTATTTTACAGCAATACTACAATAAATCTACACAATATGAAAAATAAATTATAGCATGAACTATAAGAACTAATACAGATGGTATGACTATCGAGAATTATAAAAAGTGGGAAGTGAATACATAGAGTAATGTCAACTTAACAATGTACAACAAGAATCAGCAATCACCGAATATTTAATTATAAATTGAAAATAGTGCGGAAATTGCAAAAACAATTAATTGAATTAGCGAAAACAATAGATAAGTACAAACCCACAAAAGTAAGGAAAGAAAAAGGAAAATAGGAATAAAACACAAAGGTCAAGCTGATAGCCATATCTTTTTGAATGGAAAAAGTAATAAAGCTTTAACTTAAACCTAAATTTTATTTCTTAACTGACAAAAGTGAATATAAGTATACCGCTACATAATCAAGACTTATCATCATTTGATCCACCTACACATAGAATATACACATACTCTGTATGTAAAGTAATATGTAATGTCGTTTTTTAATTCGTGAATCTAATATATAATATATTACACAGAAATAAACAGCTTGAAAATGAAAACAATGAAATATAAATTTTCAAATTTTCAATGGAAAATTTAAAATTAGATAAAATCAATTAAGGCATATAGTAATAATGTAACAATATGAAGATAGAATAACAATACTTTATTTGGTAAACAAAGGCGTTAGAGTTTTGTCAAGCAAGATTTTGTTTAAATACAAAGTTTAACTAATGAGAAAAAATCAGCAAATAAAAAGAAAAATAATGCCCGACAATAGGAGAAAATTGAGGCAGTGTGGATAAAAGTGTAAATTAAAATACGTGAAAATTTGTGAGCCCAATATTAATAACCGCGCCCACAAGTAATGTAAAAATAAAATAACAATAATTTTGAAGGCCTCAGACATATGAAGTAACATAAATCTAGAATTTGCGAAATACAATGACAATTATTAAATACAAATACACAAAAATTTACTAAAAACATAGTGTGTCTTTTCAAAAGTTTAGAAATAATAGTTAAGTACTAAAAATATATGGTAAGACTGAATCAAAGGACATGTTAAATTTATTACCTGAAGAAAAACTGTTAGTAACAAAAAAAGAGGGGAGAGATGAAAAGCTATAAAGCTGGTGGCAAAGCAACCCAGGATAAGAGGATATGAATGAAAAAAGCAAAGTATAAGCCACTTGTCTATTCAGAAGATGGACAATGTGATTAACTCAGCTTCATAAACCCGTGTATCTAGGTTAGAAATAGTCAAAAAATAATACTGTACTATGAAGATTTACAGTGAAAATTGAGTATGTAATGACTTAATATCTCAATAAATGCATTTAAAAAAAATGAATGAAAACAATGCCACACTATCTAATGTTTGAGGAATACAGTAAATGAAAGCTGTTAACTTAATTTTTATAAAAACGTACAGGTTTAAAAATAATGCACGGTATTAAAAGATAATAAGTCAACCAGGGTCAGGGATGGAAAGTGGAGGCACTGTTCCTATAAGGGTAATATAATTGCCATTAAATATTTATTTTAAACGTCTTAACCAAATCATTATAAGAGAAGAAAATAAACAAAATAAACTAGAATAAATAAAAGTTTGGCAGAGCAGAAAACCAATCAATAAAATAAGAAAAGGCAAAGACAGCAGAAATGGAGAAATATTTGCAATCATATATGCTGACTCAATATTACCATCACATCTGACAAGGATTAATATTAAATTTTAAATCGGAACTTACGACTCAAATAATCAAAAATCCAATTAAAAATGAGGTCAAAAGGATATGAACAGACATTTTTCCAAAAATAGACATAACCCACACATTTACAAAGAGTATACGAAAAGGTGCTCAAAGACGTCATTATTTAAGCAAGCGGCGAATCAATCAAAATGCGCACATGTCATTCCTCTCACACTGGGATGTATCTTGCAAAAAGCAAAAGATAATAAACAATTTTGAAAATGTGACAAAACATTCAGCAAATGGGAAACCCTTCCTAATACATTGTTTGCAAGAATGTAAATTGGCACAGCTAATTAATTAAGAACATTACTGGATGCATCCTATAAAATTTTAAAATATTATTATTATAGGTTTCTAGAACACCGTCACTATCTGGGATAATGTGTTATATATATGTTTATGTTTATGTGTGAAAGTGTGTTGTATATATAAGGTCCCAAAAAATCACTTAGTCTTTCGAAGAGAGAATAATCTTGCATAAACCTTGTATGTTTAGATTACAGCAATTACCATTTATAAAAGTCACGGATACGGAATAACCCAAGGTGAATATAGATAGATGAGATGATAAAGAGAGAATGATATATATATAATACACATGCTCTATACTATACCTACACACCCTCCTTAGTAATATGCACAATGTAATATTATTCAGGCCTTAAAAAAGAGAAGTTTTGTGTTTTGCAACAAAATGGATGACCTGGAGATATCATGCTAAGCAAAATAAGCAGACACACGAAAGACACACTAAAAAATATACTACAGATCTCAGTTATATATGGTCAAACTCATAGCAAAAGAAGTCAAAGGCATGATAACCAGAATGGAGGGAGCAGAGAAGTGTTACACAGGATACAATTCTTGCAGGGCTGTGAGATGAGTTAACGTTCCCTGGAAAGCTACATGTCCGGCATGATGACTACGTAGTTAATAAGAATGTGTCTAGGTACTTGAATTTCTAGAAACGTAACTCTAAGCAGGCGCCGTGGCTCATCGCATGTAATCAGCACTTGGAGCCGAGGGCCGGGCGATCCCACCGACGCTGCAGGATGACCAGACCATCCTACGCTACACACCGGTGAACACCCATCTCCTAAATATCACACCAAAAATTAGCCTGGCACTGGGGCTCGGAGGGTAGTCCAGCACGGAACGCTAAGCAAGCGAGCATATACGTCGTCGAACCCTGCGAGGCGAGCTCGCAAGTTGATCCAAGACTCTATCCACCTAGCCTCACCTGAGACAGAGCGAGGACTCCATTCTCGGAAAAAAAATTATACCTTTACGATGTTCTCAACTAGACACACATCCCTGCATCATACAACACACCCAATTCACAAGAAAGGTAACAAATGAGGTGATGGACTATGAAATCTATATAAAAGCTGAGAGATGGGGTAATATTCAACAACCATAAAGTTCTAACGTAAAAAAAGCCTCTATCTATATACAATACACTCTAGAAATAACTAACAATTGTTATTTGCACTAATATGCCTAAAGATACTGAAGAACTTTTATAATGGAGAATATAGAGAATCTAAACGAGCATCTGGAGACTGCAGAGCATCTAGAACAGAGAATAAATATATCATCCCCTTAGAGGGCTCCGGAGAGCCGACAGAAAAAACACGCACCAGGCCTGCACCCGAACACCACTCTGCTTCAGAGACGCGCGGAAGACTTTACTGTCAATGAACGAATGCACATCCTTAACATGCTTTCCTCTACCGCCAACTGAAGATGTTCTGTCACCCTGTTTTTGTAGCGGCAGCAGAGTTGGCAGTCAGACCATTCACAGATGCCTCGCATCGTTGGTGCAAGTTACATACAATAAGCGATTGAAGCCAGAAAAAAGCACTATCGTCATGTTCTCAATCTCTTTCATCGCTCATTAGAGAAGAGACACTACCGACTTCTTCATTTCAGTACACGTCTTAAGGATACACACTGCTCCAGCGACATTCTTCCTGGGCATTCAAGAGTGCGAGTACTCTGAGCCGCCCCTCTGCTCCAGAAAGGTCACATCGTTTGCCCGTGCCTTTTGCAAATCTAATAATTTTATTTTAAGTTTGTGTTTGGACATGAAGTCTGGTAGAGCACTAGGACATGATTCAGCAAGACATTATCACAACATACAAGTGGGCCCTTAATGCCCACTCTAGACCTACCAGGCTACCTCTTCCCCAAACTCTCTCTTGACACCTCATGATGGTGAGCCTACCTTCCATCGTAGTCCTCCCACACTTGGAGAGGCTGGGCATTGGCAAGCAGAGAGTGAAAAGCGCATGGTTGCACTGCACCGGCCTCTTGATGGTAAGGGCAAAAAGTGCGCATTCCCTCCAGCCTTGTGCTTCCACAAGGTTTTGGCTCTCACCTACCCATGTAGATCTAGGTGGCTGAGTGTCCGCCAGACACAGGTTGCAATCATCCTGAGGTCTTCAATCATCTGTGCATTGAAGAGTCCCGCCATGAAAAGATATATTGATTTCCCTGCCCATCTCGAGCCCTGCCTTTTTTTGTTTCACTGGGACCCTACCAAATTGTAGCTGGCCCTGTCTATAAATGTCTATAATCCCCCAAAACAGATATAGATTGGCTAGAGATGGGTAACTTCCAGTCTTATATGGAGTTTGATAGAATACCTGACGATTCCTCCACCAACTAAAGACAGAAGGCTGGTGAAATAGAGTCGCCACAAACAGTAGCCACCATTTGTGGATGGCATGCCTGACAGCGACGTGTTCTAGGCGGTAC";
   int width = 256;
   //   uint8_t * qry = "tgagctagcgatcgat";
   //   uint8_t * ref = "tactgcagtcggacgt";
   //uint8_t * qry = "tgacgtacgtacgtagtcgtacgtcagtcagcgtatcgagtcgtacgtcgtgtcgtacgtcagtctgacgagtcagcgagcagtcagtcgtacgtagtcgtacgtacgtcatggtcagtcatgcgtacgtacgtacgtagtcagtcgtacgtacgtacgtacgtcgatcgtagtcgatcgtactgcgtacgtagtcgtcatgca";
   //uint8_t * ref = "tgagtagtgtacgtcatgcgtacgtacctgacgtatcacgtagtcagtcactgcaactctacgacaccatcgacactacagcagccgccatagcgagatatagcagcatactagcacgttccgcgcttgacgacgcacgcgagcagtcacagcgtacagtcacagtacgtacactgactgacgacacatacgacgaaaaatagtact";
   //int width = 32;

   int qlen  = strlen(qry);
   int rlen  = strlen(ref);
   //   int width = align_max(qlen,rlen);
   
   int score = simd_align_sse2(qry, ref, qlen, rlen, width);

   fprintf(stdout,"score: %d\n", score);

   return 0;
}
